### ISSUE TITLE
Run custom script instead of default

### ISSUE THREAD

**Issue by anddimario** [Strider-CD/strider#1004]
Hi, i've installed strider-custom script and i need to disable the default prepare script to run my own, but it seems that custom prepare doesn't override the default. Have you informations about that?

**Comment by knownasilya** [comment]
Make sure the strider-custom is ordered after any of the other plugins in the plugins page.

**Comment by anddimario** [comment]
I've tried to add it after all other plugins and as first plugin (only after the Runner: Default), without results. I've only custom script, slack and default runner plugin.

**Comment by knownasilya** [comment]
What are you trying to override/accomplish?

**Comment by anddimario** [comment]
I'm working on strider-github to get tags, i don't want that default "Prepare" action run (the github clone) that give me back an error, but i want run my custom script that has my ad hoc commands.

**Comment by knownasilya** [comment]
That's currently not possible. I have some changes to strider-github I'm working on to support releases.
