### ISSUE TITLE
contact / contribution

### ISSUE THREAD

**Issue by ellerbrock** [Strider-CD/strider#1006]
hi strider team,

first at all i want to thank you for awesome work on strider.
i really appreciate your work and support in the open source community.

i work as a full stack javascript developer and work at the moment for a large company setting all the fancy new stuff up for later later scaling. personally i used before more the open source systems like travis ci and others and when i logged into jenkins i allways had this 90th feeling :)

on the weekend i wanted to have a closer look to your system and to drone.io.
so i started to pull the docker image and opened with big eyes the docker hub page and there was nothing. normally im used to a quick introduction what to do, what ports to open or something like that. after i got it running i could nowhere find the information what the default username and password is and find it on someones blog. i was getting a bit thinking if i should move on but i really liked the idear having a full stack stack and don't wanted to give up to early.
somehow i got it running but wth all the stuff it did not write the data into the mongo database.
i got lil bit angry and gave up with the docker image with the decision to made maybe my own one later on.

so i installed strider locally. all went easy and smoof and i had a cli tool what was cool.
i came to the point with the plugins. of course it makes sence to first at all update all plugins to the latest version but there was no way to say update all, so i had to do it manual for each one of it which sucked. thats the kind of moment where guys like us start writing a tool for it or so :)

i also found a plugin which not even had a repository anymore (404).
so i opened the issue and came in contact with one of you.
later i finally had the stuff running and wanted to test with one repositroy on github what i can do.
and this was the moment where i almost was gone. 500 error witht oauth stuff.
later on i found out what to do and answered it here in the issue but i think if things stay like this you will lose a lot of people who want to use your system (i was almost on of them).

this is why i come no here to play and want to help to fix few things up because i thing the project is nice and i would like to bring something good back to the community.

so i made the small fix on the file (need me quite a while to find where it was coming from).
and the last few hours i created a first alpha version from scratch with docker.
its much more lightway and build on alpine linux. i would like to create a few versions which are really nice to use and make fun to use.

lets say a version for exploring and have a first look.
where you can run with one command all the setup and get a first look.
then a developer version, more focused for debugging and changing von enviroment variables and stuff like that. and then a production version, focused for security and speed.
after all made a clear to understand step by step introduction (again to make it fun to start playing with it). when the devops stuff is running i would also be interested to write some cool stuff for the system.

so sorry for writing all that here and open an issue but i don't know where i can get you guys else.
you can get me on mail via strider@frapsoft.com, or on twitter @frapsoft, skype @frapsoft or gitter @frapsoft.

i guess i can show you a first impression soon what i have done so far.
would be great if i can get access for the docker hub account as a team member to make things nice. i just use these registries not so long myself but u can have a quick look here: https://hub.docker.com/u/frapsoft/ . i registered yesterday on https://quay.io/user/ellerbrock which is actually really nice! so i would like to register u there too. the main reason what makes it really interessting is that the run vulnerbility scanns on the images for open source projects for free (on docker hub at least u have to pay for it). and i moved all my stuff there too and jenkins example i just build less then a week from the official repo had around 25 vulnerbilities. 
anyway, later on would be great to get the hole workflow that we automatically create new docker version after the tests passed with your ci / cd system. this is one point i also really interested in.

ok so long talking, hope i hear something from u guys :)

cheers

**Comment by knownasilya** [comment]
We are interested in a nice Docker image for getting up and running quickly, and would point to it from the readme once we had something nice that just worked.

**Comment by knownasilya** [comment]
Also, you can chat here: https://gitter.im/Strider-CD/development

**Comment by ellerbrock** [comment]
hey there,

i got an 404 from gitter, maybe no access rights?

**Comment by knownasilya** [comment]
https://gitter.im/Strider-CD works too. Not sure why the other doesn't work. I tried adding you there but all it says is "Forbidden".

**Comment by ellerbrock** [comment]
yeah somethings not right there. i tried as well but i can't do anything.
but i could open a issue or something in gitter did u at least see this one?
so you guys have there the admin rights?
are u all together connected inside and just me who can't connect?

**Comment by ellerbrock** [comment]
good morning,

i just double checked before going to work.
i still can't access the gitter channel  :(
maybe you can ask the gitter support whats the problem.

for the docker setup i need from you the information about the configuration variables for the start. it would be important to know which are optional and others required.
so i guess the most simple setup don't need to pass anything for example the starter image to have a first look what is strieder. 

when i got the information i will play with the implementation for that.
i was also thinking about an small cli setup / configuration tool or something like that ...

cheers

**Comment by ellerbrock** [comment]
**update**

i guess i know whats the problem.
whats the access rules for the development room?
i would guess private and you tried to add me won't work, right?
a tried it myself with a room for my organisation on github and got the info that only members can access this room i private. so if you add me to strider could work. 

for a test i create 2 gitter rooms:

https://gitter.im/frapsoft/strider - room with public access
https://gitter.im/frapsoft/striderdev - room with private access

i added you to both rooms.
can you check if its working?

cheers maik

**Comment by oliversalzburg** [comment]
@ellerbrock 404 for striderdev

**Comment by ellerbrock** [comment]
i only added @knownasilya before so guess this was the reason for the 404.
i added you (@oliversalzburg) to the room, can you try it again?

**Comment by ellerbrock** [comment]
i added you as well to the public room.
frapsoft/strider - public
frapsoft/striderdev - privat

but i guess as long i don't add you to my organisation frapsoft you can't join.
can you try to access both rooms and just make one post to see if its working?

if you still get the 404 for the frapsoft/striderdev room i can add you for this test to my organisation to see if its working ...

**Comment by ellerbrock** [comment]
and another question for the setup.
do you have for the strider project a privat github repo as well?
i work on the docker stuff and would like to keep it non public before we discussed the general way how to set things up first. not because some secret stuff is hosted there or so i was more thinking in case i post it public maybe someone will try and run it and just get disappointed if it fails.

**Comment by oliversalzburg** [comment]
I'm not aware of any private Strider repositories.

**Comment by ellerbrock** [comment]
development still gives me an 404:

![dev](https://cloud.githubusercontent.com/assets/2029255/20883226/47ba98dc-bae5-11e6-8192-47a32427b99e.jpg)

and on the https://gitter.im/Strider-CD/ i just can open a topic but can't see anything else.
or do i miss something here?
![pub](https://cloud.githubusercontent.com/assets/2029255/20883257/74d50258-bae5-11e6-89f3-331994fd5b0d.jpg)

**Comment by oliversalzburg** [comment]
Seems like Gitter is a bit annoying with this stuff: https://gitter.zendesk.com/hc/en-us/articles/200178951-Gitter-communities-and-rooms

Strider-CD on Gitter was created from the organization, so it's only accessible to organization members and there is no way around it. At least that's what it looks like for me :P

**Comment by ellerbrock** [comment]
so what now?
we just keep talking in this issue?

lol i see myself already writing a chat program loading via github api the comments :)
https://api.github.com/repos/Strider-CD/strider/issues/1006/comments

anyway, i wanted to keep going with the docker stuff.
like i mentioned before would be nice to get informations about all the initial variables to pass with a few informations for me to understand whats going on and which one are required or optional ...

**Comment by oliversalzburg** [comment]
I don't know if @knownasilya has any more options regarding the room privacy settings. Otherwise we might want to create new rooms. I'd like to hear back from him regarding this matter before taking any steps though.

**Comment by knownasilya** [comment]
I've exhausted all options on gitter. @oliversalzburg give another room a try maybe.. I'm a bit busy with a new baby boy 🚼

**Comment by knownasilya** [comment]
@ellerbrock if you want to help with documentation, please see #1007.

**Comment by ellerbrock** [comment]
jupp got it, and thanks for your help.
let me know when you set things up for later discussion.
i'm playing locally with some idears ...

and good look with sleeping next day :)

**Comment by ellerbrock** [comment]
hehe,

lets make things small and secure and get started with mongodb:

official mongo repo: 150MB
https://hub.docker.com/r/library/mongo/tags/

woop woop: 55MB :)
https://hub.docker.com/r/frapsoft/mongodb/tags/

more coming soon ...

**Comment by knownasilya** [comment]
I'm going to close this, please create a specific issue for docker image optimizations.

**Comment by oliversalzburg** [comment]
https://gitter.im/Strider-CD/strider might work

**Comment by ellerbrock** [comment]
@oliversalzburg thx buddy its working!

![](http://i.giphy.com/wAxlCmeX1ri1y.gif)
