### ISSUE TITLE
github webhook events - PR & merge job fails

### ISSUE THREAD

**Issue by crobinson42** [Strider-CD/strider#1013]
I've noticed this bug:

- I push code to a branch `pre-release` - a job starts in strider
- Immediately after I go to github and submit a PR from `pre-release` to `release` branch - a job is added to the strider queue (the `pre-release` job is currently running)
- I click "merge" on the PR
- As soon as the `pre-release` job finishes, the next job in the queue for the `release` branch immediately errors (turning yellow) and offers no text/explanation in the console.

**Comment by knownasilya** [comment]
Did you try this flow with `DEBUG=strider* startstriderhere`?
