### ISSUE TITLE
GIT URL not generating right for deploy and test

### ISSUE THREAD

**Issue by pramodhdn** [Strider-CD/strider#1017]
I have manually configured to a private git repo through the Strider admin screens. Tried to run the deploy, and the deployment begins to run, but hangs. I noticed that username and password are not getting populated.  Here is what I see in the console -

Prepare > 
git clone --recursive https://[username]:[password]@pn5958@mygitcloud.domain.com/scm/st_ixt/ixt.git . --branch master

Please note username and password are not getting substituted with the username and password configured in the admin screens

**Comment by knownasilya** [comment]
That means they are hidden, but are passed through successfully.

**Comment by pramodhdn** [comment]
Then how do I find out why its hanging and not cloning ?

**Comment by knownasilya** [comment]
Try running strider with `DEBUG=strider* bin/strider` (or how ever you start strider instead of `bin/strider`) and paste the results (don't forget to remove any sensitive material from logs).

**Comment by pramodhdn** [comment]
I see the command line terminal says it couldn't resolve the host... I have verified that the host is right and I am able to open it using a browser. Here is the rest of the information -
strider-runner-core:job Job "587fcdc9c1dd190a6df5eb5f" status: command.done { '0': 'command.done',
  '1': 
   { exitCode: 128,
     time: Wed Jan 18 2017 14:19:22 GMT-0600 (CST),
     elapsed: 56 } } +3ms
  strider-runner-core:job Job "587fcdc9c1dd190a6df5eb5f" status: phase.errored { '0': 'phase.errored',
  '1': { time: Wed Jan 18 2017 14:19:22 GMT-0600 (CST), exitCode: 0 } } +1ms
  strider-runner-core:job Job "587fcdc9c1dd190a6df5eb5f" errored: Git clone failed with code 128 Error: Git clone failed with code 128
    at badCode (/Users/pramodh/fixt_st/strider/node_modules/strider-git/worker.js:93:11)
    at updateCache (/Users/pramodh/fixt_st/strider/node_modules/strider-git/worker.js:159:19)
    at ChildProcess.<anonymous> (/Users/pramodh/fixt_st/strider/node_modules/strider-simple-runner/node_modules/strider-runner-core/lib/job.js:252:9)
    at emitTwo (events.js:87:13)
    at ChildProcess.emit (events.js:172:7)
    at Process.ChildProcess._handle.onexit (internal/child_process.js:200:12) +0ms
  strider-runner-core:job Job "587fcdc9c1dd190a6df5eb5f" status: stderr { '0': 'stderr',
  '1': 'An unexpected error occurred while executing this job. Please report at https://github.com/Strider-CD/strider/issues\n\nGit clone failed with code 128\n\nError: Git clone failed with code 128\n    at badCode (/Users/pramodh/fixt_st/strider/node_modules/strider-git/worker.js:93:11)\n    at updateCache (/Users/pramodh/fixt_st/strider/node_modules/strider-git/worker.js:159:19)\n    at ChildProcess.<anonymous> (/Users/pramodh/fixt_st/strider/node_modules/strider-simple-runner/node_modules/strider-runner-core/lib/job.js:252:9)\n    at emitTwo (events.js:87:13)\n    at ChildProcess.emit (events.js:172:7)\n    at Process.ChildProcess._handle.onexit (internal/child_process.js:200:12)' } +0ms

**Comment by knownasilya** [comment]
Git error 128 is usually something with ssh keys.

**Comment by knownasilya** [comment]
Try to add the Strider project ssh key to your git provider.

**Comment by Colin6618** [comment]
add ssh keys may solve the problem @pramodhdn

**Comment by knownasilya** [comment]
Let me know if the issue still persists and I can reopen this issue.
