### ISSUE TITLE
PICs Missing on the doc

### ISSUE THREAD

**Issue by Colin6618** [Strider-CD/strider#1018]
e.g: https://github.com/Strider-CD/strider/blob/master/docs/guides/continuous-deployment/ssh.md

PICs Missing on the doc page which could help users made the correct configration.

![image](https://cloud.githubusercontent.com/assets/3047309/22637854/72762278-ec7f-11e6-8364-4393839d826e.png)

**Comment by knownasilya** [comment]
The guides are not complete yet, we would love your help, see https://github.com/Strider-CD/strider/issues/1007
