### ISSUE TITLE
PRs on language repositories.

### ISSUE THREAD

**Issue by Psykar** [Strider-CD/strider#1019]
Hi, I've had a PR on strider-python open for nearly a year. It's pretty simple, but seems that the repo may be unmaintained? Thought I'd see if poking the main repo might gain some traction, apologies if not.
https://github.com/Strider-CD/strider-python/pull/12

**Comment by knownasilya** [comment]
Will release a new version tomorrow.

**Comment by knownasilya** [comment]
Thanks for the ping.
