### ISSUE TITLE
Cleaning up old jobs

### ISSUE THREAD

**Issue by pwdng** [Strider-CD/strider#1020]
Hi,

Is there anyway of cleaning up old jobs from the Mongo DB?
The UI displays the last 20 jobs but nowhere can I find any mention of what happens to old jobs.
I have many jobs in the DB to the point where Mongo is now refusing to start because of insufficient disk space.
Apart from removing job documents by hand from Mongo, is there anything else I can do?
If not, why keep them if we can't view them? And maybe a config parameter would be good to have, don't you think?

Thanks

**Comment by knownasilya** [comment]
Good idea, maybe even with a default value where it cleans up jobs after they are x old and there are more then y.

**Comment by pwdng** [comment]
Until it's possible to configure how many jobs the GUI can display, I'd say the default value should be the maximum number of jobs that are displayed (i.e. 20). What's the point in keeping more if you can't view them?

If there are people out there that view the data directly from the Mongo DB, the limit should not be applied if the number of jobs is greater than the limit itself. A log message would be preferable with maybe an extra option to force Strider to delete the old jobs.

**Comment by Colin6618** [comment]
There are many old jobs, and query all of them cost a lot time.

![image](https://cloud.githubusercontent.com/assets/3047309/22878260/16b617e6-f214-11e6-9834-f3c6583430f6.png)

Removing job documents by hand

**Comment by oliversalzburg** [comment]
Lightweight :P
```shell
> db.jobs.count();
10661
``` 

Those 10k jobs don't produce any noticeable effect on performance. If you think you're having trouble with 126 jobs, the count is not the problem.

**Comment by pwdng** [comment]
Agreed.
The only reason I brought this up is because my build process produces a lot of output and therefore takes up a lot of space.

**Comment by oliversalzburg** [comment]
Maybe someone can suggest something that can be run in the `mongo` shell from a cron job? Then that could be a workaround for the time being.

**Comment by knownasilya** [comment]
Like a prune that removes the oldest jobs beyond n jobs.

**Comment by pwdng** [comment]
Something like this should do it:  `mongo localhost:27017/strider-foss  /tmp/clean_old_jobs.js`

where /tmp/clean_old_jobs.js is:

```
var MAX_JOBS = 20
projects = db.projects.find({}, { 'name': true }).toArray()
var nb_deleted = 0
var i, projects_len
projects_len = projects.length
for (i = 0; i < projects_len; i++) {
   var cursor = db.jobs.find({ 'project': projects[i]['name'] }, { 'created': true }).sort({ created: true })
   var jobs = cursor.toArray()
   var jobs_len = jobs.length
   for (j = 0; j < jobs_len - MAX_JOBS; j++) {
     db.jobs.remove( { _id: jobs[j]['_id'] } );
     nb_deleted++
   }
}
print("Deleted " + nb_deleted + " jobs")
```

**Comment by knownasilya** [comment]
We could add that as a command to strider-cli

**Comment by oliversalzburg** [comment]
Excellent idea!

**Comment by knownasilya** [comment]
Implemented in the cli, see https://github.com/Strider-CD/strider-cli#prunejobs

Available in master of Strider. Let me know if there are any issues.

**Comment by oliversalzburg** [comment]
@knownasilya Very awesome!
