### ISSUE TITLE
Unable to start any build

### ISSUE THREAD

**Issue by zouloux** [Strider-CD/strider#1024]
Hello guys.

So I upgrade from 1.8.0 to master and there is something weird.

I can't launch any projet from web interface. I tried to create new project so this isn't happening because of the upgrade I think. What's happening :
- When the project is HTTP git, launching goes to the terminal page and it is stuck on `git clone ...` command. Unable to cancel it, I need to restart strider.
- When the project is SSH git, nothing happens at all when I click the build or test button.

Didn't tried with other checkout methods.

Also, nothing special showing in strider CLI.

Tried with `npm install -g Strider-CD/strider` installation method and also `git clone ...` + `npm install` method.

Building and testing runs fine with 1.8.0 version.

Running in Ubuntu 16 with global npm package installed at `~/npm`.

Thanks for the help.

**Comment by zouloux** [comment]
Didn't saw that but in fact I got this in CLI when I try to build :
`2017-02-20T11:26:46.026Z - error: (node:9040) DeprecationWarning: Mongoose: mpromise (mongoose's default promise library) is deprecated, plug in your own promise library instead: http://mongoosejs.com/docs/promises.html`

**Comment by oliversalzburg** [comment]
Please try setting `DEBUG` to `strider*` and run your tests again. There should be a lot more log output, hopefully with something interested.

But, just to be sure, you didn't mix up any file access rights during the upgrade?

**Comment by knownasilya** [comment]
Pull down from master again, I fixed the socket/passport thing.

**Comment by zouloux** [comment]
Working now :) I had to create a new MongoDB. I think migrating from 1.8.0 to 1.9.X is breaking something inside the DB or file system.

**Comment by knownasilya** [comment]
Thanks for getting back on this.

**Comment by zouloux** [comment]
Thanks to you guys, this is working so well now and I can't go back anymore. I'll try to convince my boss to donate also a little something :)
Thanks a lot for your passionate work !
