### ISSUE TITLE
Automatic deploy via custom script plugin on pull request

### ISSUE THREAD

**Issue by harishajdarevic** [Strider-CD/strider#1026]
Automatic deploy didn't start on pull request. 
I make pull request from develop to staging branch and it only runs npm tests. After tests are successfully passed it stops. 

Than I need to manually run "Test & Deploy" to run deploy from "Deploy" section in "Custom Script" plugin.

Thanks in advance

**Comment by knownasilya** [comment]
The project settings page has the following option:

![screen shot 2017-03-14 at 9 42 36 am](https://cloud.githubusercontent.com/assets/34726/23903350/9f40b1e2-089a-11e7-97c0-088737bb8837.png)

make sure you have it enabled.

**Comment by harishajdarevic** [comment]
@knownasilya everything is checked ( active ).

**Comment by knownasilya** [comment]
Which provider? And have you updated your plugins?

**Comment by harishajdarevic** [comment]
Provider: bitbucket
Plugins: all up to date

**Comment by knownasilya** [comment]
And Strider is on the latest version?

**Comment by harishajdarevic** [comment]
@knownasilya 
Version is 1.9.4 
Is there easy way to update to latest 1.9.5

Can I do that with npm update?

**Comment by knownasilya** [comment]
You should be able to just `npm install -g strider`, if that's how you installed it initially.

**Comment by harishajdarevic** [comment]
@knownasilya 

There was issue on our side. We have strider-middleware which hooks tests or test and deploy functionallity after pull requests. 

There was if, else. In case if it is master branch than make test and deploy and for all other do tests only. 

So, I just extended if branch master or staging make test and deploy and it works.

Sorry for causing mess with this.

**Comment by knownasilya** [comment]
No problem
