### ISSUE TITLE
Add a Heroku account with Error: Failed to add ssh key

### ISSUE THREAD

**Issue by josefwijaya** [Strider-CD/strider#1030]
After successfully running strider and log in and then trying to add a Heroku account. After login to the heroku account and accept the authorization process it will redirect back and show error as shown in the picture.

I believe this error is coming from the heroku side, but I have configured my account settings properly to allow this.

Strider Version: 1.9.6

in this case, I have set up the environment variables such as
DB_URI=mongodb://.....
PLUGIN_HEROKU_CLIENT_ID=....
PLUGIN_HEROKU_CLIENT_SECRET=....

![image](https://cloud.githubusercontent.com/assets/18253945/26394986/486540c4-40a1-11e7-9ebc-2d9706647b00.png)

**Comment by xgalen** [comment]
@josefwijaya is this still happening?

**Comment by josefwijaya** [comment]
@xgalen I'm not sure anymore, because I end up not using strider. But I love what you guys have done :)

**Comment by knownasilya** [comment]
Thanks for getting back on this 👍
