### ISSUE TITLE
Pull request not triggering build

### ISSUE THREAD

**Issue by jackSnaps** [Strider-CD/strider#1034]
My GitHub webhook is configured to fire on push events and pull requests (open, closing, editing, etc). Ideally, I want this to trigger a build of the to-be-merged branch and through custom scripts run my testing suite. However, whenever github fires off a POST request because of a pull request, nothing happens on my Strider instance. Commits to a branch still trigger builds, however.

Am I confused and this is user error? I just want to be able to trigger tests on a build whenever someone creates a pull request for the master branch.

Thanks for a great library

**Comment by knownasilya** [comment]
You need to enable the pull request feature in your branch settings.

**Comment by jackSnaps** [comment]
The "deploy on pull request" option? I've enabled that and opening a new pull request still doesn't trigger a build

**Comment by knownasilya** [comment]
Did you update your gihub plugin?

**Comment by jackSnaps** [comment]
updating right now, I'll let you know how it goes. thanks for the help

**Comment by jackSnaps** [comment]
Updated to 2.3.3 and still getting the same issue. Any ideas?

**Comment by knownasilya** [comment]
Try running strider with `DEBUG=strider:*` env var, and see if there are any messages that might help.

**Comment by jackSnaps** [comment]
No messages when a pull request webhook is fired. When I fire a normal commit, I get these messages 
`strider:backchannel job.prepare - strider.json not found, skipping config merge +6m                                     strider:backchannel new job was created +13ms                                                                           strider:backchannel job saved +22ms`

**Comment by knownasilya** [comment]
Sounds like the webhook never gets triggered most likely. You can put a breakpoint here: https://github.com/Strider-CD/strider-github/blob/master/lib/webhooks.js#L308

**Comment by jackSnaps** [comment]
I logged out the webhook payload and it is a pull request, but it strangely get's caught on the `if (config.pull_requests === 'none')` block, yet doesn't log out the debug message. Very confused as to what is going on.

**Comment by knownasilya** [comment]
What version of Strider are you using?

**Comment by jackSnaps** [comment]
1.9.6

**Comment by jackSnaps** [comment]
I've logged out the config ( from req.providerConfig() ) and got this

`{ ....
  repo: 'cms',
  auth: { type: 'ssh' },
  pull_requests: 'none' }`

What is this config being made from? GitHub or Strider? Every branch on strider has deploy on pull requests enabled.

**Comment by knownasilya** [comment]
Oh, you also have to update the Provider: github (toward the bottom of the left menu) settings in the project config page.

**Comment by jackSnaps** [comment]
What do you mean by update?

**Comment by jackSnaps** [comment]
Oops.

**Comment by jackSnaps** [comment]
THANK YOU
