### ISSUE TITLE
[Solved] Change http to https and deliver/access everything with/via SSL

### ISSUE THREAD

**Issue by natterstefan** [Strider-CD/strider#1035]
Hi,

I am new to Strider, so please forgive me if I open a duplicate Issue. I used the search but all I found was [this old issue #860 from 2015](https://github.com/Strider-CD/strider/issues/860). How can I set up Strider to deliver the frontend with via `https` and not `http`? Do I need to set this in the Strider Config somewhere or just handle it on my Apache server (eg. via `.htaccess`)?

Because currently everything is delivered with `http`.

Thank you for your help.

**Comment by knownasilya** [comment]
You have the correct idea.  Have the server that proxies strider, nginx, apache or what not, be the one to handle the https connection.

**Comment by natterstefan** [comment]
@knownasilya Works, thank you.
