### ISSUE TITLE
Jobs are blocked when a deleted branch from GitHub is launched

### ISSUE THREAD

**Issue by xgalen** [Strider-CD/strider#1038]
Hi all,

When we remove a `branch` on GitHub, it calls Strider with this:

**Headers:**
```
{
    ...
    X-GitHub-Event: push
    ...
}
```

**Payload:**
```
{
    "ref": "refs/heads/deletedbranch",
    ...
     "created": false,
    "deleted": true,
    "forced": false,
...
}
```

As the call comes from a `push` event, we can't disable it but Strider can't download the branch and gets stuck.

Any solution or suggestion?

Thanks in advance :D

**Comment by knownasilya** [comment]
You could submit a PR to add logic checking for that here https://github.com/Strider-CD/strider-github/blob/master/lib/webhooks.js#L300

**Comment by knownasilya** [comment]
Try updating to GitHub Plugin v2.4.0
