### ISSUE TITLE
Cache npm install

### ISSUE THREAD

**Issue by felipeprov** [Strider-CD/strider#1040]
First, sorry if this is not the best place to post this kind of question.

I am using strider in my enterprise, and  i loved it.

I have two projects in this moment:
- One using nodejs
- One using Angular4

The project using nodejs is very small, and i can deploy in seconds.

But the project using Angular4 always take more than 10 minutes to clone the git repository, install all dependencies, run the tests, build, and  deploy.

I would like to know how could i keep the node_modules folder between runs.
I tried some configurations but i feel i am missing something...

Best regards

**Comment by knownasilya** [comment]
You need to enable the nodejs plugin, and then enable "Strict" caching in the settings for NodeJS on that branch.

**Comment by felipeprov** [comment]
It works

Thank you
