### ISSUE TITLE
Can't clone from GitLab

### ISSUE THREAD

**Issue by iamstiil** [Strider-CD/strider#1043]
Hi,
I'm currently struggling with cloning from GitLab.
When doing so, I get following error:
![image](https://user-images.githubusercontent.com/4603306/32415077-6fcc3cae-c287-11e7-8416-d6934fddb036.png)

This is the error in the console:
![image](https://user-images.githubusercontent.com/4603306/32415092-bc2f9cee-c287-11e7-81d6-674210d32044.png)

And my server shows this:
![image](https://user-images.githubusercontent.com/4603306/32415098-0ffe649a-c288-11e7-8d63-04e397505ff3.png)

I set up my server with GitLab hosted on gitlab.example.com, and strider on strider.example.com, but using a nginx reverse proxy on the same server.

Do you have any idea why it is not working?

**Comment by xgalen** [comment]
Have you tried this https://futurestud.io/tutorials/strider-how-to-connect-with-gitlab-and-run-tests-automatically ?

**Comment by knownasilya** [comment]
@pavethiran was the above guide able to help you through this?

**Comment by knownasilya** [comment]
Gitlab API was updated, update that plugin to get the fix
