### ISSUE TITLE
Website Broken?

### ISSUE THREAD

**Issue by Anzumana** [Strider-CD/strider#1046]
Hey,
your website seems to be broken
http://stridercd.com/.
Maybe this is not the official page anymore ?
In that case you should update 
https://github.com/Strider-CD
Description. If you have the domain there should be a forward to the current one.
As there are a few blog post comparing different ci solutions and they link to 
stridercd.com

**Comment by knownasilya** [comment]
The site is http://strider-cd.github.io/ thanks for letting me know, I've updated it in the org.

**Comment by LC43** [comment]
are you still managing the migration? images don't show up in some parts of the guide:

http://strider-cd.github.io/guides/providers/bitbucket.html

the guide looks like this:

![bitbucket-strider-2018-0jan-13__3-5-36](https://user-images.githubusercontent.com/48201/34902214-ad6a8996-f80e-11e7-802d-61ded84ca5a5.jpg)

what i see in the markup:
```
<p><img src="" alt="Bitbucket Application Information"></p>
```

**Comment by knownasilya** [comment]
We are still in the process of moving over the guides from a blog post, see https://github.com/Strider-CD/strider/issues/1007
