### ISSUE TITLE
How to make different projects run [deploy] at the same time?

### ISSUE THREAD

**Issue by RephoneYin** [Strider-CD/strider#1047]
Hi all, I'm new to strider. My question may be stupid.
I have many projects which are crawler scripts. I want to make all projects run at the same time.
But now one project can only start to run after another project ends. 
How to make many projects run at the same time? Or where can I find some clues to realize this target?

**Comment by knownasilya** [comment]
You can set `CONCURRENT_JOBS` to something other than 1. It's documented here: https://github.com/Strider-CD/strider#configuring

**Comment by RephoneYin** [comment]
Thanks a lot. I @knownasilya . I did add CONCURRENT_JOBS in [.striderrc] file. It did not work at all.

**Comment by xgalen** [comment]
@RephoneYin  you can find here more help http://strider-cd.github.io/guides/configuration.html
I hope this helps.

Could you paste the content of the file? Is the file created into the `strider`'s directory? Version of `strider` and `nodejs`?

**Comment by knownasilya** [comment]
See the guides for details on striderrc
