### ISSUE TITLE
Clone + Yarn install + Yarn test -> Test fail but work on local machine

### ISSUE THREAD

**Issue by Anzumana** [Strider-CD/strider#1049]
To reproduce 
https://github.com/devtools-html/debugger.html
is the project that i tried to do this with.
Clone + Yarn install + Yarn test
I put yarn install and yarn test into custom script plugin.
Not sure why its not work

**Comment by knownasilya** [comment]
Did you get any output from the test? Also try running Strider with `DEBUG=strider*` and paste the logs as well.

**Comment by Anzumana** [comment]
needed to clear the cache for the project as the snapshot for the tests did not match.
how do you usually set DEBUG=strider* just for future reference. zshrc ?
Thanks for the quick response btw :)
In the process of hopefully running strider at our company so still figuring things out.

**Comment by knownasilya** [comment]
As an environment variable when you start strider in the terminal/startup script.
