### ISSUE TITLE
Adding Heroku account redirects to localhost

### ISSUE THREAD

**Issue by useo6** [Strider-CD/strider#1051]
Hi,
I'm trying to add a Heroku account to my Strider project. When I click "Add a Heroku Account", it shows me a page where I click "Allow" to allow strider to access my Heroku account. After clicking on the button, I'm redirected to http://localhost:3000/ext/heroku/oauth/callback?code=<some code>.
I know, that there're already some reports about that issue but unfortunately, I cannot get it to work and don't know what the solution was.
On Heroku, I already registered a new API client and set the corresponding callback URL ("http://mydomain:port/ext/heroku/oauth/callback"):

![grafik](https://user-images.githubusercontent.com/13544117/35474700-1fe4d4ac-0392-11e8-9395-3a89b281677d.png)

After I created the Heroku API client, I've done the following on my VPS:

export PLUGIN_HEROKU_CLIENT_ID=<API_CLIENT_ID>
export PLUGIN_HEROKU_CLIENT_SECRET=<API_CLIENT_SECRET>
npm start

But unfortunately, it still redirects to localhost:3000 when I try to add a Heroku account.
I also already removed the "Authorized Applications" in Heroku, but it doesn't solve the problem. The SERVER_NAME for strider is also set in my .striderrc file:

```
{
        "server_name": "http://mydomain.tld:3000",
        "port": "3000",
}

```

Any idea what's wrong?

**Comment by knownasilya** [comment]
What version of Strider are you using? Also, did you get a chance to update all of the plugins?

**Comment by useo6** [comment]
I'm using Strider 1.10.0. I already updated the plugins some days ago and the currently installed version is 0.1.2

**Comment by useo6** [comment]
Alright, I figured out that my environment variables were incorrect. The SERVER_NAME variable was applied, hence I thought everything should be configured. But obvoisly it wasn't.
Now, I'm having another problem with Heroku, but I'll open another issue because it has nothing to do with the localhost issue...
