### ISSUE TITLE
Can not login anymore

### ISSUE THREAD

**Issue by real-artswan** [Strider-CD/strider#1055]
Yesterday at some moment (possibly after OS updates) I faced the issue with some older strider version (don't remember exact version now).
I put my email, password, press login and it just reloads the login page.
Logs even with DEBUG="strider*" says nothing interesting: each click on button login just logs line like
2018-02-28T14:00:50.605Z - info: username: mymail@mail.com
I tried to add new users using strider-cli and tried to overwrite existing user with new password, it didn't help.
Also I tried to update strider to the latest version.
Then I installed everything on a fresh system and it worked at first and I was able to deploy my project once but at some moment after that it stopped to login users again.

Any help would be appreciated!
`$ lsb_release -a
No LSB modules are available.
Distributor ID: Ubuntu
Description:    Ubuntu 16.04.4 LTS
Release:        16.04
Codename:       xenial

$ node -v
v8.9.4

$ mongo --version
MongoDB shell version v3.6.3
git version: 9586e557d54ef70f9ca4b43c26892cd55257e1a5
OpenSSL version: OpenSSL 1.0.2g  1 Mar 2016
allocator: tcmalloc
modules: none
build environment:
    distmod: ubuntu1604
    distarch: x86_64
    target_arch: x86_64
`

**Comment by knownasilya** [comment]
Have you tried deleting the project and users from mongo first?

**Comment by real-artswan** [comment]
I've tried right now. 
1. Removed projects
2 Tried to login
3 Nothing
4 Removed users
5 Tried to login
6 It showed message about wrong user and log "no user" line 
7 Added user via strider-cli
8 Tried to login
9 Nothing

**Comment by knownasilya** [comment]
Are you running it via localhost or a tld?

**Comment by real-artswan** [comment]
It is on AWS t2-micro

**Comment by knownasilya** [comment]
I wonder if it's an https issue..

**Comment by real-artswan** [comment]
No, it is a plain http.

**Comment by knownasilya** [comment]
Yeah, that's what I mean. Like the browser blocking the request since it's not https. I would try and reinstall everything from scratch.

**Comment by real-artswan** [comment]
Do you mean that https should work without problems?

**Comment by knownasilya** [comment]
I'm not really sure since there are no error or anything obvious that I can tell. A fresh install is probably the best bet at this point.

Are there any logs in the browser console?

**Comment by xgalen** [comment]
We have working Strider with `http` so I'm not sure if that could be the problem.

**Comment by real-artswan** [comment]
In fact the problems is on the fresh system as I mentioned in the first post. I created special fresh AWS instance, installed fresh nodejs, and mongo, and pulled strider from git, added user and were able to login and setup project and deploy it one time, after that I couldn't login anymore.

You know, today I got back to my first working server where problems has started initially and where I removed projects after that, and I were able to login there! 
I successfully created project, pressed "Deploy" button and it pushed me to login screen and I couldn't login anymore.
So I think it somehow relates to project config, but removing project from DB doesn't solve the problem immediately. I even tried to drop "strider-foss" DB and restart app.
Could you tell me if it stores any information somewhere outside DB?

**Comment by real-artswan** [comment]
Unfortunately, browser's console says nothing interesting too.

**Comment by xgalen** [comment]
All the user's information is stored into the DB.
Is it possible that the tests or the deploy are removing info from MongoDB? I mean if you have checked that the user you have created to login into Strider is still there when you can't login.

**Comment by knownasilya** [comment]
It could be a bug, but yeah check the db before first login and after first login, and then after failed login and see if the user data changes at all.

**Comment by real-artswan** [comment]
Definitely user is still there, I see it in the DB and I see it by strider behavior: if I use wrong user name or password I see correct error message in browser and in logs as well. If I use valid credentials it just reloads login page without any errors.

May be it creates some temporary files or cache somewhere? I would know why the behavior changes in time as it is pretty weird. May be some of plugins affects it?

**Comment by knownasilya** [comment]
I'll give it a try tomorrow with a fresh install.
