### ISSUE TITLE
Gitlab hook plugin not working anymore

### ISSUE THREAD

**Issue by ecoitsolutions** [Strider-CD/strider#1058]
Hi there,
After updating to latest version the gitlab plugin is not working anymore. On Gitlab logs i see invalid WebHook URI. as Webhook the plugin automatically setups the following:
http://IP_ADDRESS:3000/project/api/gitlab/webhook
Tried to run that URI manually and i get invalid response from Strider. 
Any clues?
Thank you!

**Comment by xgalen** [comment]
Repeated issue: https://github.com/Strider-CD/strider-gitlab/issues/107
Closing here.

**Comment by xgalen** [comment]
You have opened the same issue twice in two different repos.
