### ISSUE TITLE
Git clone failed with code 500

### ISSUE THREAD

**Issue by firstfleet** [Strider-CD/strider#1060]
git clone --recursive git@github.com:firstfleet/test.git . --branch master github 34s
An unexpected error occurred while executing this job. Please report at https://github.com/Strider-CD/strider/issues

Git clone failed with code 500

Error: Git clone failed with code 500
    at badCode (C:\CICD\strider\node_modules\strider-git\worker.js:106:11)
    at updateCache (C:\CICD\strider\node_modules\strider-git\worker.js:172:19)
    at C:\CICD\strider\node_modules\strider-git\lib\index.js:126:5
    at Function.<anonymous> (C:\CICD\strider\node_modules\gitane\index.js:173:7)
    at next (C:\CICD\strider\node_modules\gitane\node_modules\step\lib\step.js:51:23)
    at ChildProcess.<anonymous> (C:\CICD\strider\node_modules\gitane\index.js:159:9)
    at ChildProcess.emit (events.js:180:13)
    at ChildProcess.emit (domain.js:439:23)
    at maybeClose (internal/child_process.js:936:16)
    at Socket.stream.socket.on (internal/child_process.js:353:11)
    at Socket.emit (events.js:180:13)
    at Socket.emit (domain.js:439:23)
    at Pipe._handle.close [as _onclose] (net.js:541:12)

**Comment by knownasilya** [comment]
@firstfleet can you test with `DEBUG=strider* npm start` and past any relevant errors?

**Comment by knownasilya** [comment]
Ping

**Comment by enfo-mi** [comment]
Facing the same issue here: Dump from DEBUG.

`Thu, 13 Sep 2018 13:48:28 GMT strider-runner-core:job Job "5b9a6aabd4fb2f591695684f" status: phase.done [Arguments] {
  '0': 'phase.done',
  '1':
   { phase: 'environment',
     time: 2018-09-13T13:48:28.116Z,
     exitCode: 0,
     next: 'prepare',
     elapsed: 0 } }
Thu, 13 Sep 2018 13:48:28 GMT strider-runner-core:job Job "5b9a6aabd4fb2f591695684f" status: command.start [Arguments] {
  '0': 'command.start',
  '1':
   { command:
      'git clone --recursive git@github.com:Enfo-ITT/HelloWorld.git . --branch master',
     time: 2018-09-13T13:48:28.125Z,
     plugin: 'github' } }
Thu, 13 Sep 2018 13:48:28 GMT strider-git:worker Git Version:2.14
Thu, 13 Sep 2018 13:48:28 GMT strider-runner-core:job Job "5b9a6aabd4fb2f591695684f" status: stderr [Arguments] { '0': 'stderr', '1':
 'Cloning into \'.\'...\n' }
Thu, 13 Sep 2018 13:48:28 GMT strider-runner-core:job Job "5b9a6aabd4fb2f591695684f" status: stderr [Arguments] { '0': 'stderr', '1':
 'Permission denied (publickey).\r\n' }
Thu, 13 Sep 2018 13:48:28 GMT strider-runner-core:job Job "5b9a6aabd4fb2f591695684f" status: stderr [Arguments] {
  '0': 'stderr',
  '1':
   'fatal: Could not read from remote repository.\n\nPlease make sure you have the correct access rights\nand the repository exists.\
n' }
Thu, 13 Sep 2018 13:48:28 GMT strider-git Gitane error: process exited with status 128
Thu, 13 Sep 2018 13:48:28 GMT strider-git gitane command done git clone --recursive git@github.com:Enfo-ITT/HelloWorld.git . --branch
 master; exit code 128; duration 770
Thu, 13 Sep 2018 13:48:28 GMT strider-runner-core:job Job "5b9a6aabd4fb2f591695684f" status: command.done [Arguments] {
  '0': 'command.done',
  '1':
   { exitCode: 128, time: 2018-09-13T13:48:28.895Z, elapsed: 770 } }
Thu, 13 Sep 2018 13:48:28 GMT strider-runner-core:job Job "5b9a6aabd4fb2f591695684f" status: phase.errored [Arguments] {
  '0': 'phase.errored',
  '1': { time: 2018-09-13T13:48:28.895Z, exitCode: 0 } }
Thu, 13 Sep 2018 13:48:28 GMT strider-runner-core:job Job "5b9a6aabd4fb2f591695684f" errored: Git clone failed with code 500 Error: G
it clone failed with code 500
    at badCode (/usr/lib/node_modules/strider/node_modules/strider-git/worker.js:106:11)
    at updateCache (/usr/lib/node_modules/strider/node_modules/strider-git/worker.js:172:19)
    at /usr/lib/node_modules/strider/node_modules/strider-git/lib/index.js:126:5
    at Function.<anonymous> (/usr/lib/node_modules/strider/node_modules/gitane/index.js:173:7)
    at next (/usr/lib/node_modules/strider/node_modules/gitane/node_modules/step/lib/step.js:51:23)
    at ChildProcess.<anonymous> (/usr/lib/node_modules/strider/node_modules/gitane/index.js:159:9)
    at ChildProcess.emit (events.js:182:13)
    at ChildProcess.EventEmitter.emit (domain.js:460:23)
    at maybeClose (internal/child_process.js:962:16)
    at Process.ChildProcess._handle.onexit (internal/child_process.js:251:5)
Thu, 13 Sep 2018 13:48:28 GMT strider-runner-core:job Job "5b9a6aabd4fb2f591695684f" status: stderr [Arguments] {
  '0': 'stderr',
  '1':
   'An unexpected error occurred while executing this job. Please report at https://github.com/Strider-CD/strider/issues\n\nGit clone
 failed with code 500\n\nError: Git clone failed with code 500\n    at badCode (/usr/lib/node_modules/strider/node_modules/strider-gi
t/worker.js:106:11)\n    at updateCache (/usr/lib/node_modules/strider/node_modules/strider-git/worker.js:172:19)\n    at /usr/lib/no
de_modules/strider/node_modules/strider-git/lib/index.js:126:5\n    at Function.<anonymous> (/usr/lib/node_modules/strider/node_modul
es/gitane/index.js:173:7)\n    at next (/usr/lib/node_modules/strider/node_modules/gitane/node_modules/step/lib/step.js:51:23)\n    a
t ChildProcess.<anonymous> (/usr/lib/node_modules/strider/node_modules/gitane/index.js:159:9)\n    at ChildProcess.emit (events.js:18
2:13)\n    at ChildProcess.EventEmitter.emit (domain.js:460:23)\n    at maybeClose (internal/child_process.js:962:16)\n    at Process
.ChildProcess._handle.onexit (internal/child_process.js:251:5)' }
Thu, 13 Sep 2018 13:48:28 GMT strider-simple-runner [runner:simple-runner] Job done with error. Project: enfo-itt/helloworld Job ID: 
5b9a6aabd4fb2f591695684f
`

**Comment by knownasilya** [comment]
Thanks, I'll try and investigate.

**Comment by nihaopaul** [comment]
Permission denied (publickey).

Is it a local problem?

**Comment by knownasilya** [comment]
The key must be local and in github.

**Comment by enfo-mi** [comment]
I'm not sure which key you are referring to?, so what should I check from the git-hub. The git-plugin works fine when fetching the private repos from the github. So no problems with that. And the OAuth app should be correctly set at github as well. I was just wondering why it uses git username at git clone URI? Shouldn't that be my username at github instead or is this OAuth specific thing?

**Comment by knownasilya** [comment]
The ssh public key is the one I'm refering to. It's created here: https://github.com/<username>/<reponame>/settings/keys

Can you past an example (sensor any private info first) of the URI in question?

**Comment by knownasilya** [comment]
Let me know if you have additional issues.
