### ISSUE TITLE
Error: Cannot find module 'strider-cli'

### ISSUE THREAD

**Issue by nenadb97** [Strider-CD/strider#1069]
I get this error message when I  try to start strider.
My pm2 strider process is restarting every fe seconds.

npm version: 3.10.10
pm2 version: 2.4.6

**Error log**:
 `0|strider  | Error: Cannot find module 'strider-cli'
0|strider  |     at Function.Module._resolveFilename (module.js:469:15)
0|strider  |     at Function.Module._load (module.js:417:25)
0|strider  |     at Function._load (/usr/lib/node_modules/pm2/node_modules/pmx/lib/transaction.js:94:21)
0|strider  |     at Module.require (module.js:497:17)
0|strider  |     at require (internal/module.js:20:19)
0|strider  |     at Object.<anonymous> (/home/adm_walt_vlado/apps/strider/bin/strider:7:33)
0|strider  |     at Module._compile (module.js:570:32)
0|strider  |     at Object.Module._extensions..js (module.js:579:10)
0|strider  |     at Module.load (module.js:487:32)
0|strider  |     at tryModuleLoad (module.js:446:12)
`

**package.json**: [https://gist.github.com/nenadb97/6e26ddc057ead4d892d5c58ae559a3cc](https://gist.github.com/nenadb97/6e26ddc057ead4d892d5c58ae559a3cc)

**Comment by knownasilya** [comment]
Is it located in `node_modules/strider-cli`?

**Comment by nenadb97** [comment]
@knownasilya Yes, it's located inside node_module

**Comment by knownasilya** [comment]
What version of node are you using?

**Comment by harishajdarevic** [comment]
> What version of node are you using?

Hello, I'm @nenadb97 collegue. 

node -v
v6.10.2

Thanks for helping. @knownasilya

**Comment by knownasilya** [comment]
And what command are you using with pm2?

**Comment by knownasilya** [comment]
Did you solve this issue?

**Comment by nenadb97** [comment]
I solved it, but I forgot how. It was year ago.
