### ISSUE TITLE
构建报错后经常卡主，能否增加个重启按钮？

### ISSUE THREAD

**Issue by caizx666** [Strider-CD/strider#1073]
构建时卡主，不显示构建输出信息，也不能被取消，其他构建job也无法执行！

能否增加一个在线重启，要不每次都需要连接服务器重启

---

Translated by Google Translate:

During the build, the card owner does not display the build output information, nor can it be cancelled, and other build jobs cannot be executed!

Is it possible to add an online restart, or you need to restart the server every time

**Comment by knownasilya** [comment]
Are you saying that the server crashes during your build? There is a manual test/deploy button otherwise.

**Comment by saas-plat** [comment]
strider服务没有崩溃，但是构建job报错后，无法在执行其他job，也看不到错误信息
---------------------

The striper service did not crash, but after the build job reported an error, it could not execute other jobs and could not see the error information

**Comment by knownasilya** [comment]
If this is still an issue, please set DEBUG=* env when starting strider server and paste any errors here.
