### ISSUE TITLE
Uncaught Error: [$location:nobase] $location in HTML5 mode requires a <base> tag to be present!

### ISSUE THREAD

**Issue by engagit** [Strider-CD/strider#1075]
I have just done a fresh install on Ubuntu 18, and when I open Strider in my web browser, I get a blank page.  It has the Strider header with a link that says "dashboard" at the top, and has the footer with links to github etc. in the footer, but the main container of the page is completely blank white and empty.

I get the following error in my dev tools in Chrome:
Uncaught Error: [$location:nobase] $location in HTML5 mode requires a <base> tag to be present!

In case the following information helps:
Strider: version 1.11.0
node: v10.18.0
npm: v6.13.4

**Comment by engagit** [comment]
I have figured out more details of what is happening.

After initial installation and going to Strider in my browser, I am not shown a login page.  I think the desired behavior would be to redirect me to the login.

I can choose to add /login to the end of the main URL and then I can login and access Strider as expected.  Everything is working.

However, if I then logout, I am taken back to the blank page I describe above in my original post with the same error in dev tools.

It appears there is a bug in the angular code for the main landing page.

**Comment by knownasilya** [comment]
Thanks for the bug report. I think it has to do with a dependency of angular changing how it works. Will investigate.

**Comment by engagit** [comment]
No problem.  Let me know if you need any more details.

**Comment by engagit** [comment]
Apparently when I add a project, this same error is making most pages blank.  I can add the project, and click to save, but all other pages have the error so I just see a blank white page and no project added.

**Comment by lhardie** [comment]
In case this helps (I am engagit, this is my personal account), here is a link to information about the cause of the error: https://code.angularjs.org/1.7.8/docs/error/$location/nobase

In the previous version of angular that you used in version 1.7 of strider-cd, this was not a hard requirement, according to the information in the link above.

**Comment by engagit** [comment]
Did you experience any problems after making this change?  The only reason I ask is I attempted to make this change in base.html myself, but this then caused all kinds of other problems, such as a template not being found.

**Comment by knownasilya** [comment]
Yeah, saw the same, will investigate further. Feel free to do so as well.

**Comment by engagit** [comment]
I am poking around now and will update if I find anything helpful.

**Comment by knownasilya** [comment]
Try v2.0.1. I reverted the angular upgrade.

**Comment by lhardie** [comment]
This does not appear to fix the issue.  I believe the version of angular has to be older than 1.3, and the code adding "base" in the head of the base.html template needs to be removed.

**Comment by knownasilya** [comment]
Hum, seems to work here. Maybe the built files didn't make it into npm, try `npm run build`

**Comment by engagit** [comment]
That worked, thank you very much!
