### ISSUE TITLE
Dashboard -> View Project -> blank page

### ISSUE THREAD

**Issue by engagit** [Strider-CD/strider#1076]
I have some weird problems with Strider.  This is a fresh installation on Ubuntu 18.  Strider v2.0.1

When I go to my strider website, it loads the expected dashboard page, with a list of projects. If I click on the name of a project I get a blank page with only the strider header and footer.

There is a flash of an error message but it disappears when the blank page loads.  However, I was able to capture it and it says:

```
Uncaught Error: Syntax error, unrecognized expression: #
    at Function.t.error (jquery.js:1560)
    at t.tokenize (jquery.js:2216)
    at t.select (jquery.js:2643)
    at Function.t [as find] (jquery.js:862)
    at Ce.fn.init.find (jquery.js:2896)
    at new Ce.fn.init (jquery.js:3006)
    at Ce (jquery.js:152)
    at i (bootstrap.js:762)
    at HTMLAnchorElement.<anonymous> (bootstrap.js:749)
    at Function.each (jquery.js:367)
```

Even weirder, from the blank page, if I then click the Strider logo in the top menu, the page then loads the project page I had been trying to view in the first place.  This now throws the same error to the console.

Now that it has loaded the project page I originally wanted to view, I cannot use any of the links in the top menu without unexpected results.  Some links just load a blank page again, and others do nothing.

Any ideas, or is there any other information I could provide?

**Comment by knownasilya** [comment]
Give 2.0.5-alpha.0  a try, it's still a wip but will at least give you the latest build

**Comment by knownasilya** [comment]
Give 2.1.0 a try.
