### ISSUE TITLE
After upgrading to 2.0: Failed to load template: build-tpl.html

### ISSUE THREAD

**Issue by manuelbieh** [Strider-CD/strider#1079]
Hey,

is there an upgrade guide somewhere? I've just upgraded my Strider installation from 1.10.0 to 2.0.2 and it (almost) worked fine but when I try to go to a project view, I get an error in the browser console:

> Error: [$compile:tpload] Failed to load template: build-tpl.html (HTTP status: 404 Not Found)

Any idea how what went wrong and how I could fix it?

**Comment by knownasilya** [comment]
The issue is on our end, will attempt to resolve this week. If you want to dig in that would help speed it up.

**Comment by knownasilya** [comment]
Have you tried 2.0.2?

**Comment by astrolope** [comment]
Any update on this? I tried upgrading to 2.02 last night and it still shows the build-tpl error. Everything else works fine but I can't monitor the jobs.

**Comment by knownasilya** [comment]
I wouldn't recommend upgrading yet. I've tried addressing the issue in a few ways and have not been successful yet. I think a client side rewrite, starting from this page is in order.

**Comment by knownasilya** [comment]
Give 2.0.5-alpha.0  a try, it's still a wip but will at least give you the latest build

**Comment by knownasilya** [comment]
Give 2.1.0 a try.
