### ISSUE TITLE
Strider won't install

### ISSUE THREAD

**Issue by MattiusAscentMS** [Strider-CD/strider#1082]
node_modules/connect-mongo/src/types.d.ts:8:23 - error TS2688: Cannot find type definition file for 'express-session'.

8 /// <reference types="express-session" />
                        ~~~~~~~~~~~~~~~

node_modules/connect-mongo/src/types.d.ts:10:26 - error TS7016: Could not find a declaration file for module 'express'. '/home/strider/strider/node_modules/express/index.js' implicitly has an 'any' type.
  Try `npm install @types/express` if it exists or add a new declaration (.d.ts) file containing `declare module 'express';`

10 import * as express from 'express';
                            ~~~~~~~~~

node_modules/connect-mongo/src/types.d.ts:13:26 - error TS7016: Could not find a declaration file for module 'express-session'. '/home/strider/strider/node_modules/express-session/index.js' implicitly has an 'any' type.
  Try `npm install @types/express-session` if it exists or add a new declaration (.d.ts) file containing `declare module 'express-session';`

13 import * as session from 'express-session';
                            ~~~~~~~~~~~~~~~~~

node_modules/connect-mongo/src/types.d.ts:113:58 - error TS2503: Cannot find namespace 'Express'.

113         get: (sid: string, callback: (err: any, session: Express.SessionData | null) => void) => void;
                                                             ~~~~~~~

node_modules/connect-mongo/src/types.d.ts:114:37 - error TS2503: Cannot find namespace 'Express'.

114         set: (sid: string, session: Express.SessionData, callback?: (err: any) => void) => void;
                                        ~~~~~~~

node_modules/connect-mongo/src/types.d.ts:118:39 - error TS2503: Cannot find namespace 'Express'.

118         touch: (sid: string, session: Express.SessionData, callback?: (err: any) => void) => void;

**Comment by knownasilya** [comment]
Thanks for the note. You're installing from master right?

BTW
> I recommend using v1 atm. v2 is broken due to some unknown angular issue. Slowly working on a fix.

**Comment by MattiusAscentMS** [comment]
Yeah, that was from master, I managed to get v2.0.2 working, although it refuses to load my repos from github see #1083 v1 seems to take issue with my version of mongo

**Comment by MattiusAscentMS** [comment]
v1.11.0 also suffers from #1083 for me :( I'd help out with the code if I had capacity to do so! Strider has been so easy to setup in the past and get up and running!

**Comment by knownasilya** [comment]
I'm actively working on replacing the broken part of the angular app, and eventually all of the angular code. Progress is on https://github.com/Strider-CD/strider/tree/feat/octane-start

**Comment by knownasilya** [comment]
Give version 2.0.5-alpha.3 a try. It's still very much a wip.

**Comment by knownasilya** [comment]
Give 2.1.0 a try.
