### ISSUE TITLE
Strider can't access organisational repositories

### ISSUE THREAD

**Issue by MattiusAscentMS** [Strider-CD/strider#1083]
Strider version v2.0.2

Projects pages just displays...

Failed to refresh repositories: Not Found

**Comment by knownasilya** [comment]
I recommend using v1 atm. v2 is broken due to some unknown angular issue. Slowly working on a fix.

**Comment by knownasilya** [comment]
Give 2.0.5-alpha.0  a try, it's still a wip but will at least give you the latest build

**Comment by knownasilya** [comment]
Give 2.1.0 a try.
