### ISSUE TITLE
github pull request status

### ISSUE THREAD

**Issue by jaredly** [Strider-CD/strider#299]
would be good to have

**Comment by Pithikos** [comment]
Hi, I am a bit puzzled on this. What is the current way to run tests on a pull request?

I have installed the Webhooks plugin and setup Github webhooks to fire for PR (from Github's settings tab). Still I am not sure how I am supposed to get this to work? "Github Status" plugin does not appear in Strider's list of plugins that can be installed..

**Comment by knownasilya** [comment]
@Pithikos Thanks for the heads up, i'll add it.

**Comment by knownasilya** [comment]
@Pithikos give it another go, I've added it to the index.

**Comment by Pithikos** [comment]
@knownasilya Oh thanks, it seems to work. Cheers :)
