### ISSUE TITLE
GitHub watching only works if you have a public URL

### ISSUE THREAD

**Issue by flirtester** [Strider-CD/strider#378]
I set up Strider with a machine running on a private subnetwork, with no externally reachable hostname. I could get manual build and tests working. Unfortunately, there was no way to set the webhook at GitHub (there is no way to reach the machine) and there isn't currently a way to have Strider poll GitHub for changes.

Much sadness ensued.

**Comment by Nepoxx** [comment]
[ngrok](https://ngrok.com/) Will do exactly that. 

@jaredly How is polling github different than polling a git repository? A generic git polling plugin might be a good alternative.

**Comment by bitwit** [comment]
I suppose it's worth mentioning here that the strider-scheduler plugin I made does polling:

https://github.com/bitwit/strider-scheduler

We don't currently use this at our workplace, but it works and I'll support an reported issues.

**Comment by knownasilya** [comment]
@bitwit we should add that to the ecosystem-index

**Comment by bitwit** [comment]
@knownasilya Yes, I can do this soon. If it's easier it can be forked into the Strider organization too. I just haven't field tested the plugin thoroughly, or on every git provider yet, for example.

Works like a charm but we never actually started using it at work on an ongoing basis. Like I said, I'm happy to support it though.
