### ISSUE TITLE
Pending jobs change order when they're being processed

### ISSUE THREAD

**Issue by oliversalzburg** [Strider-CD/strider#391]
This is the view on one of our projects while I was pushing 2 commits shortly after each other:

![](http://i.imgur.com/or0wnSj.png)

When the build task finished, suddenly it switched places with the one above it:

![](http://i.imgur.com/cDysEuc.png)

This seems to happen every time in similar situations.

**Comment by knownasilya** [comment]
What kind of sorting would you expect, created date?

**Comment by oliversalzburg** [comment]
@knownasilya Yes, "date created" seems like the most intuitive value
