### ISSUE TITLE
Branch priority not being respected in Dashboard/Project

### ISSUE THREAD

**Issue by andrioid** [Strider-CD/strider#427]
If I click "Test & Deploy" in Dashboard. It completely ignores what I consider to be "default branch" and deploys "master".

If I open the project and click configure, it defaults to my release branch and clicking "deploy" there will deploy the correct branch.

But default "Deploy & Test" button seems to always deploy "master". Which is unfortunate for release branches.
![screen shot 2014-05-06 at 12 06 05](https://cloud.githubusercontent.com/assets/271599/2888393/38323884-d50a-11e3-92d3-75d9c0bdd234.png)
![screen shot 2014-05-06 at 12 07 06](https://cloud.githubusercontent.com/assets/271599/2888392/3831d5b0-d50a-11e3-9e46-eea5869936a5.png)

**Comment by knownasilya** [comment]
This should be fixed as of 2876753e2299c27929dcc14ea00e882679c04200
