### ISSUE TITLE
Strider API Start Job

### ISSUE THREAD

**Issue by adamestela** [Strider-CD/strider#429]
Does strider have an API to start a job without using the UI? Also, is it possible to change variables through an API rather than UI?

Ultimately, what I'm trying to do is set up a cron job to run a test group once per day. I think API calls would be helpful, or if there's an easier way to reach my goal, any help would be much appreciated. 

Thanks!

**Comment by duykhoa** [comment]
I hope Strider can support simple API, includes running test for a project and build status

**Comment by oliversalzburg** [comment]
Probably related to #177

**Comment by knownasilya** [comment]
That would be a nice feature. Seems like we'd need a UI for creating API keys that a tool could consume.

**Comment by oliversalzburg** [comment]
For a quick first patch a random key could be assigned to each user and be displayed in their account page. I'm sure that would already take care of a lot of use cases.

**Comment by knownasilya** [comment]
Agreed. Would just have to setup the passport auth middleware and we should be set.

**Comment by ouadi** [comment]
I positively vote for this feature.

**Comment by oliversalzburg** [comment]
The *easiest* way to trigger a build right now is to just call the provider webhook yourself. Not really an API, but it works.

**Comment by ouadi** [comment]
Thank you @oliversalzburg 

I'm new to **Strider**. I will look at the what can be done using *webhook* and report my finding here.

**Comment by oliversalzburg** [comment]
@ouadi You can `POST` to `http://your.server/account/project/api/provider/webhook`. `provider` would be `gitlab` or `github`. I'm not quite sure about *what* you have to post though.

**Comment by ouadi** [comment]
[Future Studio](https://futurestud.io/) site has nice materials on **Strider**. There, the authors have explained how to [setup git-based project and use 'git-update-hook' to start a build after each commit](https://futurestud.io/blog/strider-how-to-manually-add-git-or-gogs-repository-and-run-tests-automatically/).

The URL they provided (`http://<server>/<repos>/start`) is different from the one you provided.

The data being posted is:
* `branch` to use for the build
* `type`: of build (I guess possible values are `TEST`, `DEPLOY` and `TEST_AND_DEPLOY`).

I have tried **Future Studio** method and it works.

I will give a try to the URL you provided with the same data structure and let you know the outcome.

**Comment by oliversalzburg** [comment]
@ouadi Ah, I didn't even know about that :D Looks pretty solid, and easier than what I had in mind ;).

**Comment by ouadi** [comment]
I have tried the URL you provided with no luck.

I have replaced:
* `account` by my `email` (my Strider user id)
* `project` by the `name` of my project (the value I have put for `namespace/name` in manual setup)
* `provider` by `git`

In your comment, you mentioned `github` and `gitlab` as `provider`s. Does this means that your URL will work only for this two providers?

**Comment by oliversalzburg** [comment]
@ouadi It should work for other providers as well. But I'd go with the example from Future Studio. It looks to be more generic.
