### ISSUE TITLE
Run Selenium Tests without resorting to SauceLabs or similar

### ISSUE THREAD

**Issue by ghost** [Strider-CD/strider#524]
Hi,

Looks like I can start the Selenium Server via custom scripting, but the tests don't seem to be able to fire up an instance of FireFox.  Perhaps I need to install it into the instance somehow.  I'm not even sure if this is possible.

Is it possible?

Regards,

Nick

**Comment by gavinengel** [comment]
@kfatehi Do you have thoughts on automating Selenium IDE HTML tests (easier to  than ruby/java/python) on a Linux server alongside Strider?

The Selenium browser type isn't a big deal to me, meaning I don't care if it's simply WebKit.

I want to include .HTML  Selenium IDE (I might use Firefox to create these) inside a /tests/ directory.  I want Strider to automate these tests in a localhost Selenium daemon on demand.  Sauce Labs isn't necessary for these basic smoke tests.

**Comment by kfatehi** [comment]
@gavinengel Unfortunately I don't. It's been awhile since I've worked in this space, sorry! I'm sure running it in Xvfb will still work, but there are probably better ways to accomplish this sort of thing now (hopefully?).
