### ISSUE TITLE
strider addUser -f causes issues with project creator

### ISSUE THREAD

**Issue by knownasilya** [Strider-CD/strider#584]
Since `strider addUser -f` deletes the old user, and creates a new one, we are left with a `null` for creator of any projects for that user. This is slightly brittle, and maybe we link to email instead of ObjectID? Or we just update the user instead of removing/adding?

cc @jaredly

**Comment by ryanfields** [comment]
I'm not sure why #754 was marked as a duplicate.  I can see where it might be related, but it doesn't describe the same bug.  This issue indicates that `strider addUser -f` will delete a user and then add a new one.  That is not what it currently does.  No removal is taking place in the current version.  It leaves the old user in the DB and creates a duplicate.  That's not quite the same as the orphaning issue described above.

**Comment by knownasilya** [comment]
@ryanfields my mistake, I'll see if I can replicate it. And fix both this and the other.

**Comment by knownasilya** [comment]
Should be fixed with 1.4.7 of strider-cli
