### ISSUE TITLE
Question about SMTP

### ISSUE THREAD

**Issue by sweco-sehrbe** [Strider-CD/strider#590]
How do I configure strider not to use authentication for SMTP?

I always gets this in my log:
_Error sending email: { [AuthError: Invalid login - 502 unimplemented (#5.5.1)]_

**Comment by leutrimhusaj** [comment]
I'm receiving the same Error:
Error sending email: { [Error: Greeting never received] code: 'ETIMEDOUT', errno: 'ETIMEDOUT', stage: 'connect' }

when trying to connect a SMTP server without authentication.
It doesn't matter if i leave SMTP_USER and SMTP_PASS as an empty String or don't even override them.

No Email communication is possible :/

**Comment by leutrimhusaj** [comment]
Issue closed for me now, since switching to strider 1.6.3.
The fix is contained in lib/libconfig.js, last line was 'return defaults;' before and now 'return options;'.

**Comment by knownasilya** [comment]
@leutrimhusaj :+1:

**Comment by DeepzSandra** [comment]
i have the same problem pls dada help me..how can i solve the problem
