### ISSUE TITLE
can't set up new manual project

### ISSUE THREAD

**Issue by swolfekabaminc** [Strider-CD/strider#594]
Tried to setup strider today. Initial installation was ok. Ran into a couple issues trying to create a project:

* for Manual Add, what is the 'Name" field for? No matter what combination of project name and slash / I tried, I couldn't get it to stop marking red.
* Create new button didn't work -- probably because I couldn't get past the Manual Add field.

Moving my repo url to the 'Name' field enabled the Create New button, but resulted in a 'failed to create project' error popup.

Looks like this page needs some work? Cause unfortunately this isn't easy to configure :(

**Comment by mingfang** [comment]
+1
I'm unable to add a github project at all.
Isn't this a basic use case?

**Comment by keyvanfatehi** [comment]
The manual add page has been massively improved. This issue is old. @mingfang make a new issue and let us know your actual errors, etc. +1 isn't very helpful in this case since the original issue is outdated and resolved (the title should have been: Manual Add form is confusing.)

**Comment by keyvanfatehi** [comment]
And yeah it is a basic use case, one that Strider supports really well -- let us know more in a new issue and we can help you.
