### ISSUE TITLE
Strider output: Colors missing

### ISSUE THREAD

**Issue by readme42** [Strider-CD/strider#603]
When Strider executes custom grunt tasks and scripts like jsinspect, colors are not shown correctly. Example from grunt-contrib-jshint with jshint-stylish.

First an example from my terminal, doesnt mind which OS is used, colors are always there:
![image](https://cloud.githubusercontent.com/assets/1941305/4625568/0856caf2-5378-11e4-8ff7-76f2a581c8a8.png)

And now a screenshow from strider. 
![image](https://cloud.githubusercontent.com/assets/1941305/4625605/813ae11a-5378-11e4-93a2-d2f992718286.png)

As you can see, all green/grey/red color definitions from the grunt task call are ignored - but not all - some are shown.

**Comment by knownasilya** [comment]
Is this available in io.js?
