### ISSUE TITLE
mocha tests fail, but strider still "green"

### ISSUE THREAD

**Issue by jorgenskogmo** [Strider-CD/strider#633]
hi,

I have a node.js project with a few simple mocha bdd tests that (deliberately) fail (for now).
They fail badly, and mocha (correctly) prints that to the console.
And so does stride.
But: The build is still marked as "green" (as in "tests completed successfully") - and that cant be right... ideas?

Thanks in advance!

**Comment by ChrisPiechowicz** [comment]
I have the same issue, my script in package.json is: { "test": "mocha --recursive ./src/tests" }
When I run it manually (npm test) and my test fails it returns the correct status (echo $? gives me 1),
but for the same command Strider is always green...
