### ISSUE TITLE
Strider on Heroku: is it possible to run tests for Rails app cloned from Bitbucket/Github?

### ISSUE THREAD

**Issue by movstox** [Strider-CD/strider#644]
Hi all,

I've successfully installed Strider on Heroku. However, when I try to test a Ruby project (2.1.1) I find that Ruby installed on Heroku is too old (1.9.3) and I can't update it due to lack of permissions.

Is there a way to make tests running? Thank you.

**Comment by fny** [comment]
Here's what's needed to get things (nearly) working with Ruby. The only thing that needs to be figured out is #781.

1. Make sure you have the buildpack set to buildpack-multi:  `heroku config:set BUILDPACK_URL=https://github.com/ddollar/heroku-buildpack-multi.git`
2. Add the following to `.buildpacks`:

        https://github.com/mbuchetics/heroku-buildpack-nodejs-grunt#v58
        https://github.com/heroku/heroku-buildpack-ruby.git#v136
        https://github.com/heroku/heroku-buildpack-python.git#v52

3. Create a `Gemfile` with the Ruby version you require listed. The Ruby buildpack apparently won't do squat unless this file is present:

```ruby
# Example Gemfile
source 'https://rubygems.org'
ruby '2.2.1'
```

**Comment by ctoynbee** [comment]
Did anyone resolve this issue completely (including the [https://github.com/Strider-CD/strider/issues/781] issue?
