### ISSUE TITLE
Docker image unusable

### ISSUE THREAD

**Issue by markkimsal** [Strider-CD/strider#647]
After installing the docker image localhost:3000 shows an unstyled page that just says "Running job... Job submitted.."

http://localhost:3000/styles/styles.css redirects to http://localhost:3000/styles/styles.css/ and says "Project not found"

steps to reproduce

```
docker pull niallo/strider
docker run --name strider -d -p 3000:3000 -p 27000:27017 -p 44:22 niallo/strider
```

Version is 1.6.0-pre.2

```
docker exec strider /usr/local/bin/strider -version
1.6.0-pre.2
```

**Comment by leonfs** [comment]
I'm experiencing the same issue in a Azure VM and local (MacOS X with boot2docker), js files and css styles are not available...
