### ISSUE TITLE
Heroku auth redirecting to localhost:3000

### ISSUE THREAD

**Issue by mystery-man** [Strider-CD/strider#677]
After authenticating heroku iam being redirected to localhost. I've set environment variable SERVER_NAME to my app address still iam being redirected to localhost

http://localhost:3000/ext/heroku/oauth/callback?code=60e420f4-1414-436c-a025-25c5609067ef

Am i missing something?

**Comment by tylermauthe** [comment]
For me, this was the solution... I was using OAUTH_ID and OAUTH_SECRET...

`heroku config:add PLUGIN_HEROKU_CLIENT_ID=<CLIENT_ID_FROM_HEROKU> PLUGIN_HEROKU_CLIENT_SECRET=<CLIENT_SECRET_FROM_HEROKU>`
