### ISSUE TITLE
install permission issue (bcrypt) while installing strider

### ISSUE THREAD

**Issue by jordan112** [Strider-CD/strider#693]
I'm trying to install strider on a DO Ubuntu instance.  Fairly vanilla.  I'm running as root user.  I tried to run as sudo as well.

    npm install strider -g

I get this error over and over and it never installs fine

````
gyp WARN EACCES attempting to reinstall using temporary dev dir "/root/npm/lib/node_modules/strider/node_modules/bcrypt/.node-gyp"
gyp WARN EACCES user "root" does not have permission to access the dev dir "/root/npm/lib/node_modules/strider/node_modules/bcrypt/.node-gyp/0.10.34"
````

**Comment by keyvanfatehi** [comment]
Strange. maybe look at https://github.com/TooTallNate/node-gyp/issues/454#issuecomment-69112174

**Comment by jordan112** [comment]
I found that even when i try to install bcrypt alone, same issue, so not an issue with Strider.

    npm install bcrypt -g

I did try the following to see if that works.  Its still running (seems like it could be hung on socket.io install).  It did get past the bcrypt portion.  And yes, i feel dirty using --unsafe-perm

   npm install strider -g --unsafe-perm
