### ISSUE TITLE
npm install fails - bower not found

### ISSUE THREAD

**Issue by rosshettel** [Strider-CD/strider#694]
On OS X 10.10 and npm version 2.2.0, the command `npm install -g strider` fails for me.

Here's the bit where it fails:

````
> strider@1.6.1 postinstall /usr/local/lib/node_modules/strider
> bower install --config.interactive=false --allow-root && npm run build

sh: bower: command not found
npm ERR! Darwin 14.0.0
npm ERR! argv "node" "/usr/local/bin/npm" "install" "-g" "strider"
npm ERR! node v0.10.33
npm ERR! npm  v2.2.0
npm ERR! code ELIFECYCLE

npm ERR! strider@1.6.1 postinstall: `bower install --config.interactive=false --allow-root && npm run build`
npm ERR! Exit status 127
npm ERR!
npm ERR! Failed at the strider@1.6.1 postinstall script 'bower install --config.interactive=false --allow-root && npm run build'.
npm ERR! This is most likely a problem with the strider package,
npm ERR! not with npm itself.
npm ERR! Tell the author that this fails on your system:
npm ERR!     bower install --config.interactive=false --allow-root && npm run build
npm ERR! You can get their info via:
npm ERR!     npm owner ls strider
npm ERR! There is likely additional logging output above.

npm ERR! Please include the following file with any support request:
npm ERR!     /Users/rosshettel/npm-debug.log
````

I don't have bower installed on my system, and I'm sure that would be the easy fix for this, but this sounds like a dependency issue, shouldn't bower be included?

**Comment by knownasilya** [comment]
@rosshettel try cloning master and doing npm install, see if it fails.

**Comment by knownasilya** [comment]
I think we'll be dropping bower as a tool for the enduser to setup the project and will just add the client dependencies and builds.

**Comment by knownasilya** [comment]
@rosshettel can you try doing `npm install Strider-CD/strider -g` and let me know if that works.

**Comment by rosshettel** [comment]
@knownasilya just tried both cloning master and running `npm install` as well as `npm install Strider-CD/strider -g`. Both worked fine, so it does sound like it was just a script path issue when installing globally.

**Comment by knownasilya** [comment]
@rosshettel we'll release a 1.6.2 to address this issue.

**Comment by rosshettel** [comment]
Cool! It's no problem for me to install it other ways for testing purposes, just wanted to give you guys a heads up in case you weren't aware.

**Comment by knownasilya** [comment]
Published
