### ISSUE TITLE
missing module

### ISSUE THREAD

**Issue by gottaloveit** [Strider-CD/strider#696]
for release 1.62 npm installed fine, however, got Error: Cannot find module 'path-to-regexp'

running npm install -g path-to-regexp fixed the issue

**Comment by knownasilya** [comment]
Hum, didn't realize we used that outside of tests. I'll have to move that up to dependencies as well. Thanks for reporting @gottaloveit!

**Comment by knownasilya** [comment]
@gottaloveit for anyone else seeing this, if you set `NODE_ENV=production` you won't see this issue.

**Comment by crokita** [comment]
I have a similar problem with running strider, only instead I get this: "Error: Cannot find module 'mongodb/lib/mongodb/connection/read_preference'". I tried the above "NODE_ENV=production". My database is being hosted elsewhere and I'm using strider locally. Here is my npm-debug.log: http://pastebin.com/3dq0Y6yL

**Comment by knownasilya** [comment]
@crokita looks unrelated, but most likely due to you using node 0.11, which isn't guaranteed to be supported.

**Comment by crokita** [comment]
I missed that for some reason. It works now; thanks.

**Comment by knownasilya** [comment]
Fixed in master.
