### ISSUE TITLE
Can't get any information only for 1 project.

### ISSUE THREAD

**Issue by fernandoneto** [Strider-CD/strider#712]
Hi,

in one of my projects of strider i cant get any information as you can see in image:
![strider](https://cloud.githubusercontent.com/assets/6515784/5979550/8d9c15d2-a8a0-11e4-8df2-28b1a6c6a863.png).

All my other projects are running correct, only this one have this problem.
maybe the problem is with mongodb, some table related with the job/project.

I also updated strider to last version and the problem persist.

**Comment by knownasilya** [comment]
Have you tried deleting the project and adding it back in?

**Comment by fernandoneto** [comment]
@knownasilya 

thank you, among so many hypotheses in my head i don't remenber this one....... :)
