### ISSUE TITLE
Branch priority ordering not giving a correct error if there is no wildcards

### ISSUE THREAD

**Issue by Nepoxx** [Strider-CD/strider#713]
If my understanding is correct, ordering branches in the configuration UI is only useful if we have wildcards. If that is correct, reordering the branches without wildcards gives a meaningless error:

    Error adding branch: required parameter `branches` not found.

**Comment by knownasilya** [comment]
Branches need some work..

They should populate automatically.
Also, I have a branch with no name and can't delete it. Not sure how it got there..

**Comment by mistergaskill** [comment]
I'm getting the same error with a wildcard branch entry. And I'm also getting an API error when trying to add collaborators to a project: ```Error adding collaborator: required parameter `email` not found.```

It looks like the request is getting sent correctly, but the API middleware is incorrectly rejecting the request:

```
Remote Address:54.214.255.17:8100
Request URL:http://ci.mylivelydev.com:8100/livelyme/tryolabs/collaborators/
Request Method:POST
Status Code:400 Bad Request
Request Headersview source
Accept:application/json, text/javascript, */*; q=0.01
Accept-Encoding:gzip, deflate
Accept-Language:en-US,en;q=0.8,en-NZ;q=0.6,en-AU;q=0.4
Connection:keep-alive
Content-Length:151
Content-Type:application/x-www-form-urlencoded; charset=UTF-8
Cookie:_ga=GA1.2.460204139.1422906642; connect.sid=s%3A2V6tNVLC4dzs8U3ujuf9lGtZybuhMb5A.C561lzHDDp7e0%2FryZOoeUU7tSdEP612vSXrXHiA7E2E
Host:ci.mylivelydev.com:8100
Origin:http://ci.mylivelydev.com:8100
Referer:http://ci.mylivelydev.com:8100/livelyme/tryolabs/config/tab-project
User-Agent:Mozilla/5.0 (Macintosh; Intel Mac OS X 10_10_1) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/40.0.2214.94 Safari/537.36
X-Requested-With:XMLHttpRequest
Form Dataview sourceview URL encoded
email:joshua@mylively.com
access:2
gravatar:https://secure.gravatar.com/avatar/1d044d80754a191ea50109c7a8f73bc3?d=identicon
owner:false
Response Headersview source
Connection:keep-alive
Date:Thu, 05 Feb 2015 21:47:12 GMT
Transfer-Encoding:chunked
Vary:X-HTTP-Method-Override
X-Powered-By:Express
```

Could this be something the form data not populating req.params?

**Comment by mistergaskill** [comment]
I figured out the bug. express' req.param function looked at req.params, req.body, and req.query http://expressjs.com/api.html#req.param - So just checking req.params is only a subset of the previous functionality. Since these settings are submitted as form data, the fields are stored in req.body - so at least for this endpoint (and the collaborator's one I mentioned) we should be checking req.body instead of req.params.

I'm not sure if this solution will work for other endpoints but right now this is completely broken.

**Comment by knownasilya** [comment]
@mistergaskill I'm not available to submit a fix atm, but would totally take a PR.

**Comment by mistergaskill** [comment]
So this issue should be fixed by https://github.com/Strider-CD/strider/pull/723 and the issue I reported (which should have been filed as a different issue as they have different causes) should be fixed by https://github.com/Strider-CD/strider/pull/725

**Comment by knownasilya** [comment]
1.6.4 has this issue fixed
