### ISSUE TITLE
security issue in strider-status-report plugin

### ISSUE THREAD

**Issue by fernandoneto** [Strider-CD/strider#715]
If i try to acess to plugin URL for example  localhost:3000/ext/status-report/jobs i can get the status of all projects that i run in strider.
the problem is that I have private projects and if i GET the url it shows all jobs status.
I think the correct is acess all project status if we are logedd. if you were not you only can acess to public project.

@keyvanfatehi

**Comment by keyvanfatehi** [comment]
@fernandoneto good catch, I enabled the issue tracker there and created an issue https://github.com/Strider-CD/strider-status-report/issues/3

**Comment by fernandoneto** [comment]
ok thanks :)
