### ISSUE TITLE
When running on Heroku free plan, Plugins revert to original version after resuming from idle 

### ISSUE THREAD

**Issue by robotiko** [Strider-CD/strider#718]
Under free plan, dyno gets idle and  the instance goes to sleep. 
When dyno awakes, the plugins get back to old  versions, loosing all updates. 

It seems that plugins must been saved in heroku ephemeral space  (https://devcenter.heroku.com/articles/dynos#ephemeral-filesystem). 
There are ways to prevent dynos from going to sleep if there is no other solution for plugin updates.

**Comment by knownasilya** [comment]
@robotiko yeah, most of the plugins are on npm, but are not updated, since most of the contributors don't have publishing permissions for the plugins on npm. 

This looks like a task for @niallo.

**Comment by brugnara** [comment]
+1

**Comment by knownasilya** [comment]
@niallo would love more access to the plugins on npm.

**Comment by niallo** [comment]
If you can give me a list of npm packages I'll grant you as owner.

On Tue, May 5, 2015 at 7:41 AM, Ilya Radchenko <notifications@github.com>
wrote:

> @niallo <https://github.com/niallo> would love more access to the plugins
> on npm.
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/Strider-CD/strider/issues/718#issuecomment-99100025>.
>



-- 
Niall O'Higgins
W: http://niallohiggins.com
E: n@niallo.me
T: @niallohiggins

**Comment by knownasilya** [comment]
@niallo it would be nice to take advantage of scoped packages, since those are a thing now. Maybe have a strider accounts.

**Comment by niallo** [comment]
Sounds good. For now, can you send me a list of NPM packages which you need
access to and I can add you as owner?

On Tue, May 5, 2015 at 9:32 AM, Ilya Radchenko <notifications@github.com>
wrote:

> @niallo <https://github.com/niallo> it would be nice to take advantage of
> scoped packages, since those are a thing now. Maybe have a strider accounts.
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/Strider-CD/strider/issues/718#issuecomment-99133416>.
>



-- 
Niall O'Higgins
W: http://niallohiggins.com
E: n@niallo.me
T: @niallohiggins

**Comment by knownasilya** [comment]
strider-bitbucket
strider-build-badge
strider-custom
strider-email-notifier
strider-env
strider-extension-loader
strider-git
strider-github
strider-gitlab
strider-heroku
strider-mailer
strider-metadata
strider-node
strider-python
strider-ruby
strider-simple-runner
strider-slack
strider-ssh-deploy

**Comment by niallo** [comment]
Ok, I added all those I could. Some of these I wasn't able to update since
@keyvan or someone else is the owner:

strider-ssh-deploy
strider-slack
strider-gitlab
strider-email-notifier
strider-build-badge

On Tue, May 5, 2015 at 9:58 AM, Ilya Radchenko <notifications@github.com>
wrote:

> strider-bitbucket
> strider-build-badge
> strider-custom
> strider-email-notifier
> strider-env
> strider-extension-loader
> strider-git
> strider-github
> strider-gitlab
> strider-heroku
> strider-mailer
> strider-metadata
> strider-node
> strider-python
> strider-ruby
> strider-simple-runner
> strider-slack
> strider-ssh-deploy
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/Strider-CD/strider/issues/718#issuecomment-99141048>.
>



-- 
Niall O'Higgins
W: http://niallohiggins.com
E: n@niallo.me
T: @niallohiggins

**Comment by knownasilya** [comment]
Thanks @niallo

**Comment by knownasilya** [comment]
@niallo I forgot we had https://github.com/Strider-CD/npm-outdated
