### ISSUE TITLE
Weird branch checkout

### ISSUE THREAD

**Issue by oliversalzburg** [Strider-CD/strider#729]
While deploying a project, I noticed the following in the log:

![](http://i.imgur.com/Zlhn3Nf.png)

I would expect `master` to be checked out of git, but it shows a hash instead. I was wondering if the username is leaking into the log here.

**Comment by knownasilya** [comment]
@oliversalzburg is that the sha of the commit at HEAD?

**Comment by oliversalzburg** [comment]
@knownasilya Oh! Maybe I never realized it before, but I expected that it would check out `dev` or `master` or whatever the branch is named.

**Comment by knownasilya** [comment]
I'm not sure behind the reasoning, but maybe @jaredly or someone else in @Strider-CD/owners knows why it's done this way.

**Comment by knownasilya** [comment]
Seems like if the build is initiated via a commit, you'd get the sha, but if you do it manually, you'd see the branch name.

**Comment by oliversalzburg** [comment]
Ah, cool, that explains it. Because I was working on another issue recently, I did a lot of manual deployments and probably didn't remember the other behavior.

Thanks for taking the time to look into it.
