### ISSUE TITLE
new Plugin route not found

### ISSUE THREAD

**Issue by mabc224** [Strider-CD/strider#730]
Hi guys,

I am writing a custom plugin. I use this as base template.  [https://github.com/bitwit/strider-template](https://github.com/bitwit/strider-template)
 In config/config.js, i register this route on button click.
```javascript
	$scope.getProject = function () {
		$http.get('/ext/konsow/jobs')
		.success(function(result) {
			console.log(result);
		}).error(function(err) {
			console.log(err);
		});
```
in webapp.js
```javascript
globalRoutes: function (app, context) {
    app.get('/jobs', function(req, res){
        var options = {
            uri : 'http://localhost:4000/api/system/info',
            method : 'GET',
            headers: {
                "Accept": "application/json",
                "Content-Type": "application/json"
            }
        };
var rp = require("request-promise");
        rp(options)
            .then(function (response) {
                res.send(response);
            })
            .catch(function (response) {
                res.send(response);
            });
    });
}
```

strider.json
```javascript
  "strider": {
    "type": "job",
    "id": "konsow",
    "title": "My Plugin Template",
    "worker": "worker.js",
    "webapp": "webapp.js",
    "icon": "icon.png",
    "config": {
      "controller": "MyTemplateCtrl"
    }
  }
```

when i try to access this path from plugin gui on button click, it says, 
GET http://localhost:3000/ext/konsow/jobs 404 Not Found

I have double check controller name in config.js file and plugin id. No thing is wrong. 
kindly tell me where i am wrong.

**Label**: *Question*

**Comment by knownasilya** [comment]
@mabc224 do you have your plugin up on github, for testing?

**Comment by mabc224** [comment]
@knownasilya Here it is repo [https://github.com/mabc224/strider-plugin](https://github.com/mabc224/strider-plugin)

**Comment by mabc224** [comment]
Any one who have command on plugin writing, kindly check it and respond back

**Comment by knownasilya** [comment]
@mabc224 I'll try to have a look on monday.

**Comment by mabc224** [comment]
@knownasilya Did you check it?

**Comment by knownasilya** [comment]
@mabc224 yes, it's the order that the global routes are loaded, since there is a route of `/:org/:repo/jobs`,
this one gets intercepted by that route. This is due to the upgrade to express4, and will be solved in the next patch.

The workaround is to rename `jobs` to a route not taken already.

**Comment by knownasilya** [comment]
@mabc224 does that help?

**Comment by mabc224** [comment]
@knownasilya yes. it works
