### ISSUE TITLE
Can not install globally on debian 7 (1.6.3, 1.6.4)

### ISSUE THREAD

**Issue by m00t** [Strider-CD/strider#732]
Can not install by `npm install -g strider` (npm tries to install version 1.6.3). Can not install by `git checkout v1.6.3 && npm install -g`. Also can not install by `git checkout v1.6.4 && npm install -g`. `npm install` works fine on both v1.6.3 and v1.6.4 tags.

npm-debug.log from installation: https://gist.github.com/m00t/e66c9502b77884adb872

P.S.
Output from npm install -g: https://gist.github.com/m00t/28009a17abc03226fd73

P.P.S.
For those who will google this issue by error message:
```
System info:
Bower version: 1.3.12
Node version: 0.10.29
OS: Linux 3.2.0-4-amd64 x64
npm ERR! Linux 3.2.0-4-amd64
npm ERR! argv "node" "/usr/bin/npm" "install" "-g"
npm ERR! node v0.10.29
npm ERR! npm  v2.5.0
npm ERR! code ELIFECYCLE

npm ERR! strider@1.6.4 postinstall: `bower install --allow-root && npm run build`
npm ERR! Exit status 1
npm ERR! 
npm ERR! Failed at the strider@1.6.4 postinstall script 'bower install --allow-root && npm run build'.
npm ERR! This is most likely a problem with the strider package,
npm ERR! not with npm itself.
npm ERR! Tell the author that this fails on your system:
npm ERR!     bower install --allow-root && npm run build
npm ERR! You can get their info via:
npm ERR!     npm owner ls strider
npm ERR! There is likely additional logging output above.

npm ERR! Please include the following file with any support request:
npm ERR!     /root/strider/npm-debug.log
```

**Comment by knownasilya** [comment]
I think this has to do with the `less` dependency, since it doesn't install properly with the -g option when in dependencies.

**Comment by m00t** [comment]
How I can get output from `bower install --allow-root && npm run build`? Is there some sort of flags to keep `node_modules/strider` folder after `npm install -g` fail?

**Comment by m00t** [comment]
Things became even more strange after I run `npm install -g less`. Now `npm install -g strider` (or `npm install -g` within strider checkout directory) silently fails without any error and logs:

```
root@ci:/usr/lib# npm install -g strider
npm WARN deprecated swig@0.14.0: v1.0.0 is a complete rewrite of Swig from the ground up. Previous versions are no longer supported
npm WARN engine npm@1.3.26: wanted: {"node":">=0.6","npm":"1"} (current: {"node":"0.10.29","npm":"2.5.0"})
npm WARN optional dep failed, continuing fsevents@0.3.0
 
> bcrypt@0.8.1 install /usr/lib/node_modules/strider/node_modules/bcrypt
> node-gyp rebuild

gyp WARN EACCES user "root" does not have permission to access the dev dir "/root/.node-gyp/0.10.29"
gyp WARN EACCES attempting to reinstall using temporary dev dir "/usr/lib/node_modules/strider/node_modules/bcrypt/.node-gyp"
Killed
root@ci:/usr/lib# make: Entering directory `/usr/lib/node_modules/strider/node_modules/bcrypt/build'
  CXX(target) Release/obj.target/bcrypt_lib/src/blowfish.o
  CXX(target) Release/obj.target/bcrypt_lib/src/bcrypt.o
  CXX(target) Release/obj.target/bcrypt_lib/src/bcrypt_node.o
  SOLINK_MODULE(target) Release/obj.target/bcrypt_lib.node
  SOLINK_MODULE(target) Release/obj.target/bcrypt_lib.node: Finished
  COPY Release/bcrypt_lib.node
make: Leaving directory `/usr/lib/node_modules/strider/node_modules/bcrypt/build'

root@ci:/usr/lib# 
```

**Comment by knownasilya** [comment]
@m00t did you see the note about global installs [here](https://github.com/Strider-CD/strider#running-on-infrastructure)?

**Comment by m00t** [comment]
@knownasilya nope, I used this manual: http://strider.readthedocs.org/en/latest/install.html
I will try it later, thanks.

**Comment by knownasilya** [comment]
@m00t were you successful?

**Comment by m00t** [comment]
@knownasilya Sorry, did not have time for testing yet.

**Comment by m00t** [comment]
Tried this. Got unlimited
```
gyp WARN EACCES attempting to reinstall using temporary dev dir "/root/npm/lib/node_modules/strider/node_modules/bcrypt/.node-gyp"
gyp WARN EACCES user "root" does not have permission to access the dev dir "/root/npm/lib/node_modules/strider/node_modules/bcrypt/.node-gyp/0.10.29"
gyp WARN EACCES attempting to reinstall using temporary dev dir "/root/npm/lib/node_modules/strider/node_modules/bcrypt/.node-gyp"
gyp WARN EACCES user "root" does not have permission to access the dev dir "/root/npm/lib/node_modules/strider/node_modules/bcrypt/.node-gyp/0.10.29"
gyp WARN EACCES attempting to reinstall using temporary dev dir "/root/npm/lib/node_modules/strider/node_modules/bcrypt/.node-gyp"
gyp WARN EACCES user "root" does not have permission to access the dev dir "/root/npm/lib/node_modules/strider/node_modules/bcrypt/.node-gyp/0.10.29"
gyp WARN EACCES attempting to reinstall using temporary dev dir "/root/npm/lib/node_modules/strider/node_modules/bcrypt/.node-gyp"
gyp WARN EACCES user "root" does not have permission to access the dev dir "/root/npm/lib/node_modules/strider/node_modules/bcrypt/.node-gyp/0.10.29"
gyp WARN EACCES attempting to reinstall using temporary dev dir "/root/npm/lib/node_modules/strider/node_modules/bcrypt/.node-gyp"
gyp WARN EACCES user "root" does not have permission to access the dev dir "/root/npm/lib/node_modules/strider/node_modules/bcrypt/.node-gyp/0.10.29"
gyp WARN EACCES attempting to reinstall using temporary dev dir "/root/npm/lib/node_modules/strider/node_modules/bcrypt/.node-gyp"
gyp WARN EACCES user "root" does not have permission to access the dev dir "/root/npm/lib/node_modules/strider/node_modules/bcrypt/.node-gyp/0.10.29"
gyp WARN EACCES attempting to reinstall using temporary dev dir "/root/npm/lib/node_modules/strider/node_modules/bcrypt/.node-gyp"
gyp WARN EACCES user "root" does not have permission to access the dev dir "/root/npm/lib/node_modules/strider/node_modules/bcrypt/.node-gyp/0.10.29"
gyp WARN EACCES attempting to reinstall using temporary dev dir "/root/npm/lib/node_modules/strider/node_modules/bcrypt/.node-gyp"
gyp WARN EACCES user "root" does not have permission to access the dev dir "/root/npm/lib/node_modules/strider/node_modules/bcrypt/.node-gyp/0.10.29"
```

**Comment by knownasilya** [comment]
@m00t so if you follow that note about installing global modules, you shouldn't be using sudo.

If this isn't working, just clone the repo and do `npm install` inside.

**Comment by m00t** [comment]
@knownasilya what note should I follow to not using `sudo`? I use `npm install -g strider` without sudo, but other commands like `npm config` etc was ran with sudo because I forgot to remove sudo: yes from my ansible playbook. Can it be the case?

`npm install` inside repo works.

**Comment by knownasilya** [comment]
The one [here](https://github.com/Strider-CD/strider#running-on-infrastructure) under the `npm install`

**Comment by m00t** [comment]
@knownasilya This note says nothing about sudo. Also I followed it completely. Tried to install everything from scratch without sudo, no luck.

**Comment by m00t** [comment]
@knownasilya  Ow, I see. I should not install modules for root too?

**Comment by knownasilya** [comment]
You should never use sudo for npm modules global or local.

**Comment by m00t** [comment]
@knownasilya works fine when I do not try to install strider as root. I think this should be pointed clearly, because it is not obvious that `~` should not actually be `/root`

**Comment by chrisfosterelli** [comment]
Also running into this problem. @knownasilya do you have any resources for not using sudo to install global modules? AFAIK this is common practice...

**Comment by chrisfosterelli** [comment]
In fact, it looks like the [official stance](https://github.com/npm/npm/issues/3139#issuecomment-13358582) is that packages should work while being installed with `sudo` or else they are considered broken.

**Comment by knownasilya** [comment]
@chrisfosterelli run (as normal user) `npm config set prefix ~/npm` to set your global modules directory to '~/npm'. You will also have to add ~/npm/bin to your PATH environment variable. Also installing node with `n` or `nvm` is recommended, especially since ubuntu botches that install so often.

On the other end, node-gyp is a special case since it compiles the systems native c++ libraries to build certain modules, and if that doesn't work with `sudo`, it should be brought to their attention. I've not had any issues with it working with sudo, when I've tried.

**Comment by chrisfosterelli** [comment]
@knownasilya I understand the process to reconfiguring that, I was wondering if you had any resources stating that you should not install modules globally when you said "You should never use sudo for npm modules global or local", which doesn't seem to be the official stance. I'd like to install my global modules _globally_, and I'm sure lots of other users would too.

At any rate, this is certainly a bug and saying "don't install Strider the standard, accepted way" isn't a fix.

It appears that npm scripts are ran as the user `nobody`, could it be that bower is trying to access the error directory (`/home/cfoster/.cache/bower/registry/bower.herokuapp.com/lookup` in my case) and the user `nobody` wouldn't have access?

**Comment by chrisfosterelli** [comment]
The permission error appears to be what's happening, because if I add a `whoami` to the `postinstall` script then I get `nobody` as the result. As a temporary workaround, you can create a world-writeable directory that `nobody` can write to and use that as `HOME`.

```
mkdir /tmp/testhome ; chmod 777 /tmp/testhome ; HOME=/tmp/testhome sudo npm install -g strider ; rm -r /tmp/testhome
```

That works for me on Ubuntu with Strider@1.6.4, but isn't exactly a fix. 

I guess this issue is that bower is trying to use the `HOME` variable to access it's cache, but the user `nobody` wouldn't have access to that directory. Strider could get around this by assigning `HOME` to a temporary dir as part of the `postinstall` script, but I've also created bower/bower#1715 to see what they think of building this into bower, since what `node-gyp` does if I understand right is create it's _own_ temporary build directory if it can't access the one it needs to for whatever reason.

Also open to better suggestions :)

**Comment by knownasilya** [comment]
Yeah not sure, probably not using bower, or having a script for pulling out the used files from the dependencies and committing those.

**Comment by mihaly-alberti-kurtosys** [comment]
If you're on ubuntu, you may have to install `nodejs-legacy`

Read more: http://stackoverflow.com/a/21171188

This was the solution for me.

**Comment by ksgy** [comment]
If you're trying to install on an Ubuntu machine, you may have to install `nodejs-legacy` package.

Read more here: http://stackoverflow.com/a/21171188

This was the solution for me.

**Comment by knownasilya** [comment]
@ksgy thank you for the input!

**Comment by chrisfosterelli** [comment]
@ksgy I think that may be a separate issue, I'm using the PPA which provides `/usr/bin/node`. If it's working to globally install Strider, that may because the debain package is a much older version of node that doesn't run scripts as `nobody` (just a guess, though). Can you clarify your node version?

**Comment by ksgy** [comment]
@chrisfosterelli 
My node version is: v0.10.25 on Ubuntu 14.04.2 LTS

**Comment by fernandoneto** [comment]
like @ksgy im using nodejs-legacy v 0.10.25 on Ubuntu machine and have no problems installig globally

**Comment by knownasilya** [comment]
Closing this, since we no longer tell you to use `-g` to install strider. Feel free to continue discussion. If there are any other specific issues feel free to create a new issue.

**Comment by bmustata** [comment]
Only worked after I installed strider like a node.js app without -g flag.
