### ISSUE TITLE
How can I install third party plugins?

### ISSUE THREAD

**Issue by Jinkwon** [Strider-CD/strider#734]
Hi, Strider.
I wanna install third-party plugin such as https://github.com/bitwit/strider-scheduler.
Can you give me some advice?
I'm using on strider stable version with npm install -g strider.

**Comment by knownasilya** [comment]
Since that plugin is not in the [registry](https://github.com/Strider-CD/ecosystem-index/blob/master/plugins.yml), you will need to install it with `npm install --save strider-scheduler`.

For plugins that are in the registry, go to the "Admin > Plugins" from within Strider and install from there.

**Comment by Jinkwon** [comment]
@knownasilya 
I solved this problem.
Thanks.
