### ISSUE TITLE
Corporate Proxy Support

### ISSUE THREAD

**Issue by kauegimenes** [Strider-CD/strider#738]
Hello, its possible to include a option to set a corporate proxy?

I am unable to connect with bitbucket because of this.

``````````````````````````````````
error: failed to obtain request token (Error: connect ETIMEDOUT)
    at /strider/node_modules/strider-bitbucket/node_modules/passport-bitbucket/node_modules/passport-oauth/lib/passport-oauth/strategies/oauth.js:196:36
    at /strider/node_modules/strider-bitbucket/node_modules/oauth/lib/oauth.js:543:17
    at ClientRequest.<anonymous> (/strider/node_modules/strider-bitbucket/node_modules/oauth/lib/oauth.js:421:9)
    at ClientRequest.emit (events.js:95:17)
    at CleartextStream.socketErrorListener (http.js:1547:9)
    at CleartextStream.emit (events.js:95:17)
    at Socket.onerror (tls.js:1440:17)
    at Socket.emit (events.js:117:20)
    at net.js:440:14
    at process._tickCallback (node.js:419:13)
GET /ext/bitbucket/oauth - - ms - -
``````````````````````````````

Thanks.

**Comment by kauegimenes** [comment]
I have the same problem with the page /admin/plugins 
``````````````````````````````````
Connect
500 Error: socket hang up
   at createHangUpError (http.js:1472:15)
   at CleartextStream.socketCloseListener (http.js:1522:23)
   at CleartextStream.emit (events.js:117:20)
   at tls.js:691:10
   at process._tickDomainCallback (node.js:463:13)
``````````````````````````````````

**Comment by knownasilya** [comment]
Probably worth implementing with https://github.com/nodejitsu/node-http-proxy

**Comment by knownasilya** [comment]
@kauegimenes would there be an http and https url, or just a base url without the http/https prefixes?

**Comment by kauegimenes** [comment]
I was thinking about using https://www.npmjs.com/package/global-tunnel
The proxy setting is the same for http & https.

**Comment by kauegimenes** [comment]
@knownasilya Just tested global-tunnel and everything works just fine.

The only modification was to include this code in the main.js file:
var globalTunnel = require('global-tunnel');
globalTunnel.initialize({
  host: '10.0.0.10',
  port: 8080
});

**Comment by knownasilya** [comment]
@kauegimenes feel free to submit a PR, which should enable the tunnel if `PROXY_HOST` env is set, otherwise I'll get to it when I have time.

**Comment by kauegimenes** [comment]
@knownasilya I think the correct env variable to use is HTTP_PROXY and HTTPS_PROXY right?

**Comment by knownasilya** [comment]
@kauegimenes those are the envs for npm, if global tunnel uses those, then yes.

**Comment by knownasilya** [comment]
Looks like just `http_proxy` is [honored](https://www.npmjs.com/package/global-tunnel#auto-config)

**Comment by kauegimenes** [comment]
@knownasilya Great, i will submit a PR when i have some time avaliable!

Thanks!

**Comment by kauegimenes** [comment]
@knownasilya Just created a PR https://github.com/Strider-CD/strider/pull/741 
If you need any changes let me know.

**Comment by knownasilya** [comment]
In master, will be shipped in 1.7.0

**Comment by onlymee** [comment]
Nice fix but ... global-tunnel doesn't appear to support authentication? eg: http_proxy=http://user:pass@myproxy:port

**Comment by knownasilya** [comment]
@onlymee feel free to submit a feature request to global-tunnel :+1:
