### ISSUE TITLE
Mongo user and password config 

### ISSUE THREAD

**Issue by alivxlive** [Strider-CD/strider#739]
in which file can I edit or add mongodb port and host, user name and password. and the database name

**Comment by knownasilya** [comment]
Use the `DB_URI` environment variable. This is the [format](http://docs.mongodb.org/manual/reference/connection-string/).

**Comment by alivxlive** [comment]
mm, I did not get your point,
I want to change the setting in the strider-cd config file.

**Comment by knownasilya** [comment]
The config file would be `.striderrc` and it's JSON and it would be `{ "db_uri": "yoururihere" }`

**Comment by knownasilya** [comment]
@alivxlive did you get it working?

**Comment by knownasilya** [comment]
If you still need help, feel free to ask any questions here, or create more specific issues.

**Comment by alivxlive** [comment]
sorry,  that did not works :(

**Comment by knownasilya** [comment]
@alivxlive I just tried it, and it works fine. My `.striderrc` looks like this:

```json
{
  "db_uri": "hi"
}
```

**Comment by alivxlive** [comment]
Thank you Alot :) @knownasilya
