### ISSUE TITLE
Project not deploying after POST on /start/

### ISSUE THREAD

**Issue by kauegimenes** [Strider-CD/strider#740]
Hello, 

I have set the option Deploy on Green but nothing happens after the test.

I already have a Runner with my custom scripts setup.

I am missing something?

Thanks.

**Comment by knownasilya** [comment]
How are you triggering the test (exact command please - minus sensitive data)?

**Comment by kauegimenes** [comment]
@knownasilya This is the first project i am trying to implement with strider, for now the project dont have any tests. 

My Node plugin is test command is: No test command.

If i click the test & deploy button everything works.

**Comment by kauegimenes** [comment]
@knownasilya After i tried to create the hook with bitbucket i was able to see the POST request in the server log, but strider is not even running the tests.

POST /cnova/seo-monitor/start/ 302 3.360 ms - 40

But if i simulate the POST the system is able to test the project but without deploying it

**Comment by knownasilya** [comment]
@kauegimenes see https://github.com/Strider-CD/strider-cli#runtest

**Comment by kauegimenes** [comment]
@knownasilya The output is "Login error"
I double checked my email and changed my password twice, still not able to runTests using this command.

**Comment by kauegimenes** [comment]
@knownasilya Also, about the Bitbucket implementation i was able to debug the request and looks like Stride is redirecting the POST to the login page.

**Comment by kauegimenes** [comment]
[strider]$ bin/strider addUser -l striderTestingRandom21341@testing.com -p 2jkd93j49fkjddo239 -a true
Connecting to MongoDB URL: mongodb://localhost/strider-foss
User added successfully! Enjoy.
[strider]$ bin/strider runTest -l striderTestingRandom21341@testing.com -p 2jkd93j49fkjddo239  -j proj/testing
Login error

**Comment by knownasilya** [comment]
@kauegimenes try installing strider-cli from master branch, I just added a console log for the error.

**Comment by knownasilya** [comment]
`npm install Strider-CD/strider-cli` should do it

**Comment by kauegimenes** [comment]
i just executed `npm install strider-cli` in the root folder of strider:
````````````````````````
strider-cli@1.4.3 node_modules/strider-cli
````````````````````````
But i am still not able to use the command runTest:
````````````````````````
Login error
````````````````````````

**Comment by knownasilya** [comment]
I didn't publish to npm, so you have to use the command above..

**Comment by kauegimenes** [comment]
@knownasilya  I was able to make the command runTest work, the problem only happens when i am running strider on a different port, i run without the `PORT` env i got the message `Job started`

**Comment by kauegimenes** [comment]
@knownasilya Also the only difference is that https://github.com/Strider-CD/strider-cli/blob/005b6eb3ae55d6bfce15aebf4794297912d16bb8/run.js posts the ` postData.type = 'TEST_AND_DEPLOY';` I already tested with this data in the POST and works fine.

**Comment by knownasilya** [comment]
@kauegimenes if you could still pull down the master version so that we can know what the error was so we can track it down.

**Comment by knownasilya** [comment]
You must have setup your provider with a different port, and then changed it after, so that the provider has the wrong port for the post hook?

**Comment by kauegimenes** [comment]
@knownasilya No, i aways used the same port since i started using strider.

**Comment by kauegimenes** [comment]
@knownasilya Just updated the strider-cli to the master version, thats the output: 
````````````````````````````
/strider/node_modules/strider-cli/run.js:57
        console.error('Login error', error, res);
                                     ^
ReferenceError: error is not defined
    at /strider/node_modules/strider-cli/run.js:57:38
    at Request.callback (/strider/node_modules/strider-cli/node_modules/superagent/lib/node/index.js:746:30)
    at ClientRequest.<anonymous> (/strider/node_modules/strider-cli/node_modules/superagent/lib/node/index.js:711:10)
    at ClientRequest.emit (events.js:95:17)
    at Socket.socketErrorListener (http.js:1547:9)
    at Socket.emit (events.js:95:17)
    at net.js:440:14
    at process._tickCallback (node.js:419:13)
``````````````````````````````````

**Comment by knownasilya** [comment]
Try again, I made a typo.

**Comment by kauegimenes** [comment]
Here:
``````````````````````
Login error { [Error: connect ECONNREFUSED]
  code: 'ECONNREFUSED',
  errno: 'ECONNREFUSED',
  syscall: 'connect' } undefined
``````````````````````

If you need help with the debug feel free to add me on skype (kaue@dot.net)

**Comment by knownasilya** [comment]
Ok, sounds like my suspicions were right between mismatch of ports in the provider and what you were trying.

**Comment by kauegimenes** [comment]
@knownasilya Hmm ok, whats the solution?

**Comment by knownasilya** [comment]
@kauegimenes don't change the port after you've used one. Otherwise you can delete the hooks in your provider (github, bitbucket, ..) and set them up again with the new port.

**Comment by kauegimenes** [comment]
@knownasilya I am not linking the account to integrate with bitbucket, i created the hook, you guys have any documentation on how i should create the hook? the url should just be /start/? There is no need for any auth?

Thanks.

**Comment by knownasilya** [comment]
You'd have to recreate your project in Strider. So delete it first, and then re-add it via the projects page.

**Comment by kauegimenes** [comment]
@knownasilya I never changed the port on strider, maybe its because i am using the env in the command ? `PORT=8888 npm start`

**Comment by knownasilya** [comment]
That should work. So you used `PORT` right from the beginning and every time since then?

**Comment by kauegimenes** [comment]
@knownasilya Yes, in my current implementation its impossible to open strider dashboard if its in another port.

Can you help me find where the bug is located?

**Comment by kauegimenes** [comment]
@knownasilya I really want to make Strider work.

**Comment by knownasilya** [comment]
@kauegimenes for a quick fix, I'd leave the default port, and just proxy with your server, e.g. nginx.

**Comment by knownasilya** [comment]
@kauegimenes the solution is to use `PORT` with the `runTest`, e.g.

```no-highlight
PORT=8000 bin/strider runTest -l TestingRandom21341@testing.com -p 2jkd93j49fkjddo239  -j proj/testing
```
