### ISSUE TITLE
Error running test on bitbucket repo (spawn git ENOENT)

### ISSUE THREAD

**Issue by shaymarketing** [Strider-CD/strider#742]
I am getting the following error trying to run a test on a new project. Any idea on how to resolve this?
Thanks.

 spawn git ENOENT
 environment
// Config merged from strider.json
 prepare -1
$ git clone --recursive git@bitbucket.com:myrepo/repotest1 . -b br2015-02-27 bitbucket  -1
An unexpected error occurred while executing this job. Please report at https://github.com/Strider-CD/strider/issues

spawn git ENOENT

Error: spawn git ENOENT
    at exports._errnoException (util.js:746:11)
    at Process.ChildProcess._handle.onexit (child_process.js:1046:32)
    at child_process.js:1137:20
    at process._tickDomainCallback (node.js:381:11)

**Comment by knownasilya** [comment]
@shaymarketing sounds like you don't have git installed on your machine.

**Comment by shaymarketing** [comment]
@knownasilya Thanks for replying. I have git installed. I use bitbucket and github every day.

git version 1.9.4.msysgit.2

**Comment by knownasilya** [comment]
@shaymarketing otherwise it looks like something doesn't exist.. a file or directory, maybe a branch..

**Comment by shaymarketing** [comment]
btw, the git clone command mentioned in the error log above works for me when executed from the CLI; but seems to be failing when I press the Test button in the Strider UI.

**Comment by knownasilya** [comment]
@shaymarketing maybe the directory it's trying to clone to doesn't have write permissions?

**Comment by knownasilya** [comment]
@shaymarketing did you get this fixed?

**Comment by shaymarketing** [comment]
Hey Ilya,
No I didn't get it to work. I moved on to another CI and CD solution.

**Comment by knownasilya** [comment]
@shaymarketing if you want to get back to this, feel free to reopen.

**Comment by DivyaMadari17** [comment]
Hi @knownasilya ,

I am facing similar issue, 

Scheduled jobs on Katalon testops - pointing to a repo in bitbucket. 
Below is the debug log,
2021-11-09T09:07:38.058Z] [ERROR]: 	Error: spawn git ENOENT
    at Process.ChildProcess._handle.onexit (internal/child_process.js:240:19)
    at onErrorNT (internal/child_process.js:415:16)
    at process._tickCallback (internal/process/next_tick.js:63:19)
{
  "task": {
    "commands": [
      "clone",
      "--depth",
      "1",
      "--branch",
      "master",
      "https://divyamadari:************8@bitbucket.org/********/automation",
      "D:\\KatalonAgent\\tmp\\2021.11.09-14.37--13900-lDq3dFQrBYiH-429558\\automation"
    ],
    "format": "utf-8"
  }


any help is appreciated!

**Comment by knownasilya** [comment]
Most likely you don't have `git` installed, or it's not on your `PATH` env.

**Comment by DivyaMadari17** [comment]
@knownasilya I do have it.. installed and in the path env.
git --version gives me "git version 2.33.1.windows.1".

**Comment by knownasilya** [comment]
@DivyaMadari17 and you have the following envs set?

```
export PLUGIN_BITBUCKET_APP_KEY="<your_bitbucket_appkey>"
export PLUGIN_BITBUCKET_APP_SECRET="<your_bitbucket_appsecret>"
```
