### ISSUE TITLE
Cannot install strider in EC2 t1.micro instance

### ISSUE THREAD

**Issue by chenweiyj** [Strider-CD/strider#744]
I am installing `strider` in EC2 t1.micro instance via typing `npm install -g strider` in the ssh terminal. However, the following message is shown in a certain step.

```
npm ERR! EEXIST, open '/home/ec2-user/.npm/8a851f8c-ser-npm-lodash-1-3-1-package-tgz.lock'
File exists: /home/ec2-user/.npm/8a851f8c-ser-npm-lodash-1-3-1-package-tgz.lock
Move it away, and try again. 

npm ERR! System Linux 3.14.27-25.47.amzn1.x86_64
npm ERR! command "/home/ec2-user/.nvm/v0.10.36/bin/node" "/home/ec2-user/.nvm/v0.10.36/bin/npm" "install" "-g" "strider"
npm ERR! cwd /home/ec2-user
npm ERR! node -v v0.10.36
npm ERR! npm -v 1.4.28
npm ERR! path /home/ec2-user/.npm/8a851f8c-ser-npm-lodash-1-3-1-package-tgz.lock
npm ERR! code EEXIST
npm ERR! errno 47
npm ERR! not ok code 0
```

So is there any approach to solve it? Thank you very much.

**Comment by fernandoneto** [comment]
try 

`rm -fR ~/.npm/`

and then try to install strider again

**Comment by chenweiyj** [comment]
@fernandoneto 

I tried your approach and the above error still shows.

**Comment by fernandoneto** [comment]
@chenweiyj is only this error you got? can you try update your npm version? 
`npm install -g npm` .

**Comment by knownasilya** [comment]
@chenweiyj I don't recommend using `-g`, just clone this project and do `npm install`.

**Comment by chenweiyj** [comment]
@fernandoneto thx. update npm fixes this problem.
