### ISSUE TITLE
Strider crashes on new jobs started from a Pull Request that has been rebased

### ISSUE THREAD

**Issue by bitwit** [Strider-CD/strider#745]
We've been seeing these for a little while, but it was hard to track down the culprit until enough of a pattern emerged. Jobs started by pull requests, when retriggered by a rebase appear to crash the server. It automatically restarts itself but any in progress or queued job are killed and marked as zombies on restart.

The strider log looks like
```
2015-03-20T15:24:18.800Z - ^[[32minfo^[[39m: [runner:simple-runner] Queued new job. Project: flowpress/api Job ID: 550c3ba26f16ea6956253552

/usr/local/lib/node_modules/strider/lib/backchannel.js:141
        self.waiting[name].forEach(function (item) {
                           ^
TypeError: Cannot call method 'forEach' of undefined
    at /usr/local/lib/node_modules/strider/lib/backchannel.js:141:28
    at /usr/local/lib/node_modules/strider/node_modules/async/lib/async.js:592:17
    at done (/usr/local/lib/node_modules/strider/node_modules/async/lib/async.js:135:19)
    at /usr/local/lib/node_modules/strider/node_modules/async/lib/async.js:32:16
    at Promise.<anonymous> (/usr/local/lib/node_modules/strider/node_modules/async/lib/async.js:589:21)
    at Promise.<anonymous> (/usr/local/lib/node_modules/strider/node_modules/mongoose/node_modules/mpromise/lib/promise.js:177:8)
    at Promise.EventEmitter.emit (events.js:95:17)
    at Promise.emit (/usr/local/lib/node_modules/strider/node_modules/mongoose/node_modules/mpromise/lib/promise.js:84:38)
    at Promise.fulfill (/usr/local/lib/node_modules/strider/node_modules/mongoose/node_modules/mpromise/lib/promise.js:97:20)
    at /usr/local/lib/node_modules/strider/node_modules/mongoose/lib/query.js:1052:26
    at model.Document.init (/usr/local/lib/node_modules/strider/node_modules/mongoose/lib/document.js:250:11)
    at completeMany (/usr/local/lib/node_modules/strider/node_modules/mongoose/lib/query.js:1050:12)
    at Object.cb (/usr/local/lib/node_modules/strider/node_modules/mongoose/lib/query.js:1016:11)
    at Object._onImmediate (/usr/local/lib/node_modules/strider/node_modules/mongoose/node_modules/mquery/lib/utils.js:137:16)
    at processImmediate [as _immediateCallback] (timers.js:330:15)
22121 died 8 null
22979 forked
```

Haven't looked much into the core libs of Strider before but if there's someway I can help resolve the issue with more info/tests, let me know.

**Comment by knownasilya** [comment]
@bitwit what version of Strider are you using?

**Comment by bitwit** [comment]
We're on 1.6.2 at the moment. Think 1.6.4 could make any diff?

**Comment by bitwit** [comment]
I'll confirm as soon as I can, in any case

**Comment by knownasilya** [comment]
Yeah, there were some major bug fixed between 1.6.2 and 1.6.4

**Comment by bitwit** [comment]
Aha, okay so this isn't core strider's fault it appears.

This is the [strider-github-status](https://github.com/Strider-CD/strider-github-status) plugin actually. 

When you asked me to upgrade it uninstall the plugin, which brought me to this revelation. Removing the plugin prevented the crash, even though it was something in the strider lib that broke on it.

I'll add an issue in that repo

**Comment by bitwit** [comment]
Unfortunately, I'm back to thinking this is a problem in core strider. After removing the github-status plugin completely and upgrading to 1.6.6 we've still seen the issue occasionally, though getting perfect re-creatable steps has continued to be a problem.
I will keep trying, but I just don't want to take anyone on a wild goose chase the wrong way in the meantime

**Comment by knownasilya** [comment]
@bitwit all and any help is always appreciated!

**Comment by bitwit** [comment]
So I set a `console.log` just above `lib/backchannel.js:146` to try and diagnose this better after it happens. We had another crash today after a rebased pull request so I went to the logs not can see that `self.waiting` is and empty object (`{}`), which means that `self.waiting[name]` returns `undefined` and crashes when calling `.forEach`. I can see that the `name` parameter is populated correctly and my `job.project' appears to also have everything.

So I can see that `self.waiting[name]` is being populated on line 110 with an empty array, but also deleted on line 150. 

Maybe the callback on `async.parallel` is getting fired twice?

The easy patch fix would be to just wrap it in `try/catch` and call it a day. I suspect the `forEach` isn't doing much anyway because it looks like in my history it's always an empty array anyway, and the `send` call is just for web socket messaging.

Anyway, some more food for thought on how to drill this down but I still am unsure of the root cause.

**Comment by bitwit** [comment]
We had another crash today and *not* from a rebase but instead a deploy that tags and commits simulataneously. This has led me to another conclusion.

I believe this is happening when two events are queued for the same project near simultaneously. In both cases it has been a new commit accompanied by either a tag or a pull request job started. I suspect that since they are both using the same project name that the code in in `backchannel.js` can have a race condition that sets `self.waiting[name]` twice, then deletes it on the first event async event callback.

I'm going to simply try checking if it is undefined and moving on but there's probably a more elegant way to solve this such as a some sort of unique identifier instead of project name.
