### ISSUE TITLE
Can not reset password: "Project not found"

### ISSUE THREAD

**Issue by m00t** [Strider-CD/strider#748]
When go to link in email http://<domain>/reset/<token> got this page: "Project not found"
Strider version 1.6.4

**Comment by knownasilya** [comment]
@m00t I can't reproduce this issue, are you setting `SERVER_NAME` to something?

I get urls like: `http://localhost:3000/reset/fac0a6d2756656562d7056d19a6109f9b37ef01d`.

**Comment by m00t** [comment]
Sorry, I didnt recognize that parser eat my url. I mean when I go to link http://my_server_name.com/reset/password_reset_token
