### ISSUE TITLE
Can not see project page: "Not authorized"

### ISSUE THREAD

**Issue by anton-siardziuk** [Strider-CD/strider#750]
When logged in as non-admin user and non project creator, I can see project on dashboard, but got "Not authorized" error when go to project page. Strider version 1.6.4

**Comment by m00t** [comment]
According to middleware code (https://github.com/Strider-CD/strider/blob/master/lib/middleware.js#L305) user can see project only if he have access_level > 0. And Read option corresponds to access_level = 0. So when I register collaborator with Read value, he can not see project page.

**Comment by m00t** [comment]
Tried to add collaborator with Admin option: same result, access_level = 0 in mongodb.

**Comment by knownasilya** [comment]
I'll have a look, seems like something was missed in a refactor.

**Comment by m00t** [comment]
What is desired bahavior here? Should users invited with "Read" option be able to see project and run builds by hand?

**Comment by knownasilya** [comment]
Really there are 3 levels:

* view (0)
* start (1)
* edit (2)

So the collaborators sets it to 0 for Read, which is technically correct, but that also allows you to start the deploy/test for the ones that they can see, which is wrong.

**Comment by knownasilya** [comment]
> According to middleware code [redacted url] user can see project only if he have access_level > 0.

So that's for detail views, jobs, and config pages. You can see the project in the list, that's about it. Kind of useless if you ask me.

**Comment by m00t** [comment]
Is level 1 working now? Can I set it in mongodb for example?

**Comment by knownasilya** [comment]
@m00t give it a try, not sure if it's working.

**Comment by zakjan** [comment]
@m00t https://github.com/Strider-CD/strider/issues/750#issuecomment-86058583 There is a bug with saving the access level, it can be fixed with my PR #836
