### ISSUE TITLE
addUser -f creates copies of user

### ISSUE THREAD

**Issue by ryanfields** [Strider-CD/strider#754]
Subsequent calls to addUser with the -f option for a given user keep inserting new copies of the user.  The -h output suggests that the user entry will be overwritten, so I expect remove/add or update to occur.  Instead, it just runs an insert query on every execution.

**Comment by knownasilya** [comment]
Duplicate of #584

**Comment by knownasilya** [comment]
Should be fixed with 1.4.7 of strider-cli
