### ISSUE TITLE
wrong url for config button

### ISSUE THREAD

**Issue by brugnara** [Strider-CD/strider#755]
The config button placed in the page of the selected project (say /brugnara/test) points to a "random" url: `/appgeo/unisys_2014-0331.cbpwaittimes/config`.

**Comment by knownasilya** [comment]
Good catch. Complete fluke on my part.

**Comment by brugnara** [comment]
thank you :+1:

**Comment by knownasilya** [comment]
@brugnara can you give 1.6.6 a try, not sure if it published correct.

**Comment by brugnara** [comment]
I have pulled from master right now and this specific bug seems ok.
