### ISSUE TITLE
plugin request: Expose ability to trigger project deploy via REST API

### ISSUE THREAD

**Issue by paul42** [Strider-CD/strider#756]
I know there is an existing web hooks plugin, but that appears to just send out messages after a build has been completed, is there a way to make a plugin that allows for triggering of builds on incoming messages? 

I'd like new servers coming up to reach out to strider and trigger a deployment process

**Comment by bitwit** [comment]
Not quite RESTful, but strider is already capable of running a job via a couple of API calls. The only problem, I believe, is that you need to get a cookie session started before you hit the endpoint that cna run a job.

The code that runs jobs form the CLI actually uses this exact method: https://github.com/Strider-CD/strider-cli/blob/master/run.js

Again, not quite RESTful, but if you were looking for a way within the existing code, this is how.

**Comment by scryptmouse** [comment]
You can also set authenticate with a header on the request, in the format `"Authorization: basic " + base64(username + ":" + password)`, per http://strider.readthedocs.org/en/latest/hacking.html

You post to `/projectname/start` to trigger a run. By default it's test only but you can specify it should deploy as well via params.

https://github.com/Strider-CD/strider/blob/master/lib/routes/api/jobs.js#L23 is the method for the API call.

**Comment by bitwit** [comment]
^ Even better. Pretty sure that satisfies the OP's request precisely and bonus I learned something too :)

**Comment by knownasilya** [comment]
@paul42 does that satisfy your question/request?

**Comment by paul42** [comment]
This satisfies my request, thank you very much :)
