### ISSUE TITLE
vendor/CodeMirror should be vendor/codemirror

### ISSUE THREAD

**Issue by oliversalzburg** [Strider-CD/strider#766]
On a fresh checkout, `make` will fail because it can't find `vendor/codemirror`. Issue is probably introduced from a case-insensitive FS.

**Comment by knownasilya** [comment]
The only reason make is still there is because the tests haven't been moved out. I'll keep this as a cleanup or  remove make issue.

**Comment by oliversalzburg** [comment]
Yeah, I'm not sure how relevant this ticket is. I was a bit confused when I was setting up our new Strider instance.

I was cloning from git directly and ran into this issue. I later just installed from npm and didn't have any problem.

I just thought I should mention it, as it seemed like a mistake related to case sensitivity.

Close at will :)
