### ISSUE TITLE
Strider GitHub account issue

### ISSUE THREAD

**Issue by cusspvz** [Strider-CD/strider#774]
Strider Release: latest
Strider GitHub provider release: 1.4.1 
Issue: "Refresh Accounts" updates repo from fetched organizations but it wont load newly created organizations.

**Comment by cusspvz** [comment]
Problem was that access wasn't granted for that organization on App tokens. Fixed! :)

**Comment by knownasilya** [comment]
Glad you solved it. Do you know if there was an error in the console log? Maybe we can provide a ui error for this.

**Comment by cusspvz** [comment]
I've figured out that wasn't a Strider error but a token's access instead:
![captura de ecra 2015-05-11 as 13 29 19](https://cloud.githubusercontent.com/assets/3604053/7564764/c897cb00-f7e1-11e4-8b88-57605e12138f.png)

Just remembered that it could be the cause after creating this issue, sorry. :p

At least it may help someone. :)
