### ISSUE TITLE
Fresh Project  - NaN years ago

### ISSUE THREAD

**Issue by nexflo** [Strider-CD/strider#777]

**Comment by knownasilya** [comment]
Where is this?

**Comment by fernandoneto** [comment]
some time ago i have a the same error when i try to run a new job. 
![captura de ecra de 2015-05-21 15 48 59](https://cloud.githubusercontent.com/assets/6515784/7751266/f27b28da-ffd0-11e4-88ab-bbc870ed1190.png).

I just update strider and problem solved.

**Comment by knownasilya** [comment]
Should be fixed here: https://github.com/Strider-CD/strider/commit/0ff581605be9f3bc4dc648a9b375e465281501f4#diff-bc17a19c5fe11d201beea1ab1b5b21ffR69
