### ISSUE TITLE
Deploy to Heroku button fails

### ISSUE THREAD

**Issue by csu** [Strider-CD/strider#778]
Breaks on the "Build app" phase.
Full build log: https://gist.github.com/csu/6cbc830ade3bb403f5bb
Seems to be a Heroku problem though (???)

**Comment by knownasilya** [comment]
Duplicate of #716

**Comment by knownasilya** [comment]
Feel free to continue discussion in that issue.

**Comment by csu** [comment]
@knownasilya Ah, thanks. Thought it was a different error because it looked like `npm install` was successful.

**Comment by knownasilya** [comment]
Sorry, I think it was actually #433
