### ISSUE TITLE
Update jaredly/ssh-keypair

### ISSUE THREAD

**Issue by oliversalzburg** [Strider-CD/strider#786]
That project is generating weak DSA keys and there is no option to use something proper. RSA is the standard and for good reason.

There seems to be a very similar project, which is also laughably unconfigurable, but at least uses 2048bit RSA: https://github.com/ericvicenti/ssh-keygen

**Comment by niallo** [comment]
It's just calling `ssh-keygen -t dsa`. DSA keys are always 1024 bits as
specified by FIPS 186-2.

I don't think 1024 bit DSA keys are especially insecure compared to RSA. I
believe the crypto-jury is still out on which format is most secure. If it
were highly insecure, ssh-keygen wouldn't support it.

However I agree key format should be configurable. The change would be
quite trivial.

On Mon, Jun 1, 2015 at 2:21 PM, Oliver Salzburg <notifications@github.com>
wrote:

> That project is generating weak DSA keys and there is no option to use
> something proper. RSA is the standard and for good reason.
>
> There seems to be a very similar project, which is also laughably
> unconfigurable, but at least uses 2048bit RSA:
> https://github.com/ericvicenti/ssh-keygen
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/Strider-CD/strider/issues/786>.
>



-- 
Niall O'Higgins
W: http://niallohiggins.com
E: n@niallo.me
T: @niallohiggins

**Comment by oliversalzburg** [comment]
I'm hardly a crypto expert, but it is my understanding that using DSA keys nowadays is discouraged because, even if they aren't inherently insecure, the alternatives are more secure and using them comes at negligible computational cost. `ssh-keygen` *will* still generate those keys, but it's not the default (meaning that, if no `-t` is provided, it will generate an RSA key).

I personally believe in using safe defaults and I would consider it *safe* to use a strong key. If someone deliberately want's to use a weaker key, they should have the option to, but forcing `ssh-keygen` out of it's default behavior to generate a weaker key by default is not cool.

**Comment by knownasilya** [comment]
@oliversalzburg feel free to submit a PR for this.

**Comment by oliversalzburg** [comment]
@knownasilya Good point. I'll try my luck submitting a change to the dependency.

**Comment by oliversalzburg** [comment]
For reference: https://github.com/jaredly/ssh-keypair/pull/5
