### ISSUE TITLE
Default strider-gitlab plugin is not the one maintained in strider-cd org

### ISSUE THREAD

**Issue by oliversalzburg** [Strider-CD/strider#790]
When installing strider, `strider-gitlab` will be installed through npm, which points to https://github.com/meric426/strider-gitlab. This package references `strider-git` by `git+https` URL, always resulting in a separate copy of `strider-git`.

Either `strider-gitlab` should be included through a version git tag, or re-published to npm under a new name.

**Comment by marcuspoehls** [comment]
You're right and there is an existing issue over at strider-gitlab`
https://github.com/Strider-CD/strider-gitlab/issues/7

**Comment by oliversalzburg** [comment]
@marcuspoehls Given that the issue was opened 4 months ago, I think it simply shouldn't be included in strider as a direct dependency.

Luckily, strider has its own system to handle plugins and doesn't rely on npm. But including a plugin, that is not under the control of the strider organization and where the author doesn't seem responsive, directly through npm is not wise IMHO.

Another option would be to simply not include any non-critical plugins in `package.json` to begin with. Maybe that would also resolve of the dependency chaos I'm seeing right now :D

**Comment by marcuspoehls** [comment]
@oliversalzburg That's exactly the problem we're currently fighting: plugin mess.

The best solution (at this point) to fix the issues with `strider-gitlab` would be to remove it from Strider's `package.json` so it doesn't get installed initially. Since Strider has it's own plugin ecosystem index, the latest plugin version of `strider-gitlab` get's installed when using Strider's admin panel.

**Comment by oliversalzburg** [comment]
Closed per https://github.com/Strider-CD/strider/commit/c4e2a1e85e97972d27a9338346362097bea18a7e

**Comment by meric426** [comment]
Sorry for posting in an old issue but i've told github to remove the "fork"-part of Strider-CD/strider-gitlab and I've given @oliversalzburg, @saraf and @knownasilya permission to publish to the strider-gitlab package

**Comment by knownasilya** [comment]
:+1: just waiting on the travis part to merge your PR.

**Comment by oliversalzburg** [comment]
@meric426 Thanks a lot! It's appreciated :)
