### ISSUE TITLE
JavaScript errors when loading most pages

### ISSUE THREAD

**Issue by djensen47** [Strider-CD/strider#796]
GET http://hostname/scripts/app.js net::ERR_CONTENT_DECODING_FAILED
plugin-config-compiled.js:6 Uncaught ReferenceError: angular is not defined(anonymous function) @ plugin-config-compiled.js:6
account-plugins-compiled.js:6 Uncaught ReferenceError: angular is not defined(anonymous function) @ account-plugins-compiled.js:6
plugin-status-compiled.js:6 Uncaught ReferenceError: angular is not defined(anonymous function) @ plugin-status-compiled.js:6

**Comment by oliversalzburg** [comment]
Try building resources with `npm run build`.

**Comment by michaelmior** [comment]
Closing due to lack of response. If you still see this issue in the current version of Strider, feel free to comment and this can be reopened.
