### ISSUE TITLE
How to add a private github repository on strider

### ISSUE THREAD

**Issue by mateeyow** [Strider-CD/strider#803]
As the title says. I'm a bit confused in adding a private github repository. I've tried adding my username and password on the http(s) auth type but the notification only shows failed to create project without any reason why.

**Comment by oliversalzburg** [comment]
1. Make sure you allow the `strider-github` plugin to communicate with GitHub. Go to https://github.com/settings/developers and register a new application. Make sure the **Homepage URL** is the correct URL where your Strider instance runs. The **Authorization callback URL** should be `https://your.strider.instance/auth/github/callback`.

2. According to https://github.com/Strider-CD/strider-github, set the `PLUGIN_GITHUB_APP_ID` and `PLUGIN_GITHUB_APP_SECRET` environment variables to the values you got when you registered your application in step 1.

3. In Strider, go to your account and click on Github. You'll be able to add your account here and link up Strider with GitHub.

4. When you now go to your Projects overview, you should see a GitHub tab with your username on it. Here, you should be able to import all your projects.

Let me know if it doesn't work out :)

**Comment by knownasilya** [comment]
Step **1** should be automatic, as long as all of your strider settings are correct, like `SERVER_NAME`..

**Comment by mateeyow** [comment]
@oliversalzburg Thanks. I did all of the steps yestereve. Didn't realize the private repository was not mine. But it's there. Thanks a lot.

**Comment by mateeyow** [comment]
Weird, I am getting this error message:  `{"results":[],"status":"error","errors":[{"code":500,"reason":"Failed to setup repo: Bad status code: 404"}]}` when creating a private repo that is originally not mine.

**Comment by oliversalzburg** [comment]
@mateeyow Do you have access to the strider log? What exactly is the configuration here? Is this a private repo of another individual or an organization?

**Comment by mateeyow** [comment]
Here's the error log
```
strider stdout | 2015-06-10T08:36:58.040Z - info: Bad status code: 404
strider stdout | 2015-06-10T08:36:58.042Z - info: Error: Bad status code: 404
    at Request._callback (/opt/strider/src/node_modules/strider-github/lib/api.js:55:26)
    at Request.self.callback (/opt/strider/src/node_modules/strider-github/node_modules/request/request.js:129:22)
    at Request.EventEmitter.emit (events.js:98:17)
    at Request.<anonymous> (/opt/strider/src/node_modules/strider-github/node_modules/request/request.js:873:14)
    at Request.EventEmitter.emit (events.js:117:20)
    at IncomingMessage.<anonymous> (/opt/strider/src/node_modules/strider-github/node_modules/request/request.js:824:12)
    at IncomingMessage.EventEmitter.emit (events.js:117:20)
    at _stream_readable.js:920:16
    at process._tickCallback (node.js:415:13)
```
I'm using docker-strider and all the environment is correctly configured. I can create a project if the repository is public. And the private repo is of another individual

**Comment by oliversalzburg** [comment]
@mateeyow Do you know whether you have write access to the repo? From what I can tell, strider isn't able to create the service hook in the repo. Which is understandable. But this case should definitely be handled in a better way.

**Comment by mateeyow** [comment]
Yes, I have write access since I can push into the repo. Is this in anyway connected to the SSH keys?

**Comment by oliversalzburg** [comment]
@mateeyow I don't think so, but I would have to check the complete workflow of the plugin to be sure.

On Github, when you go into the settings of the repo, are you allowed to add webhooks manually?

**Comment by mateeyow** [comment]
Nope I can't

**Comment by oliversalzburg** [comment]
@mateeyow That seems to be the core of the issue. Strider is trying to create a webhook and fails to do so. I guess only the owner of a private repo can add them.

Strider *could* ignore this problem, but it would not be able to start a build when you commit to the GitHub repo and I don't think there is a workflow in Strider to allow you to manually set up the hooks.

Your best option at this point is to give the owner of the repo access to your Strider and let them set up the project in Strider. I'm not quite sure if you will be able to edit the project in Strider once it was created by another user, but this is worth a shot.

**Comment by mateeyow** [comment]
Thanks a lot for the enlightment @oliversalzburg
