### ISSUE TITLE
Lets Refactor strider to diet.js framework for faster coding and more easy handling

### ISSUE THREAD

**Issue by frank-dspeed** [Strider-CD/strider#806]
Changing the framework from express to diet will improve code readability and allow promises and all that.

**Comment by oliversalzburg** [comment]
Can you give an example of the improvements you mention?

**Comment by frank-dspeed** [comment]
http://dietjs.com/

look here read it it will not take more then 30 min to read it all you will after that understand that we get a good plugin system and theme system as also better code and modularity because the promise like signal styles referenzed as $ simply read it all.

it will save us even from call back hell and will also reduce the whole code to be more readable.

**Comment by knownasilya** [comment]
Feel free to submit a PR ;)
