### ISSUE TITLE
SERVER_NAME isn't working

### ISSUE THREAD

**Issue by girvo** [Strider-CD/strider#809]
Hi all,

I've set the `SERVER_NAME` environment variable correctly, both in my `forever-service` installation and in my `/etc/environment` however for some reason whenever I try to setup OAuth connections the redirect URL is set to `http://localhost:3000/`.

Is there something in the docs that's missing, or have I done something silly?

**Comment by oliversalzburg** [comment]
It's working for us. I would suspect your setup isn't correct.

**Comment by fernandoneto** [comment]
working fine for me too. can you try set the variable in `.bashrc` or `.bashprofile` only?

**Comment by olalonde** [comment]
Getting same error on master.

**Comment by olalonde** [comment]
Fixed by adding `PLUGIN_GITHUB_APP_ID` and `PLUGIN_GITHUB_APP_SECRET` env config.

**Comment by knownasilya** [comment]
@girvo can you try that?

**Comment by knownasilya** [comment]
Ping

**Comment by knownasilya** [comment]
Closed since the original poster is unresponsive.
