### ISSUE TITLE
Checking existence of file in project

### ISSUE THREAD

**Issue by mabc224** [Strider-CD/strider#810]
i am writing a custom plugin. In this plugin, i want to check existence of some specific file in environment stage of project. If file exist, I want to do some work.

Here it is part of my file. This function is defined in worker.js file and plugin type is job.
I am using GitHub provider plugin supplied with StriderCD.

```javascript
			environment: function(context, done){
				var fs = require('fs');
				var filesExist = fs.existsSync(".circ");
				context.out('File Existence '+filesExist+ '\n', 'stdout');
				if(filesExist){
					exec('rm -rf lib', function (error, stdout, stderr) {
						console.log('stdout: ' + stdout);
						console.log('stderr: ' + stderr);
						if (error !== null) {
							context.out("Error" + error + '\n', 'stderr');
							done(error, true);
						} else {
							context.out('Removed'+stdout + '\n', 'stdout');
							done(null, true);
						}
					});
				}
			},

```

Above code is not detecting file. How can i check existence of file? 

label: Question

**Comment by oliversalzburg** [comment]
You probably need to construct an absolute path to `.circ`. I'm not sure where you expect the file to exist.

**Comment by knownasilya** [comment]
Have a look at strider-node, it looks for a file.

**Comment by mabc224** [comment]
@knownasilya  
Thanks for pointing out. 

@oliversalzburg 
Here it is my project. 
[https://github.com/mabc224/demo-todo-express-app](https://github.com/mabc224/demo-todo-express-app)
I want to check in environment stage that there exists **.circ** file in root folder of project.
i try **context.dataDir** and it finds the path.
but now the problem is **git clone** is working in prepare stage and i am unable to detect file in environment stage.
how can i reorder this.

**Comment by oliversalzburg** [comment]
@mabc224 If you want to access a file in your repo, *before* it was cloned, you will need to retrieve it directly through the source code provider plugin.

This is what is done for the `strider.json` file during the environment phase.

For your reference:
- https://github.com/Strider-CD/strider/blob/master/lib/backchannel.js#L37
- https://github.com/Strider-CD/strider-github/blob/master/lib/api.js#L121

**Comment by mabc224** [comment]
@oliversalzburg i want to run multiple tasks in order in specific stage. I have _.conf_ file where i have defined these tasks.
if execution of all tasks of specific stages have completed then that stage should give successful response. otherwise show error message.
currently i defined it in this way. Need your suggestion to control order and response.

**.conf**
```json
{
    "tasks": {
        "my-custom-script": {
            "type": "script",
            "path": "start.sh"
        },
        "notify-slack": {
            "type": "slack",
            "channel": "#development"
        }
    },
    "stages": {
        "environment": [],
        "prepare": [
            "my-custom-script",
            "notify-slack"
        ],
        "test": [],
        "deploy": [],
        "cleanup": []
    }
}
```

```javascript
prepare: function (context, done) {
    var filesExist = fs.existsSync(path.join(context.dataDir, '.conf'));
    if (filesExist) {
        var circJsonObj = JSON.parse(fs.readFileSync(path.join(context.dataDir, '.conf'), 'utf8'));
        var prepareTssk = circJsonObj.stages.prepare;
        if (prepareTssk.length) {
            prepareTssk.forEach(function (task) {
                var obj = circJsonObj.tasks[task];
                context.out("Satrt executing task " + task + '\n', 'stdout');
                switch (obj.type) {
                    case "script":
                        script(obj, context, done);
                        break;
                    case "slack":
                        slackPublish(obj, context, done);
                        break;
                    default:
                        context.out("No such task found" + '\n', 'warn');
                        break;
                }
            });
        } else {
            return done(null, false);
        }

    } else {
        done(null, false);
    }
}
,


function slackPublish(object, context, cb) {
    var channel = object.channel || "#general";
    var message = array.join('\n') || "No text specified";
    var username = object.username || "Strider";
    slack(message, channel, username, function (err) {
        if (err) {
            context.out("Slack error occurred" + '\n', 'stderr');
            return cb(err, true);
        }
        context.out('Slack published ' + '\n', 'stdout');
        cb(null, true);
    });
}

function script(object, context, cb) {
    var type = object.type.toLowerCase() || "script";
    var scriptPath = object.path;
    runscript(type, scriptPath, function (err) {
        if (err) {
            context.out("Error: executing bash script -> " + scriptPath + "\n " + err + '\n', 'stderr');
            return cb(err, true);
        }
        cb(null, true);
    });
};
```

**Comment by knownasilya** [comment]
@mabc224 looks like you are recreating what's already in `strider.json`, se here: https://github.com/Strider-CD/strider-custom#using-striderjson

**Comment by oliversalzburg** [comment]
@mabc224 It's possible that I implemented something similar for our setup recently.

We use `strider.json` to run custom scripts at each stage. We have a file named `strider.json` in our repository. This file is loaded by strider through the VCS provider plugin and merged with the web configuration. Our file looks like this for one project:

```json
{
	"merge_plugins": false,
	"plugins": [
		{
			"id": "node",
			"enabled": true,
			"showStatus": true,
			"config": {
				"test": "npm test",
				"caching": "strict",
				"runtime": "whatever",
				"fork": "Node.js"
			}
		},
		{
			"id": "bower",
			"enabled": true,
			"showStatus": true,
			"config": {
				"caching": "strict"
			}
		},
		{
			"id": "custom",
			"enabled": true,
			"showStatus": true,
			"config": {
				"prepare": ".scripts/prepare.sh --<%= ref.branch %>",
				"deploy": ".scripts/deploy.sh --<%= ref.branch %>"
			}
		}
	]
}
```

We then place scripts in the `.scripts` folder of our project. `prepare.sh` looks like:

```bash
#!/bin/sh
basedir=`dirname "$0"`

case `uname` in
    *CYGWIN*) basedir=`cygpath -w "$basedir"`;;
esac

# Move the location of this script.
cd ${basedir}
# Now traverse to the project root.
cd ..
# Install our build-utils, so we can invoke them.
npm install git+https://…/build-utils.git

if [ -x "$basedir/node" ]; then
  "$basedir/node"  "$basedir/../node_modules/…/build-utils/lib/prepare.js" "$@"
  ret=$?
else
  node  "$basedir/../node_modules/…/build-utils/lib/prepare.js" "$@"
  ret=$?
fi
exit ${ret}
```bash

`prepare.js` is then a normal NodeJS application that does all kinda of funky tasks.

**Comment by mabc224** [comment]
@oliversalzburg i have not only t run custom scripts. I have many tasks for different stages.
For example there is a task to create dns hostname by calling rundeck job scheduler api.
I can define creating dns hostname in any stage.
```json
{
    "tasks": {
        "my-dns": {
            "type": "hostname",
            "path": "dev.custom.local"
        },
        "npm-deploy": {
            "type": "npm",
            "action": "publish"
        },
        "ecs-main": {
            "type": "ecs",
            "action": "deploy"
        }
    },
    "stages": {
        "environment": [],
        "prepare": [
            "my-dns"
        ],
        "test": [],
        "deploy": [
            "npm-deploy",
            "ecs-main"
        ],
        "cleanup": []
    }
}
```

Also there involve a task to deploy on local npm registry and Amazon ECS at different stages.
Do i need to create plugin for these tasks separately and for each stage? I want freedom for user so that he could define these tasks for any stages.

**Comment by oliversalzburg** [comment]
@mabc224 I don't see why that wouldn't be possible with what I suggested. Either way, if you still want to roll your own plugin, the way to do it should be clear by now.

**Comment by knownasilya** [comment]
I see this in the future, being able to customize more granularly when things run. Currently it's kind of magic, since the plugins run in the order that you put them in the plugin list, but then it's not clear what plugin runs at what phase. The user should know the flow of the build/test/deploy..

**Comment by knownasilya** [comment]
Closing since the question was answered, feel free to submit other issues.
