### ISSUE TITLE
'Upgrade all' upgrades just-uninstalled plugins

### ISSUE THREAD

**Issue by talexand** [Strider-CD/strider#812]
Steps to reproduce:

1. Uninstall an upgradable plugin from the admin panel while upgradable packages are available in the UI
2. Click 'Upgrade All'

Installed version: Strider 1.6.6 on heroku.

**Comment by oliversalzburg** [comment]
Yeah, I'm pretty sure this happened to me as well.

**Comment by macropin** [comment]
This is probably the same issue I've seen.

**Comment by knownasilya** [comment]
Could one of you try master and see if it solves the issue. Thanks.

**Comment by knownasilya** [comment]
This has been fixed in master.
