### ISSUE TITLE
Local environment setup for contributing

### ISSUE THREAD

**Issue by sebas5384** [Strider-CD/strider#813]
Hey! I want to contribute with plugins, and stuff but I don't know how to setup a local environment in order to develop and test the plugins.
For example like connecting with Github.

Any guidance?

thanks.

**Comment by oliversalzburg** [comment]
GitHub has a lot of guides available to get your started: https://help.github.com/

**Comment by knownasilya** [comment]
Also if you use `strider init` it will create a template plugin directory.

**Comment by sebas5384** [comment]
Thanks for the help!
My major doubt is about connecting my local strider to Github, because Github wont be able to reach my local environment, right?

**Comment by oliversalzburg** [comment]
@sebas5384 If you want to make use of service hooks, you will need to have a system that can be reached online. But you can always deploy manually, I guess.

**Comment by sebas5384** [comment]
hmmm @oliversalzburg good point, I could test it deploying manually, but what about connecting the Strider to Github account and cloning the repos?

**Comment by oliversalzburg** [comment]
@sebas5384 That should work just fine. You just need to configure the GitHub provider. I'm not sure where the process is documented though.

**Comment by knownasilya** [comment]
It should be automatic, as long as you set all of the env variables, see the strider-github (and strider) readme.

**Comment by sebas5384** [comment]
Thanks I'll try to install locally and then make some step-by-step guide :+1:

**Comment by knownasilya** [comment]
@sebas5384 I'm going to close this in favor of a PR :+1:
