### ISSUE TITLE
Change directory from the repos

### ISSUE THREAD

**Issue by charlitos85** [Strider-CD/strider#814]
I try to use strider into windows 2008 server, i need change the directory to use into strider repos.

How can do that? i cant find nothing

**Comment by knownasilya** [comment]
Can you be a little more specific about what you are trying to do?

**Comment by charlitos85** [comment]
i need replace the destination of the repo where strider  stored into windows. because for default strider try to use a temp directory, and generate a privilege error.

**Comment by oliversalzburg** [comment]
@charlitos85 Are you talking about the location where strider is installed or where it places checkouts of projects you're building?

**Comment by fernandoneto** [comment]
to change the destination where strider clones repos you can use the var `STRIDER_CLONE_DEST`

**Comment by knownasilya** [comment]
@fernandoneto thanks. I just added that to the readme.

**Comment by charlitos85** [comment]
i receive this error in the console

git clone --recursive git@bitbucket.com:test/test-xxx . --branch master bitbucket 3s
Invalid Date
 -1
Cloning into '.'...
bash.exe: warning: could not find /tmp, please create!
Warning: Identity file C:UsersADMINI~1AppDataLocalTemp2_gitaneidaff722db.key not accessible: No such file or directory.
Permission denied (publickey).
fatal: Could not read from remote repository.

Please make sure you have the correct access rights
and the repository exists.

**Comment by knownasilya** [comment]
Looks like gitane is trying to create temp files, but cannot. Sounds like a permissions issue, and a bad error message since /tmp isn't a valid windows path.

**Comment by oliversalzburg** [comment]
Sorry for not realizing it earlier, but gitane doesn't work on Windows at all. You're out of luck for the moment.

**Comment by knownasilya** [comment]
Regarding that, gitane was written before there were any decent node git clients, maybe it's time to replace it. I think there's an issue floating around about it too, https://github.com/Strider-CD/strider-github/issues/1

**Comment by oliversalzburg** [comment]
I just want to note that gitane is probably used because it allows using custom SSH keys.

**Comment by knownasilya** [comment]
But since github supports custom ssh keys, shouldn't it be automatic (just thinking out loud..)?

**Comment by oliversalzburg** [comment]
Not really. If you would just spawn git, it would use the SSH keys of the user that runs strider. But those aren't necessarily the ones that should be used. Especially since, currently, a new set of keys is generated for each project and is used for deployment keys and whatnot.
So the ability to be able to run git in an environment where strider has full control over the keys seems crucial to me right now.

**Comment by knownasilya** [comment]
So is it the ssh key part that isn't windows compatible?

**Comment by oliversalzburg** [comment]
Correct. The way Gitane sets up an environment for git/ssh to use seems impossible on Windows.

Gitane will set a `GIT_SSH` environment variable, so that git then tries to execute that file for SSH access. But the file is a shell script, which Windows can't run. And it's all downhill from there.

**Comment by knownasilya** [comment]
Closing this issue, since it's technically been answered and there are other issues related to the windows issue.
