### ISSUE TITLE
"Not authorized" error after adding user to collaborators

### ISSUE THREAD

**Issue by olalonde** [Strider-CD/strider#819]
I added a collaborator to a project but when accessing the project's URL, he is getting a "Not authorized" error page. The collaborator can succesfuly login in Strider.

**Comment by olalonde** [comment]
Setting the user as an admin fixes the issue though this is not idea.

**Comment by knownasilya** [comment]
The collaboration roles need to be straightened out. There's a related issue floating around.

**Comment by olalonde** [comment]
Yep seems to be a duplicate of: https://github.com/Strider-CD/strider/issues/750 , closing.
