### ISSUE TITLE
Strider and remote executors

### ISSUE THREAD

**Issue by ynnt** [Strider-CD/strider#821]
Hi!
Is there any remote runners for strider? For e.g. I want to build and then deploy my Obj-C application. 

Could I do this if my Strider server and XCode are on the different servers?

**Comment by knownasilya** [comment]
https://github.com/Strider-CD/strider-remote-worker that might work. I've never used it, but give it a try.

**Comment by ynnt** [comment]
It may be dumb question, but how can I run it?

**Comment by knownasilya** [comment]
@ynnt looks like you can't, see https://github.com/Strider-CD/strider-remote-worker/issues/2

**Comment by knownasilya** [comment]
Closing this as a duplicate of #571, feel free to continue the conversation there.
