### ISSUE TITLE
Failed to refresh repositories: [object Object]

### ISSUE THREAD

**Issue by carlitux** [Strider-CD/strider#823]
I can't refresh my projects from github but looks like reques is successfully.

statusCode: 200,
    status: 200,
    statusType: 2,
    info: false,
    ok: true,
    redirect: false,
    clientError: false,
    serverError: false,
    error: false,
    accepted: false,
    noContent: false,
    badRequest: false,
    unauthorized: false,
    notAcceptable: false,
    forbidden: false,
    notFound: false,
    charset: 'utf-8',
    type: 'application/json',
    setEncoding: [Function],
    redirects: [] } ]
2015-06-26T06:42:08.784Z - info: Saved repo cache

**Comment by knownasilya** [comment]
Make sure your filesystem user permissions are good.

**Comment by carlitux** [comment]
now is with root and paths has root as owner.

**Comment by knownasilya** [comment]
@carlitux did that solve the problem?

**Comment by carlitux** [comment]
No, I am still having same error.

**Comment by knownasilya** [comment]
@carlitux are there any errors in the server log/console?

**Comment by carlitux** [comment]
@knownasilya no just is logging the request.

**Comment by knownasilya** [comment]
What does the network request look like when you refresh?

**Comment by carlitux** [comment]
from master branch

[2015-07-01T18:12:35.279Z] (sys) Starting

> strider@1.6.6 start /path
> bin/strider

30439 forked
2015-07-01T18:12:39.177Z - info: Using SMTP transport from config
2015-07-01T18:12:39.830Z - info: Using MongoDB URL: mongodb://localhost/strider-foss
2015-07-01T18:12:40.996Z - info: RUNNER INIT
2015-07-01T18:12:41.223Z - info: loaded templates
2015-07-01T18:12:41.474Z - info: initalized webapps
2015-07-01T18:12:41.475Z - info: [job plugins]
2015-07-01T18:12:41.475Z - info: - custom
2015-07-01T18:12:41.475Z - info: - emailnotifier
2015-07-01T18:12:41.475Z - info: - env
2015-07-01T18:12:41.475Z - info: - heroku
2015-07-01T18:12:41.475Z - info: - metadata
2015-07-01T18:12:41.475Z - info: - node
2015-07-01T18:12:41.475Z - info: - python
2015-07-01T18:12:41.476Z - info: - ruby
2015-07-01T18:12:41.476Z - info: - slack
2015-07-01T18:12:41.476Z - info: - ssh_deploy
2015-07-01T18:12:41.476Z - info: [runner plugins]
2015-07-01T18:12:41.476Z - info: - simple-runner
2015-07-01T18:12:41.476Z - info: [provider plugins]
2015-07-01T18:12:41.476Z - info: - bitbucket
2015-07-01T18:12:41.477Z - info: - git
2015-07-01T18:12:41.477Z - info: - github
2015-07-01T18:12:41.477Z - info: [basic plugins]
2015-07-01T18:12:41.477Z - info: - buildbadge
2015-07-01T18:12:41.480Z - info: initalized static directories
2015-07-01T18:12:41.513Z - info: loaded config pages
2015-07-01T18:12:41.516Z - info: loaded account config pages
2015-07-01T18:12:41.527Z - info: loaded plugin status blocks
2015-07-01T18:12:41.527Z - info: loaded plugins
2015-07-01T18:12:41.535Z - info: Express server listening on port 7000 in production mode
2015-07-01T18:12:41.535Z - info: Marking zombie jobs as finished...
2015-07-01T18:12:41.546Z - info: 0 zombie jobs marked as finished
2015-07-01T18:12:45.695Z - info: Fetching projects...
2015-07-01T18:12:46.268Z - info: [ { req: 
     { domain: null,
       _events: [Object],
       _maxListeners: 10,
       output: [],
       outputEncodings: [],
       writable: true,
       _last: true,
       chunkedEncoding: false,
       shouldKeepAlive: false,
       useChunkedEncodingByDefault: false,
       sendDate: false,
       _headerSent: true,
       _header: 'GET /user/repos?access_token=&per_page=30&page=1 HTTP/1.1\r\nHost: api.github.com\r\nAccept-Encoding: gzip, deflate\r\nCookie: \r\nUser-Agent: StriderCD (http://stridercd.com)\r\nConnection: close\r\n\r\n',
       _hasBody: true,
       _trailer: '',
       finished: true,
       _hangupClose: false,
       socket: [Object],
       connection: [Object],
       agent: false,
       socketPath: undefined,
       method: 'GET',
       path: '/user/repos?access_token=&per_page=30&page=1',
       _headers: [Object],
       _headerNames: [Object],
       parser: null,
       res: [Object] },
    res: 
     { _readableState: [Object],
       readable: false,
       domain: null,
       _events: [Object],
       _maxListeners: 10,
       socket: [Object],
       connection: [Object],
       httpVersion: '1.1',
       complete: true,
       headers: [Object],
       trailers: {},
       _pendings: [],
       _pendingIndex: 0,
       url: '',
       method: null,
       statusCode: 200,
       client: [Object],
       _consuming: true,
       _dumped: false,
       httpVersionMajor: 1,
       httpVersionMinor: 1,
       upgrade: false,
       req: [Object],
       read: [Function],
       setEncoding: [Function],
       on: [Function],
       text: '[repositories]',
    body: 
     [ objects ],
    files: {},
    buffered: true,
    headers: 
     { server: 'GitHub.com',
       date: 'Wed, 01 Jul 2015 18:12:54 GMT',
       'content-type': 'application/json; charset=utf-8',
       'transfer-encoding': 'chunked',
       connection: 'close',
       status: '200 OK',
       'x-ratelimit-limit': '5000',
       'x-ratelimit-remaining': '4977',
       'x-ratelimit-reset': '1435777122',
       'cache-control': 'private, max-age=60, s-maxage=60',
       etag: 'W/"1b0c690146aecdd22bb5f688b07f57d6"',
       'x-oauth-scopes': 'repo',
       'x-accepted-oauth-scopes': '',
       'x-oauth-client-id': '414e8ba62a928d0d47f9',
       vary: 'Accept, Authorization, Cookie, X-GitHub-OTP',
       'x-github-media-type': 'github.v3; format=json',
       link: '<https://api.github.com/user/repos?access_token=f9012bcfad5f9cb1ef6995f2f73c531a0ed58bb0&per_page=30&page=2>; rel="next", <https://api.github.com/user/repos?access_token=f9012bcfad5f9cb1ef6995f2f73c531a0ed58bb0&per_page=30&page=2>; rel="last"',
       'x-xss-protection': '1; mode=block',
       'x-frame-options': 'deny',
       'content-security-policy': 'default-src \'none\'',
       'access-control-allow-credentials': 'true',
       'access-control-expose-headers': 'ETag, Link, X-GitHub-OTP, X-RateLimit-Limit, X-RateLimit-Remaining, X-RateLimit-Reset, X-OAuth-Scopes, X-Accepted-OAuth-Scopes, X-Poll-Interval',
       'access-control-allow-origin': '*',
       'x-github-request-id': 'D059D74C:461F:C8484D3:55942DA5',
       'strict-transport-security': 'max-age=31536000; includeSubdomains; preload',
       'x-content-type-options': 'nosniff',
       'x-served-by': '474556b853193c38f1b14328ce2d1b7d',
       'content-encoding': 'gzip' },
    header: 
     { server: 'GitHub.com',
       date: 'Wed, 01 Jul 2015 18:12:54 GMT',
       'content-type': 'application/json; charset=utf-8',
       'transfer-encoding': 'chunked',
       connection: 'close',
       status: '200 OK',
       'x-ratelimit-limit': '5000',
       'x-ratelimit-remaining': '4977',
       'x-ratelimit-reset': '1435777122',
       'cache-control': 'private, max-age=60, s-maxage=60',
       etag: 'W/"1b0c690146aecdd22bb5f688b07f57d6"',
       'x-oauth-scopes': 'repo',
       'x-accepted-oauth-scopes': '',
       'x-oauth-client-id': '414e8ba62a928d0d47f9',
       vary: 'Accept, Authorization, Cookie, X-GitHub-OTP',
       'x-github-media-type': 'github.v3; format=json',
       link: '<https://api.github.com/user/repos?access_token=f9012bcfad5f9cb1ef6995f2f73c531a0ed58bb0&per_page=30&page=2>; rel="next", <https://api.github.com/user/repos?access_token=f9012bcfad5f9cb1ef6995f2f73c531a0ed58bb0&per_page=30&page=2>; rel="last"',
       'x-xss-protection': '1; mode=block',
       'x-frame-options': 'deny',
       'content-security-policy': 'default-src \'none\'',
       'access-control-allow-credentials': 'true',
       'access-control-expose-headers': 'ETag, Link, X-GitHub-OTP, X-RateLimit-Limit, X-RateLimit-Remaining, X-RateLimit-Reset, X-OAuth-Scopes, X-Accepted-OAuth-Scopes, X-Poll-Interval',
       'access-control-allow-origin': '*',
       'x-github-request-id': 'D059D74C:461F:C8484D3:55942DA5',
       'strict-transport-security': 'max-age=31536000; includeSubdomains; preload',
       'x-content-type-options': 'nosniff',
       'x-served-by': '474556b853193c38f1b14328ce2d1b7d',
       'content-encoding': 'gzip' },
    statusCode: 200,
    status: 200,
    statusType: 2,
    info: false,
    ok: true,
    redirect: false,
    clientError: false,
    serverError: false,
    error: false,
    accepted: false,
    noContent: false,
    badRequest: false,
    unauthorized: false,
    notAcceptable: false,
    forbidden: false,
    notFound: false,
    charset: 'utf-8',
    type: 'application/json',
    setEncoding: [Function],
    redirects: [] } ]
2015-07-01T18:12:46.280Z - info: Saved repo cache


err param that is logged as error contains that data, I removed some content

**Comment by knownasilya** [comment]
You've followed these instructions? https://github.com/Strider-CD/strider-github#use-custom-hostname-and-port

**Comment by carlitux** [comment]
Yes, I have no issues with authentication... I had but fixed with that
settings.

**Comment by knownasilya** [comment]
All the URLs have a blank access token qp.. Not sure if that's the issue.

**Comment by carlitux** [comment]
@knownasilya fixed on update repository and re running npm install

**Comment by knownasilya** [comment]
Glad that's over ;)
