### ISSUE TITLE
Deleting an account can leave you unable to delete projects

### ISSUE THREAD

**Issue by oliversalzburg** [Strider-CD/strider#825]
1. Register a Gitlab account in strider
2. Create a project from that account
3. Delete the Gitlab account from strider
4. Attempting to delete the project will fail

**Comment by knownasilya** [comment]
@oliversalzburg any errors?

**Comment by oliversalzburg** [comment]
@knownasilya Well, it'll fail to unregister webhooks because it can't retrieve the necessary information from a non-existent account.

Deleting an account should also delete all projects created from it, or it shouldn't be possible until all projects are deleted.

**Comment by knownasilya** [comment]
I like the last method, since it would be too easy to delete all projects..

We can give them a list of projects that use the provider, so they don't have to guess or go sifting through.
