### ISSUE TITLE
Support different release scenarios per branch

### ISSUE THREAD

**Issue by crash7** [Strider-CD/strider#827]
Hi,
Not sure if this is a feature request for strider or more like a strider-plugin. I just started to test the project and look at the code so I can contribute in the future.

I would like to have different deploy scenarios for a particular branch:
- deploy to production
- deploy to staging
- deploy to introduction

It sounds like the "build promotion/delivery pipeline" plugin for jenkins (but I don't want to use jenkins and this project looks promising).

I know that I could do this using different branchs but I don't like that setup (i'm doing this right now using a githook).

Let me know what you think.

Regards,
Chris

**Comment by knownasilya** [comment]
Would love to have you on board, check out https://github.com/Strider-CD/strider/issues/367

**Comment by crash7** [comment]
@knownasilya exactly that! Closing this in favor of feature issue #367 and #522

**Comment by knownasilya** [comment]
Also comments in https://github.com/Strider-CD/strider/issues/736 are related
