### ISSUE TITLE
Where did the cancel job button go? Also the progress bar juts out of its container.

### ISSUE THREAD

**Issue by notbrain** [Strider-CD/strider#829]
![image](https://cloud.githubusercontent.com/assets/67282/8489905/c3663384-20d5-11e5-9f1a-1eaabdeca805.png)

**Comment by notbrain** [comment]
This is on Chrome OSX latest.

**Comment by knownasilya** [comment]
Ah looks like my commit didn't work https://github.com/Strider-CD/strider/commit/76b2bf1ee91dab57d7b606c6d5c4995b6ef070d8 probably need to pass a context to the partial
