### ISSUE TITLE
How to fix perl locale settings on Ubuntu?

### ISSUE THREAD

**Issue by notbrain** [Strider-CD/strider#830]
I have tried a bunch of ubuntu settings and dpkg commands to set the locale appropriately, but strider does not seem to pick them up.

For every build I see this:

![image](https://cloud.githubusercontent.com/assets/67282/8556649/3e8f0420-24ad-11e5-8b99-b1cec0a5c9f7.png)

But when I ask the system (Ubuntu 14 LTS) for locale settings, they are set. Where is strider/perl picking this up from? 

    $ locale
    LANG=en_US.UTF-8
    LANGUAGE=en_US.UTF-8
    LC_CTYPE="en_US.UTF-8"
    LC_NUMERIC="en_US.UTF-8"
    LC_TIME="en_US.UTF-8"
    LC_COLLATE="en_US.UTF-8"
    LC_MONETARY="en_US.UTF-8"
    LC_MESSAGES="en_US.UTF-8"
    LC_PAPER="en_US.UTF-8"
    LC_NAME="en_US.UTF-8"
    LC_ADDRESS="en_US.UTF-8"
    LC_TELEPHONE="en_US.UTF-8"
    LC_MEASUREMENT="en_US.UTF-8"
    LC_IDENTIFICATION="en_US.UTF-8"
    LC_ALL=en_US.UTF-8

Strider is running as the same user I used to call `locale`.

**Comment by knownasilya** [comment]
Try strider-env plugin.

**Comment by notbrain** [comment]
Thanks!

![image](https://cloud.githubusercontent.com/assets/67282/8586098/db125822-259f-11e5-82c5-5df341bf78dd.png)
