### ISSUE TITLE
bug: link to job output always shows currently running job

### ISSUE THREAD

**Issue by phiros** [Strider-CD/strider#833]
I observed this issue several times. If you use the github status plugin you get a link to the status
of your PR job in github. However, if you click on it (for example http://foo.com/foo/job/559fd...) you will end up seeing the status of the currently running job (for example http://foo.com/foo/job/559f1...).

The following screengrab shows what my browser (tested both on current versions of firefox and chrome) renders when I access such a link (it shows a currently running job starting with the id 559fd instead of the finished job starting with the id 559f1 which I expected to see) 

![bug-does-not-open-right-build](https://cloud.githubusercontent.com/assets/16182/8621019/974bda66-2723-11e5-8d1d-7fc6a919d2f2.png)

**Comment by knownasilya** [comment]
@phiros I'm going to add you as a collaborator since you seem to be contributing. Thanks!

**Comment by phiros** [comment]
Ok cool. I will try to fix some of the bugs I reported.

**Comment by knownasilya** [comment]
@phiros can you confirm the fix worked?

**Comment by phiros** [comment]
@knownasilya Sorry for the late answer. I just saw this. 
I haven't updated our old strider installation in quite some time. Will do so when I have a little bit more time.
