### ISSUE TITLE
Repo list on projects page shows duplicate entries for github provider

### ISSUE THREAD

**Issue by saraf** [Strider-CD/strider#846]
If the user is an admin member of a team in an organization,
the repositories in the Project view show duplicate entries.

Screenshot:
![team repos and repos duplicated](https://cloud.githubusercontent.com/assets/117493/9301675/3690cf1e-450b-11e5-8eab-9cf20de75240.PNG)

This is because we are doing a concatenation at the end of lib/api.js
callback(null, repos.concat(team_repos));

The fix is to merge repos and team_repos - do a uniq on the concat of the two. 

Will raise a pull request for this.

**Comment by oliversalzburg** [comment]
But, aren't those actually separate repositories? I would assume one is a fork of the other, aren't they? I'm just surprised that I've never seen this in our environment.

**Comment by saraf** [comment]
They have the same id

**Comment by oliversalzburg** [comment]
Interesting. Thanks for reporting this!

**Comment by saraf** [comment]
Added test case for this, and comment about why it is needed in the source. 
https://github.com/saraf/strider-github/commit/8a4ad9bc6797c9923658a792915a4a9c99989d79
