### ISSUE TITLE
Execute other builds by current build

### ISSUE THREAD

**Issue by mabc224** [Strider-CD/strider#850]
I want to create a way for Strider builds to execute other strider builds.
As far as I know, Strider can only run 1 job at a time. This makes it very difficult for one build to execute another build at same time because it might result in a perpetual state of delay. 
Still, even if that is the case, I should be able to trigger a build on strider by sending the request. So that if one job end it could start another immediately.
Is my assumption true that Strider run 1 build at a time? Is there rest api exist to request to run other build?

_label: Question_

**Comment by knownasilya** [comment]
Have you seen https://github.com/Strider-CD/strider-cli#runtest this could be used with the custom plugin via a bash script.

**Comment by mabc224** [comment]
i give it [https://github.com/Strider-CD/strider-cli#runtest](https://github.com/Strider-CD/strider-cli#runtest) and it works well for initiating a job. Currently it require `strider` file that is in bin directory, to initiate job. How can i over come on this?

I am using it like this in `strider/bin` directory
`node strider runTest -l foo@example.com -p password -j username/repo-name`

I want to run it in program like this.

```
	context.cmd(
		{
			command: "node",
			args: ['strider', 'runTest',
				'-l', params['email'],
				'-p', params['password'],
				'-j', params['project'],
				'-b', params['branch'],
				'-d', params['deploy'],
				'--color=always'],
			screen: 'Adding '+params['project']+ ' in queue for next run'
		}
		, function (err) {
			if (err) {
				context.out('Error: Adding '+params['project']+ ' in queue for next run' + err + '\n', 'error');
				return cb(err);
			}
			context.out('Added '+params['project']+ ' in queue for next run ' + '\n', 'message');
			cb(null, true);

		});```

**Comment by knownasilya** [comment]
So is that not working for you? What errors are you seeing?

**Comment by mabc224** [comment]
It works fine for me if i use it manually by initiating command from `strider/bin` directory.
I wrote new plugin for this functionality to run a next job but it does not work. How can i initiate job from plugin by using above code? 
My case is, I should be able to trigger a build on strider by sending the request. So that if one job end, it could start another immediately.

**Comment by knownasilya** [comment]
for your plugin you have to pass the actual path to the strider bin, so `node /path/to/strider/bin/strider args...`.

**Comment by mabc224** [comment]
i have already solved issue by giving full path. I set up path in env variable and used it.

**Comment by mabc224** [comment]
while running command, i am getting error.

I tested it on my `localhost:3000` and it works well. When i deployed it on `server:8080` and try it. it gives this error. Kindly check this.

```
Login error { [Error: connect ECONNREFUSED]
  code: 'ECONNREFUSED',
  errno: 'ECONNREFUSED',
  syscall: 'connect' } undefined
```

**Comment by knownasilya** [comment]
Because you need to pass a username and password, see https://github.com/Strider-CD/strider-cli/tree/a465e5f22b10259e305ee5e4715eccb2a3dd9e3e#runtest for the user running the test.

**Comment by mabc224** [comment]
i am passing username and password correctly. 
I am using command like this `node strider runTest -l foo@example.com -p password -j username/repo-name -d true`
it runs correctly on `localhost:3000` but on `server:80` it is not working

**Comment by knownasilya** [comment]
Sounds like your server is trying to access it from the outside world, with the url of your strider instance, and it cannot find it from the server. The error happens here: https://github.com/Strider-CD/strider-cli/blob/a465e5f22b10259e305ee5e4715eccb2a3dd9e3e/run.js#L13 see what that url is, and try to ping it from within your server.
