### ISSUE TITLE
Simultaneous Jobs.

### ISSUE THREAD

**Issue by kayoub5** [Strider-CD/strider#858]
According to #667, Simultaneous builds/jobs is not supported yet.
I would like to know what's currently prevents strider CD from supporting that.
Is it the runners, or strider itself?
I am currently writing a runner that run the code in a Google Compute Engine slave VM.
I managed to get it to work for 1 slave, my runner is extending the [simple runner] (https://github.com/Strider-CD/strider-simple-runner), just like the [docker runner](https://github.com/Strider-CD/strider-docker-runner).

**Comment by knownasilya** [comment]
Probably both, but we are focusing efforts to support that with the new API which is being developed under [Strider-CD/core](https://github.com/Strider-CD/core).

Do you have your runner published anywhere?

**Comment by kayoub5** [comment]
is the new API usable/ready?

**Comment by knownasilya** [comment]
No, it's still in prototype mode and we'd love all the help/feedback/ideas we can get.
