### ISSUE TITLE
relative paths for scripts and stylesheets

### ISSUE THREAD

**Issue by lifeispeachy301** [Strider-CD/strider#863]
Hello, 

I am digging into strider for the first time and wondering if Strider is meant to be run under an nginx proxy that isn't the server root. For instance the following config works 

```
location /build/ {
                proxy_set_header Host $host;
                proxy_set_header X-REAL-IP $remote_addr;
                proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;
                proxy_set_header X-Forwarded-Proto $scheme;

                proxy_pass http://localhost:3000/;
        }
```

but none of the javascript or css loads because they are relative to the root and not the path.

Does Strider only work when proxied from the server root? or is there something I can do to get it working with the above config?

**Comment by knownasilya** [comment]
You are correct. Strider only works at the root or a sub-domain.
