### ISSUE TITLE
Is there a way to *not* run npm install by default?

### ISSUE THREAD

**Issue by notbrain** [Strider-CD/strider#871]
I am using custom scripts to install, test, and deploy, but for some reason strider follows the initial clone with `npm install` no matter what, and I can't find where to disable it. Is this possible? I want to avoid running this more than once since my build process already includes a fresh install step.

**Comment by knownasilya** [comment]
Personally I'd take the strider `npm install`, because that is cached, while your custom one isn't.

**Comment by oliversalzburg** [comment]
I also don't see an option to disable it and I agree with @knownasilya here. But I guess, having the option wouldn't hurt either.

**Comment by notbrain** [comment]
I would use the strider one if my build command didn't already have it built in. I'm just trying to reduce the time my builds take. I went looking for how `slc build` (strongloop) calls it to see if I could pass a flag but no dice unless I hack it.

**Comment by bitwit** [comment]
Is removing the Node plugin completely not an option here? I mean, if all you have is 'custom' then you can just write your own prepare,test,deploy steps from scratch. If you're looking for partial functionality from the node plugin, however, I don't think that's possible, as mentioned above.

**Comment by notbrain** [comment]
@bitwit Ah, interesting, maybe that will work, I will give it a try. Thanks.

**Comment by notbrain** [comment]
Uninstalling the Node plugin works for this, thanks again @bitwit
