### ISSUE TITLE
Heroku: 400 on socket.io

### ISSUE THREAD

**Issue by tbouron** [Strider-CD/strider#872]
So I have upgraded my Strider, deployed on Heroku to the latest version `1.7.5` and I notice that XHR requests to socket.io fail, both in `http` or `https`.

![capture d ecran 2015-10-23 a 06 07 23](https://cloud.githubusercontent.com/assets/2082759/10685038/8b53b82a-794c-11e5-97fd-32d573b5de18.png)

 Here is the response I got:

    {"code":0,"message":"Transport unknown"}

**Comment by oliversalzburg** [comment]
So it worked before the upgrade? If so, what version were you running? Did you also upgrade other packages?

**Comment by tbouron** [comment]
@oliversalzburg Yes, it worked before, I was using the version `1.6.0-pre.2`. I know, that is pretty old but it suited my needs so far.

Then came the mongolab update to 3.0 and Strider became unable to connect to the db anymore. That's why I did the upgrade to the latest version of Strider. The version deployed is exactly the same as what is tag within the git repo. I didn't upgrade any other package but I did add my [Strider plugin](https://github.com/tbouron/strider-artifact-repository) into `package.json`

**Comment by oliversalzburg** [comment]
I'm not sure about all the things that changed since 1.6.0, but my initial reaction was, that this could be related to an improper reverse-proxy setup. 1.6.0 probably used an older socket.io version, which might have had fallback mechanisms which are no longer supported.

I know that we have to configure the `/socket.io` route specifically in our nginx setup for it to work right.

Does that sounds possible?

**Comment by tbouron** [comment]
@oliversalzburg Humm that's possible indeed but I don't have control over any reverse-proxy on Heroku. I also don't remember doing anything about that in a past.

Do you have any other idea to fix the issue?

In a meantime, I'll try to deploy Strider `1.7.5` from scratch on Heroku and see if I can reproduce the error. If I cannot and you don't have any other solution, I will migrate my db to the new instance.

**Comment by oliversalzburg** [comment]
Maybe someone else with Heroku experience can contribute something. Because I don't really have any :)

**Comment by tbouron** [comment]
Just so you know, I got the same result with a fresh install from the [Heroku deploy button](https://github.com/Strider-CD/strider#strider-on-heroku).

**Comment by tbouron** [comment]
Hi there. Has anybody had the chance to look into that?

**Comment by duller999** [comment]
Seems to be that the client doesn't use xhr-polling, I just removed this statement and everything works fine. Line 53 of /lib/websockets.js

`  if (everypaas.isHeroku()) {
    sio.set("transports", ["xhr-polling"]);
    sio.set("polling duration", 10);
  }`

**Comment by tbouron** [comment]
Hi @duller999. You're right, I just tested it and it works! Heroku must have changed something here as I tried that few months back and failed miserably.

Anyway, thanks for that, I'll open a PR :)
