### ISSUE TITLE
SSH deploy with multiple users

### ISSUE THREAD

**Issue by srh-work** [Strider-CD/strider#873]
Hi.

I wondering if it's possible to deploy in multiple hosts with different usernames. 
```
ssh user1@host1.org:22
ssh user2@host2.org:22
...
```
The SSH deploy plugin allows me to use multiple hosts but with the same username.

Please forgive me if this is a dumb question and I only need to set up better. I am new to using Strider.

Thank you.

**Comment by oliversalzburg** [comment]
I don't think this is possible right now. You might be able to do it with a custom script though.

**Comment by knownasilya** [comment]
Sounds like a feature request for the ssh-deploy plugin. Could you submit there? Thanks!

**Comment by knownasilya** [comment]
Closing for the issue in ssh deploy repo.
