### ISSUE TITLE
node 4.x npm install failed

### ISSUE THREAD

**Issue by terminatorheart** [Strider-CD/strider#881]
node version 4.2.1 

When I run `npm install`, I get some message as follow:
```
make: *** [Release/obj.target/contextify/src/contextify.o] Error 1
make: Leaving directory `/home/****/strider/node_modules/angular/node_modules/jsdom/node_modules/contextify/build'
npm ERR! contextify@0.1.14 install: `node-gyp rebuild`
npm ERR! Exit status 1
npm ERR! 
npm ERR! Failed at the contextify@0.1.14 install script 'node-gyp rebuild'.
npm ERR! This is most likely a problem with the contextify package,
npm ERR! not with npm itself.
npm ERR! Tell the author that this fails on your system:
npm ERR!     node-gyp rebuild
npm ERR! You can get their info via:
npm ERR!     npm owner ls contextify
npm ERR! There is likely additional logging output above.
```

as i find that the problem is in contextify, and it should be dependencied by jsdom module, when i went to jsdom folder, find no contextify in package.json file, and as jsdom dependencied by angular, i went to angular folder , here i find that angular and angular-route version is 1.2.7, so i tried to change it to version  1.4.3, which i was used for a long time, and do npm install again, then there comes the miracle, it worked! i did't know if i have down right thing, may be somebody have the same issuse, hope be help

**Comment by oliversalzburg** [comment]
Seems like you didn't include the actual error message

**Comment by terminatorheart** [comment]
i suppose you need this :

167489 info postinstall browserify@11.2.0
167490 verbose unlock done using /home/***/.npm/_locks/browserify-4f3cbcd86c83bd81.lock for /home/***/tmp/strider/node_modules/browserify
167491 verbose stack Error: contextify@0.1.14 install: `node-gyp rebuild`
167491 verbose stack Exit status 1
167491 verbose stack     at EventEmitter.<anonymous> (/usr/local/node/lib/node_modules/npm/lib/utils/lifecycle.js:214:16)
167491 verbose stack     at emitTwo (events.js:87:13)
167491 verbose stack     at EventEmitter.emit (events.js:172:7)
167491 verbose stack     at ChildProcess.<anonymous> (/usr/local/node/lib/node_modules/npm/lib/utils/spawn.js:24:14)
167491 verbose stack     at emitTwo (events.js:87:13)
167491 verbose stack     at ChildProcess.emit (events.js:172:7)
167491 verbose stack     at maybeClose (internal/child_process.js:818:16)
167491 verbose stack     at Process.ChildProcess._handle.onexit (internal/child_process.js:211:5)
167492 verbose pkgid contextify@0.1.14
167493 verbose cwd /home/***/tmp/strider
167494 error Linux 3.10.0-229.el7.x86_64
167495 error argv "/usr/local/node/bin/node" "/usr/local/node/bin/npm" "install"
167496 error node v4.2.1
167497 error npm  v2.14.7
167498 error code ELIFECYCLE
167499 error contextify@0.1.14 install: `node-gyp rebuild`
167499 error Exit status 1
167500 error Failed at the contextify@0.1.14 install script 'node-gyp rebuild'.
167500 error This is most likely a problem with the contextify package,
167500 error not with npm itself.
167500 error Tell the author that this fails on your system:
167500 error     node-gyp rebuild
167500 error You can get their info via:
167500 error     npm owner ls contextify
167500 error There is likely additional logging output above.
167501 verbose exit [ 1, true ]
167502 verbose unbuild node_modules/angular/node_modules/jsdom/node_modules/contextify
167503 info preuninstall contextify@0.1.14
167504 info uninstall contextify@0.1.14
167505 verbose unbuild rmStuff contextify@0.1.14 from /home/***/tmp/strider/node_modules
167506 verbose unbuild rmStuff in /home/***/tmp/strider/node_modules/angular/node_modules/jsdom/node_modules
167507 info postuninstall contextify@0.1.14
167508 silly gentlyRm /home/***/tmp/strider/node_modules/angular/node_modules/jsdom/node_modules/contextify is being purged from base /home/***/tmp/strider
167509 verbose gentlyRm don't care about contents; nuking /home/***/tmp/strider/node_modules/angular/node_modules/jsdom/node_modules/contextify
167510 silly vacuum-fs purging /home/***/tmp/strider/node_modules/angular/node_modules/jsdom/node_modules/contextify
167511 silly vacuum-fs quitting because other entries in /home/***/tmp/strider/node_modules/angular/node_modules/jsdom/node_modules
167512 verbose unbuild node_modules/angular/node_modules/jsdom
167513 info preuninstall jsdom@0.8.11
167514 info uninstall jsdom@0.8.11
167515 verbose unbuild rmStuff jsdom@0.8.11 from /home/***/tmp/strider/node_modules
167516 verbose unbuild rmStuff in /home/***/tmp/strider/node_modules/angular/node_modules
167517 info postuninstall jsdom@0.8.11
167518 silly gentlyRm /home/***/tmp/strider/node_modules/angular/node_modules/jsdom is being purged from base /home/***/tmp/strider
167519 verbose gentlyRm don't care about contents; nuking /home/***/tmp/strider/node_modules/angular/node_modules/jsdom
167520 silly vacuum-fs purging /home/***/tmp/strider/node_modules/angular/node_modules/jsdom
167521 silly vacuum-fs removing /home/***/tmp/strider/node_modules/angular/node_modules
167522 silly vacuum-fs quitting because other entries in /home/***/tmp/strider/node_modules/angular
167523 verbose unbuild node_modules/angular
167524 info preuninstall angular@1.2.23
167525 info uninstall angular@1.2.23
167526 verbose unbuild rmStuff angular@1.2.23 from /home/***/tmp/strider/node_modules
167527 info postuninstall angular@1.2.23
167528 silly gentlyRm /home/***/tmp/strider/node_modules/angular is being purged from base /home/***/tmp/strider
167529 verbose gentlyRm don't care about contents; nuking /home/***/tmp/strider/node_modules/angular
167530 silly vacuum-fs purging /home/***/tmp/strider/node_modules/angular
167531 silly vacuum-fs quitting because other entries in /home/***/tmp/strider/node_modules

**Comment by oliversalzburg** [comment]
@terminatorheart https://guides.github.com/features/mastering-markdown/

**Comment by terminatorheart** [comment]
sorry for that,i will write more clearly later

**Comment by knownasilya** [comment]
@terminatorheart try deleting `/home/***/.npm` and reinstalling.

**Comment by rimmartin** [comment]
The greater change I'm finding is between v4.2.x and <=v4.1.x where node Buffer is involved.  Buffer has went through a complete rewrite and is now based on Uint8Array [on native side there is no difference] https://github.com/nodejs/node/issues/3419

I bumped angular from 1.2.23 to 1.4.7 to install strider.  Also angular-route to 1.4.7.

After that I could build and start strider

**Comment by knownasilya** [comment]
What does angular and angular-router have to do with the Buffer?

**Comment by rimmartin** [comment]
There is some native dependency under it jsdom -> contextify
```bash
npm WARN deprecated swig@0.14.0: v1.0.0 is a complete rewrite of Swig from the ground up. Previous versions are no longer supported
npm WARN engine global-tunnel@1.2.0: wanted: {"node":"0.10.x"} (current: {"node":"4.2.1","npm":"2.14.7"})
npm WARN optional dep failed, continuing fsevents@1.0.2
npm WARN optional dep failed, continuing fsevents@0.3.0
npm WARN engine hawk@0.10.2: wanted: {"node":"0.8.x"} (current: {"node":"4.2.1","npm":"2.14.7"})
npm WARN engine boom@0.3.8: wanted: {"node":"0.8.x"} (current: {"node":"4.2.1","npm":"2.14.7"})
npm WARN engine cryptiles@0.1.3: wanted: {"node":"0.8.x"} (current: {"node":"4.2.1","npm":"2.14.7"})
npm WARN engine hoek@0.7.6: wanted: {"node":"0.8.x"} (current: {"node":"4.2.1","npm":"2.14.7"})
npm WARN engine sntp@0.1.4: wanted: {"node":"0.8.x"} (current: {"node":"4.2.1","npm":"2.14.7"})
 
> contextify@0.1.14 install /home/roger/NodeProjects/stridertest/strider/node_modules/angular/node_modules/jsdom/node_modules/contextify
> node-gyp rebuild

make: Entering directory `/home/roger/NodeProjects/stridertest/strider/node_modules/angular/node_modules/jsdom/node_modules/contextify/build'
  CXX(target) Release/obj.target/contextify/src/contextify.o
In file included from ../src/contextify.cc:3:0:
../node_modules/nan/nan.h:261:25: error: redefinition of ‘template<class T> v8::Local<T> _NanEnsureLocal(v8::Local<T>)’
 NAN_INLINE v8::Local<T> _NanEnsureLocal(v8::Local<T> val) {
                         ^
../node_modules/nan/nan.h:256:25: note: ‘template<class T> v8::Local<T> _NanEnsureLocal(v8::Handle<T>)’ previously declared here
 NAN_INLINE v8::Local<T> _NanEnsureLocal(v8::Handle<T> val) {
                         ^
../node_modules/nan/nan.h:661:13: error: ‘node::smalloc’ has not been declared
     , node::smalloc::FreeCallback callback
             ^
../node_modules/nan/nan.h:661:35: error: expected ‘,’ or ‘...’ before ‘callback’
     , node::smalloc::FreeCallback callback
                                   ^
../node_modules/nan/nan.h: In function ‘v8::Local<v8::Object> NanNewBufferHandle(char*, size_t, int)’:
../node_modules/nan/nan.h:665:50: error: ‘callback’ was not declared in this scope
         v8::Isolate::GetCurrent(), data, length, callback, hint);
                                                  ^
../node_modules/nan/nan.h:665:60: error: ‘hint’ was not declared in this scope
         v8::Isolate::GetCurrent(), data, length, callback, hint);
                                                            ^
../node_modules/nan/nan.h: In function ‘v8::Local<v8::Object> NanNewBufferHandle(const char*, uint32_t)’:
../node_modules/nan/nan.h:672:67: error: no matching function for call to ‘New(v8::Isolate*, const char*&, uint32_t&)’
     return node::Buffer::New(v8::Isolate::GetCurrent(), data, size);
                                                                   ^
In file included from ../node_modules/nan/nan.h:25:0,
                 from ../src/contextify.cc:3:
/home/roger/.node-gyp/4.2.1/include/node/node_buffer.h:31:40: note: candidate: v8::MaybeLocal<v8::Object> node::Buffer::New(v8::Isolate*, v8::Local<v8::String>, node::encoding) <near match>
 NODE_EXTERN v8::MaybeLocal<v8::Object> New(v8::Isolate* isolate,
                                        ^
/home/roger/.node-gyp/4.2.1/include/node/node_buffer.h:31:40: note:   conversion of argument 3 would be ill-formed:
In file included from ../src/contextify.cc:3:0:
../node_modules/nan/nan.h:672:67: error: invalid conversion from ‘uint32_t {aka unsigned int}’ to ‘node::encoding’ [-fpermissive]
     return node::Buffer::New(v8::Isolate::GetCurrent(), data, size);
                                                                   ^
In file included from ../node_modules/nan/nan.h:25:0,
                 from ../src/contextify.cc:3:
/home/roger/.node-gyp/4.2.1/include/node/node_buffer.h:43:40: note: candidate: v8::MaybeLocal<v8::Object> node::Buffer::New(v8::Isolate*, char*, size_t) <near match>
 NODE_EXTERN v8::MaybeLocal<v8::Object> New(v8::Isolate* isolate,
                                        ^
/home/roger/.node-gyp/4.2.1/include/node/node_buffer.h:43:40: note:   conversion of argument 2 would be ill-formed:
In file included from ../src/contextify.cc:3:0:
../node_modules/nan/nan.h:672:67: error: invalid conversion from ‘const char*’ to ‘char*’ [-fpermissive]
     return node::Buffer::New(v8::Isolate::GetCurrent(), data, size);
                                                                   ^
../node_modules/nan/nan.h: In function ‘v8::Local<v8::Object> NanNewBufferHandle(uint32_t)’:
../node_modules/nan/nan.h:676:29: error: could not convert ‘node::Buffer::New(v8::Isolate::GetCurrent(), ((size_t)size))’ from ‘v8::MaybeLocal<v8::Object>’ to ‘v8::Local<v8::Object>’
     return node::Buffer::New(v8::Isolate::GetCurrent(), size);
                             ^
../node_modules/nan/nan.h: In function ‘v8::Local<v8::Object> NanBufferUse(char*, uint32_t)’:
../node_modules/nan/nan.h:683:12: error: ‘Use’ is not a member of ‘node::Buffer’
     return node::Buffer::Use(v8::Isolate::GetCurrent(), data, size);
            ^
make: *** [Release/obj.target/contextify/src/contextify.o] Error 1
make: Leaving directory `/home/roger/NodeProjects/stridertest/strider/node_modules/angular/node_modules/jsdom/node_modules/contextify/build'
gyp ERR! build error 
gyp ERR! stack Error: `make` failed with exit code: 2
gyp ERR! stack     at ChildProcess.onExit (/home/roger/Software/node-v4.2.1/dist/lib/node_modules/npm/node_modules/node-gyp/lib/build.js:270:23)
gyp ERR! stack     at emitTwo (events.js:87:13)
gyp ERR! stack     at ChildProcess.emit (events.js:172:7)
gyp ERR! stack     at Process.ChildProcess._handle.onexit (internal/child_process.js:200:12)
gyp ERR! System Linux 3.13.0-66-generic
gyp ERR! command "/home/roger/Software/node-v4.2.1/dist/bin/node" "/home/roger/Software/node-v4.2.1/dist/lib/node_modules/npm/node_modules/node-gyp/bin/node-gyp.js" "rebuild"
gyp ERR! cwd /home/roger/NodeProjects/stridertest/strider/node_modules/angular/node_modules/jsdom/node_modules/contextify
gyp ERR! node -v v4.2.1
gyp ERR! node-gyp -v v3.0.3
gyp ERR! not ok 
 
```
The 1.4.7 doesn't seem to have near the dependencies.

**Comment by rimmartin** [comment]
npm outdated yields up:
```npm
Package                      Current              Wanted  Latest  Location
angular                      MISSING              1.2.23   1.4.7  angular
angular-route     1.2.17-build.163.1  1.2.17-build.163.1   1.4.7  angular-route
babelify                       6.4.0               6.4.0   7.1.0  babelify
bluebird                      2.10.2              2.10.2   3.0.2  bluebird
browserify                    11.2.0              11.2.0  12.0.1  browserify
chai                          1.10.0              1.10.0   3.4.0  chai
chai-as-promised               4.3.0               4.3.0   5.1.0  chai-as-promised
cookie                         0.1.5               0.1.5   0.2.3  cookie
everypaas                      0.0.7                 git     git  everypaas
extend                         2.0.1               2.0.1   3.0.0  extend
jade                          0.35.0              0.35.0  1.11.0  jade
mocha                         1.21.5              1.21.5   2.3.3  mocha
mongoose                      3.8.36              3.8.36   4.2.3  mongoose
nodemailer                     0.6.5               0.6.5   1.8.0  nodemailer
passport                       0.2.2               0.2.2   0.3.0  passport
semver                         4.3.6               4.3.6   5.0.3  semver
should                         2.1.1               2.1.1   7.1.1  should
step                           0.0.5               0.0.5   0.0.6  step
swig                          0.14.0              0.14.0   1.4.2  swig
validator                     3.43.0              3.43.0   4.2.1  validator
winston                        1.1.2               1.1.2   2.0.0  winston
```

**Comment by knownasilya** [comment]
I remember that angular wasn't updated for some reason, like another dependency like angular-ui or something not cooperating. Is that no longer the case? Does everything seem to work?

**Comment by rimmartin** [comment]
I've setup an admin account, activated more plugins such as ones for mercurial, docker and artifact repository.  Added custom github project and it tested.  Haven't deployed.  This is the extent of my testing.  I was learning about making a plugin

**Comment by rimmartin** [comment]
angular's runtime dependencies are now none https://www.npmjs.com/package/angular.  They say for nodejs ~v0.10; my only strider test is with v4.2.1

**Comment by knownasilya** [comment]
Ah, so they actually have it exporting correctly now so no shim is required. Ok, I'll test it out, but really node version shouldn't matter so much, since it's browserified and run in the browser, it's probably an npm version issue.

**Comment by terminatorheart** [comment]
@knownasilya sorry for wait so long, before i install  strider, i have tried change global npm install position to /home/***/.npm , so the folder /home/***/.npm is completely cleaned

**Comment by knownasilya** [comment]
@terminatorheart what's the issue now?

**Comment by terminatorheart** [comment]
@knownasilya works fine now, still don't know why can't install with angular 1.2.3
