### ISSUE TITLE
startTest & start Deploy from script

### ISSUE THREAD

**Issue by rimmartin** [Strider-CD/strider#890]
Hi

I see in https://github.com/Strider-CD/strider/blob/master/lib/views/partials/_dashboard_row.html#L22 the mechanism to startDeploy with ng-click="startDeploy(job)" attribute on an html span.  I would like to do it from 
```javascript
 cy.on('cxttap', 'node', function(evt){
  //console.log( "hey!" ); // 'bar'

  var node = evt.cyTarget;
  node.animate({
      style: { backgroundColor: 'red' }
    }, {
      duration: 1000
    });
//kick a manual test of project and DAG tree algorithm if successful
 ???   startTest(node.data('job'));
});                
```
Trying to get familiar with the code and dependent technologies.
I see $scope.startTest = function (job) at https://github.com/Strider-CD/strider/blob/master/client/dashboard/controllers/dashboard.js#L24
but not finding how to trigger from script code. Howto?

**Comment by knownasilya** [comment]
If you have access to `$scope`, then you can do `$scope.startTest(job)`

**Comment by rimmartin** [comment]
Thank you
