### ISSUE TITLE
Multiple deploy based on branch

### ISSUE THREAD

**Issue by kauegimenes** [Strider-CD/strider#897]
Currently, it's possible to make different deploy tasks in the same machine depending on the branch?

**Comment by knownasilya** [comment]
See https://github.com/Strider-CD/strider/issues/367

**Comment by kauegimenes** [comment]
thanks @knownasilya !

In the current version, its possible to duplicate a project, so i can have a different deploy task for each branch of the same repo?

**Comment by knownasilya** [comment]
Also a requested feature, see https://github.com/Strider-CD/strider/issues/876, one of the users duplicates the record in the DB I think.

**Comment by knownasilya** [comment]
Closing this since multiple issues address the question you had.
