### ISSUE TITLE
The watch doesn't work,auto test and deploy don't work.

### ISSUE THREAD

**Issue by smancang** [Strider-CD/strider#904]
The active option is checked,and the branch of master ranks the first ,but when I push a change to the git,the site doesn't deploy or test automatically. It only can be triggered manually.There's no error or any warnings.

**Comment by oliversalzburg** [comment]
What provider are you using?

**Comment by smancang** [comment]
I use a GitLab built.Does it mean that strider doesn't support GitLab?

**Comment by oliversalzburg** [comment]
No, that should work just fine. We have the same setup. Maybe something went wrong with the webhook creation.

You could check the Web Hooks section in your project settings on your GitLab and see if Strider was able to create a hook.

**Comment by smancang** [comment]
Oh,I don't set any web hook.I even don't know it should be done.
I find the place of setting web hook on my GitLab, but I don't know what url should I write.Just "http://IP:Port" of my strider website or I should add other path.

**Comment by oliversalzburg** [comment]
Usually, Strider would automatically create the web hook for you. Creating it manually is not really a viable option.

Could you try re-creating the project in Strider and check the log for anything interesting?

**Comment by smancang** [comment]
I've re-created it.The log is normal via manually trigger,but it can't be triggered automatically.And I find this site https://futurestud.io/blog/strider-how-to-connect-with-gitlab-and-run-tests-automatically,but it doesn't work.

**Comment by knownasilya** [comment]
@smancang so both your gitlab has a localhost address and your strider instance?

**Comment by smancang** [comment]
@knownasilya  yeah,that's right.

**Comment by knownasilya** [comment]
@smancang did you have any luck figuring out what the issue was?

**Comment by knownasilya** [comment]
Can reopen if need be.
