### ISSUE TITLE
Prevent plugins from crashing strider instance

### ISSUE THREAD

**Issue by bariscicek** [Strider-CD/strider#907]
Custom scripts plugin allowing injection of javascript using ejs. When there is an evaluation problem in these scripts, like undefined variables etc, it crashes strider instance. 

Although problem might be related with strider-custom not properly handling errors, plugins should not be able to crash strider instances.

**Comment by knownasilya** [comment]
Would love a PR that isolates plugins into separate processes, but I don't have that kind of bandwidth myself. I would assume you are right though, that there is a bug in strider-custom.

**Comment by knownasilya** [comment]
v0.6.1 of strider-custom should fix the issue, but I'll leave this issue open.

**Comment by knownasilya** [comment]
Closing this, since I don't see any ejs parsing in strider itself, or the extension loader.
