### ISSUE TITLE
Ruby plugin fails to install dependencies

### ISSUE THREAD

**Issue by mastertinner** [Strider-CD/strider#916]
I'm not sure if the Ruby plugin is still maintained since it doesn't have Github's "issues" feature activated. That's why I'm trying it here.

I'm using `strider 1.7.7` and `strider-ruby 0.0.5` and set the "Prepare Command" to `bundle install --binstubs`. When starting, Strider stops at this install command and the build turns red without any error message. Here's the history:

```shell
$ git clone --recursive https://[username]:[password]@github.com/swisscom/docs-appcloud-book.git . --branch master github 2.2s
Cloning into '.'...
$ git checkout --quiet --force e4f5a36f8cc4efbf448ad2f2981d0314cda28f7c github 19ms
$ sh -x -c 'bundle install --binstubs' ruby 13ms
```

**Comment by knownasilya** [comment]
Looks like issues is available in strider-ruby in this org. I think it just means few people use it, or it just works. Probably the later, lol.

**Comment by mastertinner** [comment]
Aaah damn... I was looking at a fork... Thanks for clarifying, @knownasilya!
