### ISSUE TITLE
Sandbox Mode

### ISSUE THREAD

**Issue by webmechanicx** [Strider-CD/strider#917]
Is there any sandbox for guest user?

**Comment by knownasilya** [comment]
No. Haven't heard of this idea. Could you explain what a sandbox would provide?

**Comment by webmechanicx** [comment]
Actually, I was looking for a Live Test anywhere. As I found some screenshots for the dashboard.

**Comment by knownasilya** [comment]
I don't know of one. Best bet is to clone and install locally.

**Comment by webmechanicx** [comment]
Ok thanks.
