### ISSUE TITLE
Strange npm install bug

### ISSUE THREAD

**Issue by scottbert** [Strider-CD/strider#921]
I just imported a project from gitlab. This project was configured and running normally outside of gitlab.
Tried bumping the internal npm to the latest 2.x but that didn't help either.
Honestly not sure what's going on. Project fails at npm install, seems unable to read a file it already downloaded. Checking the working directory, the file is not present (the file without the datestamp at the end is though). Any ideas what could be causing it?

Log below:

``` bash
 environment
$ n latest node 2.2s
 prepare 254
$ git clone --recursive git@gitlab.03sq.net:03sq/freakcity.git . --branch master gitlab 9s 254
Cloning into '.'...
$ git checkout --quiet --force master gitlab 286ms 254
$ npm install node 4.1s 254
npm ERR! Linux 4.4.4-301.fc23.x86_64
npm ERR! argv "/home/node/strider/.n/bin/node" "/usr/lib/node_modules/strider/node_modules/strider-node/node_modules/.bin/npm" "install" "--color=always"
npm ERR! node v5.9.0
npm ERR! npm  v2.15.0
npm ERR! path /home/node/strider/data/03sq-freakcity-56ea49d2f8f1ba3f5568953a/undefined/.npm/registry.npmjs.org/browserify/.cache.json.115795511
npm ERR! code ENOENT
npm ERR! errno -2
npm ERR! syscall lstat

npm ERR! enoent ENOENT: no such file or directory, lstat '/home/node/strider/data/03sq-freakcity-56ea49d2f8f1ba3f5568953a/undefined/.npm/registry.npmjs.org/browserify/.cache.json.115795511'
npm ERR! enoent This is most likely not a problem with npm itself
npm ERR! enoent and is related to npm not being able to find a file.
npm ERR! enoent 

npm ERR! Please include the following file with any support request:
npm ERR!     /home/node/strider/data/03sq-freakcity-56ea49d2f8f1ba3f5568953a/npm-debug.log
 cleanup
$ n prev node 1.6s

    activate : node/5.3.0
```

**Comment by knownasilya** [comment]
Have you tried deleting the contents of `/home/node/strider/data`?

**Comment by scottbert** [comment]
yes. If I remove the node plugin then just build using custom scripts it’s fine, but only if I specify
```
npm config set cache /home/node/.npm/cache
```
the line above the npm install.
IF I leave that line out, it’s the same issue. Is something inside strider overriding where npm keeps its cache?

**Comment by knownasilya** [comment]
No, it would be wherever `n` keeps the cache. Sounds like a permissions issue.

**Comment by scottbert** [comment]
Definitely not a permissions issue.
```
/home/node/strider/data/03sq-freakcity-
56ea49d2f8f1ba3f5568953a/undefined/.npm/registry.npmjs.org/browserify/.cache.json.115795511 
```
doesn’t exist
```
/home/node/strider/data/03sq-freakcity-
56ea49d2f8f1ba3f5568953a/undefined/.npm/registry.npmjs.org/browserify/.cache.json
```
does. Also these files are written in the npm install.

**Comment by knownasilya** [comment]
IF you put a debug statement here https://github.com/Strider-CD/strider-node/blob/master/worker.js#L94, what does `ret.path` look like?
