### ISSUE TITLE
[Question] deploy the application to the same server that hosts the strider

### ISSUE THREAD

**Issue by tuananhtd** [Strider-CD/strider#925]
I wish to host the strider and my application in the same dev server. How should I write the deploy script in this case?
Thanks!

**Comment by knownasilya** [comment]
That depends on how you plan on deploying. By default the custom plugin runs bash commands in the directory where the project is cloned, so you don't have to do much.

**Comment by tuananhtd** [comment]
Thank @knownasilya for the nice script!
It shame on me that I used the **SSH plugin** and didn't notice the **Custom Scripts** until now lol.

**Comment by knownasilya** [comment]
Glad I could help.
