### ISSUE TITLE
How to do concurrent Jobs in different machines? [question]

### ISSUE THREAD

**Issue by qballer** [Strider-CD/strider#926]
Is there a way to to orchestrate concurrent jobs on multiple boxes ?

**Comment by knownasilya** [comment]
Not at the moment. See Strider-CD/core for ongoing development of a future build system.

**Comment by qballer** [comment]
Not at the moment meaning it is the plane ?  :)

How do you treat an instance of tests running. Do you have some kind of concept of an agent?

**Comment by knownasilya** [comment]
Yes we call them Drones: https://github.com/Strider-CD/drone
