### ISSUE TITLE
AWS CodeDeploy plugin

### ISSUE THREAD

**Issue by flxbe** [Strider-CD/strider#927]
Hi guys,

I wrote a plugin to integrate AWS CodeDeploy. It works fine for me so far and so I uploaded it. It might be useful for someone else as well: https://github.com/flxbe/strider-aws-codedeploy

Anyway, any advice or feedback is highly appreciated.

**Comment by knownasilya** [comment]
That looks beautiful! Great job.

I'm going to add this to the list of plugins in the wiki.

**Comment by knownasilya** [comment]
Feel free to submit a PR here https://github.com/Strider-CD/ecosystem-index/blob/master/plugins.yml to add to the plugin index.

**Comment by flxbe** [comment]
Alright, I will add the plugin.

Thank you!
