### ISSUE TITLE
Enable Greenkeeper

### ISSUE THREAD

**Issue by mastertinner** [Strider-CD/strider#928]
What do you guys think of enabling [Greenkeeper](https://greenkeeper.io) for all the repos in the Strider ecosystem? It would ensure that all of our dependencies are always up to date.

**Comment by oliversalzburg** [comment]
In general, I like the idea. But without proper CI, it seems less useful. Could be worth a shot though. Maybe roll it out to one or two repos to see how it works?

**Comment by mastertinner** [comment]
good point. we could enable it for some smaller repos at first and combine it with [Travis](https://travis-ci.org/).

**Comment by knownasilya** [comment]
Sounds good. We use travis on the Strider repo, and a couple others. Any repos you think might benefit from being first?

**Comment by mastertinner** [comment]
We could start with some smaller repo like https://github.com/Strider-CD/strider-gitlab. But to me it doesn't really matter where we start. There's also not that much of a risk since all it does is create a PR.

**Comment by knownasilya** [comment]
Only thing I don't want to do is enable for a repo, like the main Strider repo, where we know a good amount of the dependencies are behind (mainly because there are many breaking changes in the current major version).

**Comment by knownasilya** [comment]
First greenkeeper PR https://github.com/Strider-CD/strider-gitlab/pull/50 now to fix the tests..

**Comment by knownasilya** [comment]
@mastertinner we can add you as a contributor if you'd like.

**Comment by mastertinner** [comment]
that would be great. i'll enable Greenkeeper as soon as you have added me :)

**Comment by knownasilya** [comment]
https://github.com/Strider-CD/strider/issues/928#issuecomment-212899437

**Comment by mastertinner** [comment]
@knownasilya, thanks for enabling Greenkeeper and thanks for inviting me!
