### ISSUE TITLE
Errors installing strider

### ISSUE THREAD

**Issue by rohanoberoicornell** [Strider-CD/strider#937]
On CentOS, using npm version 2.15.6 (latest 2.x) and dependencies installed:

[root@instance-2 ~]# npm install -g strider
npm WARN deprecated jade@0.35.0: Jade has been renamed to pug, please install the latest version of pug instead of jade
npm WARN deprecated swig@0.14.0: v1.0.0 is a complete rewrite of Swig from the ground up. Previous versions are no longer suppor
ted
npm WARN engine global-tunnel@1.2.0: wanted: {"node":"0.10.x"} (current: {"node":"6.2.0","npm":"2.15.6"})
npm WARN deprecated lodash@1.3.1: lodash@<3.0.0 is no longer maintained. Upgrade to lodash@^4.0.0.
npm WARN deprecated lodash@2.2.1: lodash@<3.0.0 is no longer maintained. Upgrade to lodash@^4.0.0.
npm WARN deprecated transformers@2.1.0: Deprecated, use jstransformer
npm WARN optional dep failed, continuing fsevents@0.3.0
npm WARN engine hawk@0.10.2: wanted: {"node":"0.8.x"} (current: {"node":"6.2.0","npm":"2.15.6"})
Killed

On Debian, the same install hangs with the following messages:

root@instance-1:~# npm install -g strider
npm WARN deprecated jade@0.35.0: Jade has been renamed to pug, please install the latest version of pug instead of jade
npm WARN deprecated swig@0.14.0: v1.0.0 is a complete rewrite of Swig from the ground up. Previous versions are no longer supported
npm WARN engine global-tunnel@1.2.0: wanted: {"node":"0.10.x"} (current: {"node":"6.2.0","npm":"2.15.6"})
npm WARN deprecated lodash@1.3.1: lodash@<3.0.0 is no longer maintained. Upgrade to lodash@^4.0.0.
npm WARN deprecated lodash@2.2.1: lodash@<3.0.0 is no longer maintained. Upgrade to lodash@^4.0.0.
npm WARN deprecated transformers@2.1.0: Deprecated, use jstransformer
npm WARN optional dep failed, continuing fsevents@0.3.0
npm WARN engine hawk@0.10.2: wanted: {"node":"0.8.x"} (current: {"node":"6.2.0","npm":"2.15.6"})
npm WARN deprecated graceful-fs@1.2.3: graceful-fs v3.0.0 and before will fail on node releases >= v7.0. Please update to graceful-fs@^4.0.0 as soon as possible. Use 'npm ls graceful-fs' to find it in the tree.

Is the Strider project under active development?

**Comment by knownasilya** [comment]
Sounds like an npm issue. You can ignore the `graceful-fs` warning, since node 7 isn't even out yet and we don't officially support it.

**Comment by rohanoberoicornell** [comment]
Thanks.  Is there any version of npm that is known to work with the current version of Strider?

**Comment by knownasilya** [comment]
2+ should work just fine, as your CentOS proves (I use 2.14.12 on OSX and 2.15.1 on Ubuntu). Seems like a bug with npm on Debian.

**Comment by xgalen** [comment]
When running strider I am having a similar issue:
`2016-06-14T09:47:13.600Z - info: failed to load plugin simple-runner Cannot find module 'graceful-fs' Error: Cannot find module 'graceful-fs'
2016-06-14T09:47:13.602Z - error: { [Error: Cannot find module 'graceful-fs'; error loading plugin simple-runner] code: 'MODULE_NOT_FOUND' }
2016-06-14T09:47:13.602Z - error: Failed to load plugins`

I have reinstalled all npm packages with npm v2.15.1 and v3.9.5. It fails with the same error.

**Comment by xgalen** [comment]
My problem is when doing `npm install`, the version of `fs-extra` (strider-simple-runner) is: `"fs-extra": "~0.8.1"`.
When installing via `dev.sh` the version is `0.29.0` and `0.30.0` is required.

**Comment by knownasilya** [comment]
I've updated the version in simple-runner, will release that today.

**Comment by xgalen** [comment]
Ah ok! Thanks :D

**Comment by knownasilya** [comment]
Ok, it should be fixed. I bumped the version for simple-runner in this repo as well.

**Comment by xgalen** [comment]
It works for `npm install`. I suppose when you release simple-runner will work with `dev.sh` too.
Thanks again!

**Comment by knownasilya** [comment]
I already released it, so it should work.

**Comment by xgalen** [comment]
It also works, right :)

**Comment by knownasilya** [comment]
@rohanoberoicornell  does this fix your issue (try master branch of this repo)?

**Comment by rohanoberoicornell** [comment]
Hi Ilya, I will let you know when I get a chance to verify.
