### ISSUE TITLE
whats the matter

### ISSUE THREAD

**Issue by crazyhuoshan** [Strider-CD/strider#938]
![image](https://cloud.githubusercontent.com/assets/13940888/15670212/c2f284d8-2756-11e6-9586-6eef7cfdc37c.png)

**Comment by oliversalzburg** [comment]
The error message indicates that the user you're running strider as isn't allowed to write into `/home/strider/.npm`. Maybe you did a `sudo npm install` in `/home/strider`

**Comment by crazyhuoshan** [comment]
![image](https://cloud.githubusercontent.com/assets/13940888/15670607/e4a7ee54-2758-11e6-998e-9f94ae5c448a.png)
but i give the permission
sorry i'm a green hand

**Comment by oliversalzburg** [comment]
Maybe the permissions aren't right for folders below `.npm`. Check `ls -lha /home/strider/.npm`. Also, what user are you using to run strider (`ps aux|grep strider`)?
