### ISSUE TITLE
Wrong routing to jobs

### ISSUE THREAD

**Issue by nomean42** [Strider-CD/strider#939]
When im trying to get http://server:port/org/repo/job/id, strider send me to latest job. Is there some setting or what?

**Comment by knownasilya** [comment]
This is a known bug. I think someone has tried to address but without success. Seems like the angular router isn't setup correctly for jobs on url load.

**Comment by nomean42** [comment]
Looks like i will be the next who will try, it drive me mad.

**Comment by oliversalzburg** [comment]
Someone tried to fix it, but the fix broke something else. I was affected by that and the fix was reverted. Wouldn't mind a solution either, but you can just click other jobs back and forth until you have the right one.

Annoying, but not annoying enough that I would have wanted to fix it yet :P

**Comment by oliversalzburg** [comment]
I think this is the ticket we had in mind: https://github.com/Strider-CD/strider/pull/857

**Comment by nomean42** [comment]
it looks like i got solution, a little bit testin needed ) 
http://109.194.34.246:8181/jiralion/ert-stb/job/57517e4b3453c937045ab58c

**Comment by knownasilya** [comment]
Nice 👍

**Comment by knownasilya** [comment]
Should be resolved by https://github.com/Strider-CD/strider/commit/ecbef16dc6fb86606afde51ceaf9cd730aa0c4a5
