### ISSUE TITLE
AuthorizationError: The redirect_uri MUST match the registered callback URL for this application

### ISSUE THREAD

**Issue by crazyhuoshan** [Strider-CD/strider#940]
HELP!~~
![image](https://cloud.githubusercontent.com/assets/13940888/15776550/f6903a36-29ba-11e6-90df-8488806a4214.png)

**Comment by knownasilya** [comment]
What are you trying to do and what steps did you follow to setup Strider?

**Comment by crazyhuoshan** [comment]
i add a git project then i want to add another,so i click the button 
![image](https://cloud.githubusercontent.com/assets/13940888/15990089/60b09dc2-30bc-11e6-834d-cdbf7d403a4e.png)
then error

**Comment by crazyhuoshan** [comment]
![Uploading image.png…]()

**Comment by knownasilya** [comment]
Did you follow the readme instructions in the strider-github repo?

**Comment by dmineglobal** [comment]
not working with domain name as it got worked in localhost
