### ISSUE TITLE
restartJob: not implemented

### ISSUE THREAD

**Issue by virajsoni06** [Strider-CD/strider#945]
Hi,

I'm fairly new to CI and just getting started with it. I have it configured and running on my server. However when I try to restart a job nothing happens and console throws the following error

`restartJob: not implemented`

What could be the problem here?

**Comment by knownasilya** [comment]
It's not implemented yet 😄 I should probably remove that link.

**Comment by virajsoni06** [comment]
Ah! Any plans to add it near future?

@knownasilya Are there any workarounds to get this working, which I can use for now?

**Comment by knownasilya** [comment]
You can do a manual test/deploy from the build page (as long as the repo is still on the same commit).

**Comment by virajsoni06** [comment]
Yeah. But in my case sometimes I need to push the older versions on a staging server. 
In that case, I'd like to avoid `git revert` and do it directly from Strider. It is much cleaner and faster way to do it

**Comment by knownasilya** [comment]
@virajsoni06 I understand. Not sure when I'll get to it. Feel free to tackle it in the mean time, the code can go here: https://github.com/Strider-CD/strider/blob/master/lib/websockets.js#L294

**Comment by knownasilya** [comment]
I'm going to close this, and you can continue discussion in https://github.com/Strider-CD/strider/issues/824 if you want.

**Comment by virajsoni06** [comment]
Sure, I'll look into it. Thanks for your help @knownasilya
