### ISSUE TITLE
Build process stuck in testing phase

### ISSUE THREAD

**Issue by thedewpoint** [Strider-CD/strider#949]
I'm building a nodejs project , my unit tests are written with mocha and invoked using gulp-mocha during the test phase. When my test fails it accurately fails the build. When I comment out my test completely the build turns green. But when my tests run and they pass, it says tests success test completed, but the build keeps spinning and never turns green.

**Comment by oliversalzburg** [comment]
Could you share some more details? How are your tests invoked? `npm test`? Can you see if some process is still running? Will it timeout at some point? Maybe even a screenshot of the build output?

**Comment by thedewpoint** [comment]
In the custom script plugin in the test phase I run gulp test, which just
runs gulp-mocha. Tests run perfectly but the build just keeps spinning
after they finish. Im out right now but will post screenshots and code
snippets when I get home. Thanks for taking a look in the meantime

**Comment by oliversalzburg** [comment]
If possible, I'd also love to see the log of strider itself. Maybe there are some errors. I've personally never used the custom plugin to run the tests. I just put my test command in the `scripts` section of my `package.json`.

Maybe there is some bug in the strider-custom plugin... Hard to say. Would love more input :)

**Comment by knownasilya** [comment]
When you run the test locally, does it return to the console input? Or do you have to use ctrl+c?

**Comment by thedewpoint** [comment]
Now that you mention it, I believe it stays open and I had to end it with
ctrl+c. This might be a gulp issue and not strider issue. I will verify
when I'm home and if so will close this issue. Thanks for your help

**Comment by thedewpoint** [comment]
@knownasilya @oliversalzburg Looks like this was a gulp-mocha issue associated with supertest. Here is the related issue. https://github.com/sindresorhus/gulp-mocha/issues/28 
I fixed this by implementing gulp-exit. Thanks again for the quick responses & help.
