### ISSUE TITLE
[build:passing] badges

### ISSUE THREAD

**Issue by jaredly** [Strider-CD/strider#95]
Everybody loves those. Also, if they were given a special strider flare, it could help with publicity.
is there an svg of the strider logo anywhere?

**Comment by Pithikos** [comment]
@cusspvz thanks for the link but I am still unsure how to install it. [This](https://github.com/Strider-CD/strider/wiki/Managing-Plugins) doesn't work for me and I don't seem to be able and find instructions on how to install the plugin manually. Isn't there a way to just `git clone` in a folder?

Notice that I don't have experience with node.js and I run Strider in a Docker container.

**Comment by knownasilya** [comment]
@Pithikos just use the plugin manager from 'Admin' menu.

**Comment by Pithikos** [comment]
The only plugins I see as *Available* are:

* Email Notifier
* Environment
* Heroku
* Metadata
* Node
* Python
* Ruby
* Slack
* SSH Deply

Am I missing something?

**Comment by knownasilya** [comment]
@Pithikos sounds like you looking in a projects plugin section, not the 'Admin' plugins section

**Comment by Pithikos** [comment]
I thought you meant that since on the Admin tab there is only Invites, Users and Projects. Check pic below.

[](http://s10.postimg.org/e4i9b3cbd/Screenshot_from_2015_03_12_20_58_11.png)

**Comment by knownasilya** [comment]
@Pithikos what version of Strider are you using? Plugin manager is available since 1.6.0 https://github.com/Strider-CD/strider/blob/master/ROADMAP.md#160---2015-01-10

**Comment by knownasilya** [comment]
If you don't feel like upgrading, do `npm install strider-build-badge --save` in the strider directory.

**Comment by Pithikos** [comment]
Thanks. I upgraded eventually but for some reason I couldn't get the plugin through `strider install strider-build-badge` (some message about not being valid or in a rep - can't remember). Anyway I solved it by simply using the command you mentioned.

Then I simply modified the `README.md` on my github project by adding the line `!(Build status)[http://my-strider-instance/test/repo/badge?branch=master]` and voila!

**Comment by knownasilya** [comment]
For strider install, you'd have to do `bin/strider install [plugin-name]` from the strider directory, unless you installed strider as a global, then your command is correct. Would appreciate it if you could post the error you got.

**Comment by Pithikos** [comment]
I am not sure if this is a problem with Strider itself or the way I run it. Below is a way to reproduce the error (notice I use [my own container](https://github.com/Pithikos/Dockerfiles/blob/master/strider-docker/Dockerfile)).

Making the Strider image and running it:
````
git clone https://github.com/Pithikos/Dockerfiles && cd Dockerfiles/strider-docker
./preprocess && docker build -t strider .
ID=$(docker run -d --privileged -v $PWD/data/db:/data/db -p 3000:3000 strider)
````

Trying to add the plugin:
````
docker exec -it $ID bash
strider@6cb5b68d3f0f:~/.strider$ strider install strider-build-badge
  GET [ecosystem]/plugins.yml
  strider-build-badge is not a valid plugin
````

**Comment by knownasilya** [comment]
Oh, for `strider install`, you have to use the id [here](https://github.com/Strider-CD/ecosystem-index/blob/master/plugins.yml#L178).

**Comment by knownasilya** [comment]
I added a note to the cli readme, [here](https://github.com/Strider-CD/strider-cli/blob/master/README.md#install).

**Comment by Pithikos** [comment]
I also noticed that I could skip the whole procedure if I upgrade. It looks like the latest release has buildbadge pre-installed.
