### ISSUE TITLE
Make admin triggers an email with details to core@beyondfog.com

### ISSUE THREAD

**Issue by datashaman** [Strider-CD/strider#950]
Great work. However, when an admin is created, an email is sent to core@beyondfog.com with this information. Not ideal. :)

Putting that email address into process.env would solve this - not sure what you want to call it, otherwise I'd do it myself as a PR.

The literal email address is set in [lib/email.js @ line 164](https://github.com/Strider-CD/strider/blob/master/lib/email.js#L164).

**Comment by oliversalzburg** [comment]
wtf...

**Comment by datashaman** [comment]
The literal session_secret and smtp_from values should probably also change in [libconfig.js](https://github.com/Strider-CD/strider/blob/master/lib/libconfig.js).

The session_secret should be controlled by process.env, and I'd suggest changing that address to the harmless `no-reply@example.com`.

**Comment by oliversalzburg** [comment]
@datashaman Those values are already overridden by the environment.

**Comment by datashaman** [comment]
I see SMTP_FROM but no mention in README of how to override or set the session's secret key.

**Comment by oliversalzburg** [comment]
Then the issue is that it is undocumented, but the values from the environment are supposed to be respected.
