### ISSUE TITLE
localhost:3000 ahh!

### ISSUE THREAD

**Issue by crobinson42** [Strider-CD/strider#967]
Hi, I just installed Strider (I think it's awesome and has a great future ahead!). I'm noticing I'm experiencing a lot of the same issues everyone is mentioning that is all converging on a similar symptom `localhost:300`.  I followed the documentation, setting everything up and running just fine on Ubuntu 14.04 but still seem to see the `localhost:3000` sprinkled everywhere:
- resetting password
- github webhook (on the github site after authorizing)
- github authorize callback url
- 'make project public' setting url

Here are just a few I immediately saw with the same issue:
#748  #940  #323 

What is causing everything to default to `localhost:3000`? I've configured all env vars... any help?

**Comment by knownasilya** [comment]
did you set `SERVER_NAME` env? https://github.com/Strider-CD/strider#configuring

**Comment by crobinson42** [comment]
I did setup the ENV var `SERVER_NAME` and restarted the process, then added the github hooks. I'm wondering it's referencing the ENV var `STRIDER_SERVER_NAME`?

**Comment by knownasilya** [comment]
See if that helps. Sounds like a possible bug with the `rc` module.

**Comment by crobinson42** [comment]
**Posting for anyone who comes across in the future.**

## Problem

I am seeing localhost:3000 in place of my ENV variable `SERVER_NAME`.

_I am using PM2 to run the Strider process on my Linux box. I am putting my ENV variables in `~/.profile_

## Solution

Move ENV variables to `~/.bash` or `~/.bashrc` and use `export`. Moving this out of `~/.profile` allows PM2 process to access the ENV variables. Using `export` when declaring the ENV variables allows sub-processes access to them (ie: `SERVER_NAME=http://farm.website.com` vs `export SERVER_NAME=http://farm.website.com`).

Run: `source ~/.bashrc` <-- refreshes your changes to the file.

DELETE the existing PM2 process and start a new PM2 Strider process.

**Comment by crobinson42** [comment]
@knownasilya thanks for the minutes of your time.

**Comment by oliversalzburg** [comment]
If you're using pm2, you could just create an [application declaration](http://pm2.keymetrics.io/docs/usage/application-declaration/) and put your variables in the `env` section.

**Comment by knownasilya** [comment]
Why use pm2? Strider is already clustered and has auto restart on failure.
