### ISSUE TITLE
Job Console Preservation/Persistence in DB

### ISSUE THREAD

**Issue by crobinson42** [Strider-CD/strider#969]
Could this be a feature to have the job console saved in the DB?

**Comment by knownasilya** [comment]
The results are saved in the db.

**Comment by crobinson42** [comment]
That's interesting, I don't see them under and document. I'm referring to the console output for example while `npm install` is running, etc..

**Comment by knownasilya** [comment]
Should be in the job documents, https://github.com/Strider-CD/strider/blob/master/lib/models/job.js#L30

**Comment by crobinson42** [comment]
> Robomongo is awesome btw!

I'm seeing it now. Thx.
