### ISSUE TITLE
Install error on Ubuntu 14.04

### ISSUE THREAD

**Issue by SarasArya** [Strider-CD/strider#972]
I am running a VPS on digital ocean with Ubuntu 14.04. I recently installed strider as a global module. i.e. `npm install -g strider`  in my` /usr/local/` directory where permission is granted. So I went to into `/usr/local/lib/node_modules/strider` and __created__ a `.striderrc` file. Now in the same folder when I try to do npm start or bin/strider as mentioned in a document. It gives an error. 

```
vehico@vehico-prod-ops:/usr/local/lib/node_modules/strider$ bin/strider 
{ [Error: Cannot find module '../build/Release/bson'] code: 'MODULE_NOT_FOUND' }
js-bson: Failed to load c++ bson extension, using pure JS version
31058 forked
{ [Error: Cannot find module '../build/Release/bson'] code: 'MODULE_NOT_FOUND' }
js-bson: Failed to load c++ bson extension, using pure JS version
2016-08-02T10:23:39.464Z - info: RUNNER INIT
 
```

I don't know what more is to be added. Help is appreciated.

**Comment by oliversalzburg** [comment]
Those errors are not actually errors, as the module falls back to a JS version.

**Comment by SarasArya** [comment]
Okay. Then should it not be a warning?  I am also unable to use my.example.com:3000  and see strider homepage.

**Comment by oliversalzburg** [comment]
The message is emitted from the bson module, not Strider.
