### ISSUE TITLE
When configuring  java project from github using custom script plugin, nothing happens.

### ISSUE THREAD

**Issue by iandesj** [Strider-CD/strider#976]
I will add code for prepare and test, but it never persists. I have been able to reproduce this at least a dozen times.

**Comment by knownasilya** [comment]
Do you click save at the bottom of the page?

**Comment by iandesj** [comment]
I did click save at the top and bottom. Just now I downgraded my node version from 6.X to 4.4.7, looks like my configurations are saving now. Kind of odd, but may be something to note as far as node version goes.
