### ISSUE TITLE
.striderrc vs apps.js and various Strider woes

### ISSUE THREAD

**Issue by mark-norgate** [Strider-CD/strider#978]
I am currently learning about installation and configuration of Strider CI on Ubuntu but seem to be taking two steps forward and one step back all of the time!

I have a few questions that I would appreciate help with:
- what is the difference between `.striderrc` and `apps.js`? [Some documents](https://www.skey.uk/How-to/DevOps/12-Continuous-Integration-with-Strider) talk about .striderrc but [others](https://futurestud.io/blog/pm2-advanced-app-configuration-with-json-file) talk about apps.js
- I have been able to launch Strider from the command line using a command similar to this: `SERVER_NAME="ec2-xx-xx-xx-xx.compute-1.amazonaws.com:3000/" npm start`. I have then been able to successfully navigate to Strider and Bitbucket via Strider; but trying to convert this to a command in my `apps.js`, which I do like this: 

```
{
  "apps": [
    {
      "name": "strider",
      "script": "bin/strider",
      "instances": 1,
      "instance_id_env": "STRIDER_APP_INSTANCE",
      "exec_mode": "fork",
      "env": {
        "NODE_ENV": "production",
        "SERVER_NAME": "http://ec2-xx-xx-xx-xx.compute-1.amazonaws.com",
        "PORT": "3000",
        "DB_URI": "mongodb://strider:password"
      }
    }
  ]
}
```

and then launching with `pm2 start apps.js`, Strider will not even launch. I get a 'refused to connect' error in my browser. The Strider error logs are empty.
When I previously launched Strider on the command line without using PM2, I had to specify the username of `ubuntu` for AWS Ubuntu instance. Where do I specify that here?

I haven't even gotten to the app config yet!

**Comment by xgalen** [comment]
You say the logs are empty. Are you defining the log variables in the JSON file?
From your docs with `pm2`:
```
error_file: location of your apps error log file, e.g. "logs/blog.stderr.log"
out_file: location of your apps out log file, e.g. "logs/blog.stdout.log"
```

**Comment by mark-norgate** [comment]
I understood that the logs defaulted to the `.pm2` folder. If I do `pm2 show 0`, I get logs specified at `/home/ubuntu/.pm2/logs/strider-error-0.log` and others; but, as I say, they are empty.

**Comment by oliversalzburg** [comment]
To get any log output, make sure to set the `DEBUG` environment variable to `strider*`.

**Comment by xgalen** [comment]
@mark-norgate did the logs work finally?

**Comment by knownasilya** [comment]
I think the docs have been updated and DEBUG should help with logs.
