### ISSUE TITLE
Bitbucket & Strider: 500 InternalOAuthError: failed to obtain request token

### ISSUE THREAD

**Issue by mark-norgate** [Strider-CD/strider#980]
I have gotten to the stage of managing to get the Bitbucket link to appear within the Strider dashboard. However, clicking on it yields the following result:

```
Connect
500 InternalOAuthError: failed to obtain request token
   at /home/ubuntu/strider/node_modules/strider-bitbucket/node_modules/passport-oauth/lib/passport-oauth/strategies/oauth.js:196:36
   at /home/ubuntu/strider/node_modules/strider-bitbucket/node_modules/oauth/lib/oauth.js:543:17
   at passBackControl (/home/ubuntu/strider/node_modules/strider-bitbucket/node_modules/oauth/lib/oauth.js:397:13)
   at IncomingMessage.<anonymous> (/home/ubuntu/strider/node_modules/strider-bitbucket/node_modules/oauth/lib/oauth.js:409:9)
   at emitNone (events.js:91:20)
   at IncomingMessage.emit (events.js:185:7)
   at endReadableNT (_stream_readable.js:975:12)
   at _combinedTickCallback (internal/process/next_tick.js:74:11)
   at process._tickDomainCallback (internal/process/next_tick.js:122:9)
```

I have obtained the OAuth consumer details from Bitbucket and have configured the Callback URL to what I _think_ might be correct...

I have configured the hell out of the Strider instance, by setting `SERVER_NAME`, `PLUGIN_BITBUCKET_APP_KEY`, and `PLUGIN_BITBUCKET_APP_SECRET` in the terminal and within the `.striderrc`. What else do I need to do? 

I have previously witnessed this working with my own very eyes, but there doesn't appear to be an solution anywhere on the world wide interweb. my OAuth knowledge is minimal so I'm finding it hard to use any brute-force method of fixing.

Literally gagging to hear your replies.

**Comment by oliversalzburg** [comment]
Two things to try:
1. Clear the URL and Callback URL in the OAuth consumer settings on Bitbucket
2. Try updating strider-bitbucket to the latest code revision from GitHub

**Comment by oliversalzburg** [comment]
Closed in favor of https://github.com/Strider-CD/strider-bitbucket/issues/39
