### ISSUE TITLE
Missing dependencies when `npm i`-ing

### ISSUE THREAD

**Issue by davemackintosh** [Strider-CD/strider#981]
I cloned the repo to my target server, ran `npm i` and then tried to create the initial user.

Had to manually install missing dependencies while trying to run `node bin/strider addUser`

```
strider-cli
mongoose
debug
lodash
bcryptjs
gravatar
async
everypaas
rc
passport
strider-extension-loader
global-tunnel
express
bluebird
cors
swig
morgan-debug

```

**Comment by davemackintosh** [comment]
I'm wondering if something has gone wrong with the `npm install` just testing.

**Comment by davemackintosh** [comment]
Works fine if I `sudo npm i -g strider`

**Comment by oliversalzburg** [comment]
Weird. What's the output when you `npm i` after cloning?

**Comment by davemackintosh** [comment]
It completes with success. I see the same issue with the `npm` package if I `rm -rf node_modules` and `npm i`

**Comment by oliversalzburg** [comment]
What version of node/npm?

**Comment by davemackintosh** [comment]
Node 6.3.1
npm 3.10.3

**Comment by oliversalzburg** [comment]
Works for me with a fresh clone. Same versions for node/npm

**Comment by vinaydate** [comment]
I am facing same problem.
My node version is: 6.9.2
My NPM version is: 3.10.9

After cloning, `npm i` does show that things are installed, but running `npm start` pops up series of 'packages not found' type of errors, and I tried to install manually those packages. But lost my patience.

**Comment by knownasilya** [comment]
Does it finish installing without an error?

**Comment by vinaydate** [comment]
@knownasilya When cloning repo and doing `npm i`, npm installations are aborted with error:

> Killed   ..........] \ fetchMetadata: sill mapToRegistry uri https://registry.npmjs.org/tar-stream

BTW, there are 9 warnings regarding deprecations or outdated packages

**Comment by knownasilya** [comment]
Could you also post your `npm-debug.log` contents, thanks.

**Comment by vinaydate** [comment]
@knownasilya, I could not find npm-debug.log file. Please tell me where does this file reside?

**Comment by knownasilya** [comment]
it'll be in the directory you run `npm i` if there is an error.

**Comment by vinaydate** [comment]
@knownasilya, there is no npm-debug.log file in the folder.

**Comment by knownasilya** [comment]
Can you try `npm install --loglevel verbose` and paste the results

**Comment by oliversalzburg** [comment]
Wasn't there some problem with npm3 because some packages expected to find their dependencies at fixed locations?

**Comment by knownasilya** [comment]
Not aware, I use npm 3. Maybe a certain version of 3?

**Comment by vinaydate** [comment]
@knownasilya
`npm install --loglevel verbose &> npmlog.txt` generates following file.

[npmlog.txt](https://github.com/Strider-CD/strider/files/699313/npmlog.txt)

And "Killed" message is displayed on terminal

**Comment by knownasilya** [comment]
I don't see anything obvious on npm's side. Maybe your system kills the process because it's taking too long or something. I'd check your system logs.

**Comment by vinaydate** [comment]
@knownasilya, Appreciate your help. Please elaborate regarding system logs.
P.S. I am a newbie as far as Linux and npm goes.

**Comment by knownasilya** [comment]
Maybe give this a try https://www.digitalocean.com/community/questions/npm-gets-killed-no-matter-what?answer=18115

**Comment by vinaydate** [comment]
@knownasilya, yes, it was memory issue. I created a swapfile n it worked. Thank you

**Comment by oliversalzburg** [comment]
@davemackintosh Did you ever get the original issue resolved? Maybe a memory issue as well?

**Comment by davemackintosh** [comment]
@oliversalzburg Unfortunately I did not, I went with CircleCI instead for that particular client.

**Comment by oliversalzburg** [comment]
@davemackintosh Thanks for getting back to me. I'll close the ticket for now.
