### ISSUE TITLE
Cannot checkout from Bitbucket using Strider

### ISSUE THREAD

**Issue by mark-norgate** [Strider-CD/strider#982]
I am launching Strider quite successfully using `pm2`. I have the `strider-bibucket` plugin installed which appears to be functioning inasmuch as the repos are appearing from my Bitbucket account.

However, when trying to checkout, or pull, the repository using the `Add` button and specifying the project type, I receive a red toastie error box like this:

```
Error creating project for repo company/product: {"results":[],"status":"error","errors":[{"code":500,"reason":"Failed to setup repo: undefined"}]}
```

Anyone have any idea what this pertains to and how to solve it?

**Comment by oliversalzburg** [comment]
Please check the server-side logs if they contain more details. We have made pretty extensive changes to the logging in the latest source code snapshots (not everything has been released to npm yet).
You're going to want to set the environment variable `DEBUG` to `strider*`. If that's not helpful, try installing the latest source code snapshots of Strider and the plugins you're using.

**Comment by oliversalzburg** [comment]
Also, please don't post the same issue on multiple trackers, we're monitoring all of them ;)

Closing in favor of https://github.com/Strider-CD/strider-bitbucket/issues/42

**Comment by mark-norgate** [comment]
Oh right, sorry I didn't realise. I'll post on the `strider-bitbucket` board from now on.

**Comment by mark-norgate** [comment]
I have set the environment variable `DEBUG` to `strider*`. Here is my config:
```
{
	"NODE_ENV": "production",
	"SERVER_NAME": "http://ec2-xx-xx-xx-xx.compute-1.amazonaws.com",
	"STRIDER_CLONE_DEST": "/home/ubuntu/strider-builds/",
	"PORT": "3000",
	"DEBUG": "strider*"
}
```
My `apps.json` looks like this:
```
{
  apps: [
    {
      "name": "strider",
      "script": "bin/strider",
      "instances": 1,
      "instance_id_env": "STRIDER_APP_INSTANCE",
      "exec_mode": "fork",
      "env": {
        "NODE_ENV": "production",
        "SERVER_NAME": "http://ec2-xx-xx-xx-xx.compute-1.amazonaws.com:3000",
        "PORT": 3000,
        "PLUGIN_BITBUCKET_APP_KEY": "xx",
        "PLUGIN_BITBUCKET_APP_SECRET": "xxx"
      }
    }
  ]
}
```
The `pm2.log` file isn't particularly illuminating. It looks a lot like this over and over:
```
2016-08-14 10:21:27: App [strider] with id [0] and pid [13482], exited with code [0] via signal [SIGINT]
2016-08-14 10:21:27: Starting execution sequence in -fork mode- for app name:strider id:0
2016-08-14 10:21:27: App name:strider id:0 online
``` 
`strider-error.log` is empty, but `strider-out.log` looks like this:
```
2016-08-14T10:22:28.669Z - warn: Trying to attach a bitbucket account that's already attached...
2016-08-14T10:31:07.928Z - warn: Trying to attach a bitbucket account that's already attached...
2016-08-14T16:16:45.482Z - warn: Trying to attach a bitbucket account that's already attached...
```
Do I need to install a later version of `strider-bitbucket`? I didn't quite grasp the comment on the other board.
