### ISSUE TITLE
object with ciircular reference passed to `defaultVal()`

### ISSUE THREAD

**Issue by TibboddiT** [Strider-CD/strider#984]
I came across an edge case where the [`defaultVal()`](https://github.com/Strider-CD/strider/blob/master/lib/utils/index.js#L141) function was called with an object containing circular reference.
As you can imagine, maximum call stack size was reached.
FYI, it is related to the github plugin, when a test for a pull request is started and a previous one on the same branch is already running. To be honest, i'm surprised no one else has encountered this before.
I dirty fixed it, limiting the recursion in [`defaultVal()` and `defaultSchema()`](https://github.com/Strider-CD/strider/blob/master/lib/utils/index.js#L141-L162), but it would probably be better to prevent these functions to visit a property already visited before. I assume some npm packages exist to do exactly this kind of checks.
I can't make a PR right now, because i don't have a dev env ready, but *maybe* next week or so if not fixed before :)

**Comment by Arkotek** [comment]
It may help solving circular issues: https://github.com/soyuka/fclone

**Comment by oliversalzburg** [comment]
I had encountered this before and I think c6ded4bca6fe94d42a3864671bdb94d5e61124cb is the fix for it. These functions are not supposed to be used on structures that have circular dependencies, that in itself is a bug. If it surfaces through the "max call stack size exceeded", that's actually a good thing :P (aka not a bug, it's a feature)

**Comment by TibboddiT** [comment]
> I think c6ded4b is the fix for it

Absolutely. I should have updated before opening an issue, my bad.

>  If it surfaces through the "max call stack size exceeded", that's actually a good thing :P (aka not a bug, it's a feature)

You're right, at least the error can reveal a misuse of the function, but i thought throwing an error with a nice message would be cleaner... Those stack traces of recursive calls are so useless, we can't even know what was the bad call that started the mess ;)

Anyway, I close the issue since it was already fixed !
