### ISSUE TITLE
Can't add collaborator

### ISSUE THREAD

**Issue by mnikson** [Strider-CD/strider#990]
When I'm trying to add collaborator in project (imported from Bitbucket), in console I found error with status 404 - Page not found (POST /:bitbucket/:project/collaborators/) and in response: Project not found. Strider version is 1.9.0

**Comment by knownasilya** [comment]
Thanks, will look into the issue.

**Comment by knownasilya** [comment]
Give 1.9.1 a try

**Comment by mnikson** [comment]
Now it work fine. Thanks
