### ISSUE TITLE
Outdated dependencies

### ISSUE THREAD

**Issue by ndaidong** [Strider-CD/strider#995]
It seems there were many outdated dependencies:

![](http://i.imgur.com/US3vCPG.png)

Do you still maintain this project? Can I contribute to this repo?

Dong

**Comment by oliversalzburg** [comment]
Go ahead. The fork button is in the top right :)

**Comment by xgalen** [comment]
Maybe https://github.com/Strider-CD/strider/pull/1023 solves this?

**Comment by knownasilya** [comment]
Swig is one of the ones that that had big breaking changes and needs some work to update.

**Comment by xgalen** [comment]
What module have you chosen to replace `Swig`?

**Comment by knownasilya** [comment]
Probably handlebars, but it might be easier to just update to the latest swig, since we use a good number of it's features.

**Comment by xgalen** [comment]
But swig is not maintained anymore: https://github.com/paularmstrong/swig

**Comment by knownasilya** [comment]
Oh, wasn't aware.
