### ISSUE TITLE
Restore User and Projects

### ISSUE THREAD

**Issue by zebamba** [Strider-CD/strider#996]
I am testing strider. 

I added an user and projects had been set up for that user.

On user section I don't see option to disable that user so I clicked on remove and all the projects
are gone.

Is there a way to restore the projects or the user and the projects?

**Comment by xgalen** [comment]
I think if you have removed something, you need to re-add it. There is no way to restore as far as I know.

**Comment by knownasilya** [comment]
@xgalen do you want to be added as a maintainer?

**Comment by xgalen** [comment]
That would be nice @knownasilya . If do that, please give me some guidance about it and I'll be glad to help as much as possible. Thanks!
